### ISSUE TITLE
Missing persister injection

### ISSUE THREAD

**Issue by cursedcoder** [hautelook/AliceBundle#100]
https://github.com/hautelook/AliceBundle/blob/master/Resources/config/services.xml#L24

should have: 

```xml
<service id="hautelook_alice.alice.fixtures.persister" class="Nelmio\Alice\Persister\Doctrine">
    <argument type="service" id="doctrine.orm.entity_manager" />
</service>

<service id="hautelook_alice.alice.fixtures.loader" class="Nelmio\Alice\Fixtures\Loader">
    <argument>%hautelook_alice.locale%</argument>
    <argument type="expression">service('hautelook_alice.faker.provider_chain').getProviders()</argument>
    <argument>%hautelook_alice.seed%</argument>
    <argument type="expression">service('service_container').getParameterBag().all()</argument>
    <call method="setLogger">
        <argument type="service" id="logger" on-invalid="ignore" />
    </call>
    <call method="setPersister">
        <argument type="service" id="hautelook_alice.alice.fixtures.persister" />
    </call>
</service>
```

otherwise `TypeHintChecker` will throw with:
  
    To reference objects by id you must first set a Nelmio\Alice\PersisterInterface object on this instance

**Comment by theofidry** [comment]
I would rather set the persister in the `Hautelook\AliceBundle\Alice\DataFixtures\Loader::load()` as the persister changes depending of the database use. Plus it would make more sense as you inject the persister in the `::load()` method.

Thanks for pointing that out, #101 should solves this, but I would like to have a test suite which reproduce this error, could you give me one?

**Comment by theofidry** [comment]
I might reword that: could you give me a scenario where such error occur?
