### ISSUE TITLE
Doctrine fixtures: This method was not expected to be called.

### ISSUE THREAD

**Issue by Soullivaneuh** [hautelook/AliceBundle#102]
With the `doctrine:fixtures:load` command, since `v1.0.0-beta.2`, I get this error:

```
This method was not expected to be called.
```

I know you now have your own command but I need doctrine one too.

This break the compatibility.

My fixture class:

```php
namespace AppBundle\DataFixtures\ORM;

use Hautelook\AliceBundle\Doctrine\DataFixtures\AbstractLoader;

/**
 * @author Sullivan Senechal <soullivaneuh@gmail.com>
 */
class AppFixtures extends AbstractLoader
{
    /**
     * {@inheritdoc}
     */
    public function getFixtures()
    {
        return [
            __DIR__.'/fixtures.yml',
            __DIR__.'/accounting.yml',
            __DIR__.'/user_browser.yml',
        ];
    }
}
```

**Comment by theofidry** [comment]
It's definitely not a behaviour wished. I'll check that thanks for rising the issue.

**Comment by theofidry** [comment]
I've tagged a new beta release which includes the bugfix

**Comment by guill3m** [comment]
This doesn't seem to fix it, just get a different error.

With a loader exactly like @Soullivaneuh I get now a different error: **_Notice: Undefined offset: 0_**

**Comment by theofidry** [comment]
Can you print me the full error and running the command with the `-v` option?

**Comment by guill3m** [comment]
Sorry, it seems that it was related to a different issue. Looks like it works.

Amazing response time btw. Thanks.

**Comment by theofidry** [comment]
Cool, np :)

**Comment by guill3m** [comment]
Ok... so i sorted my issue. The only thing is that now when i run `doctrine:fixtures:load` command it does not load any of the alice fixtures. I notice that in the `Doctrine/DataFixtures/AbstractLoader.php` the loader does not do anything anymore. Do we have to implement that ourselves to be compatible with the Doctrine Fixtures Bundle? Perhaps https://github.com/hautelook/AliceBundle/blob/master/Resources/doc/doctrine-fixtures-bundle.md needs to be updated with the usage?

**Comment by theofidry** [comment]
Err, not sure of what you mean.

The bundle command to load fixtures does not rely on the loaders `::load()` method but on a loader service. The loaders `::load()` method is only used by the doctrine command.

You don't have much to do for the compatibility, as shown in the doc, there is some interfaces not supported, but otherwise there is nothing. However, if you wish to have the fixtures that you were declaring in your data loaders `::load()` method, you will have to get them out in a separate fixture file.

If you want to share some though on this or explain your use case I'll gladly help, but let's do this in a separate issue then.

**Comment by yakobe** [comment]
Hi. I'm also trying to use the `doctrine:fixtures:load` command to load fixtures. Are you saying we should use this bundle command instead and it will also load legacy fixtures?
I was hoping to just call `doctrine:fixtures:load` as normal and load all the fixtures (raw php and alice).

**Comment by theofidry** [comment]
> Hi. I'm also trying to use the doctrine:fixtures:load command to load fixtures. Are you saying we should use this bundle command instead and it will also load legacy fixtures?

No it will not, If your fixtures are specified via the data loader `::getFixtures()` yes it will, if they are declared in the `::load()` no.

> I was hoping to just call doctrine:fixtures:load as normal and load all the fixtures (raw php and alice).

I get your point, but there's a fundamental difference between AliceBundle and DoctrineFixturesBundle. For DoctrineFixturesBundle, a data loader is a fixture and you have to handle the persistence at the data loader level. In the 0.2 version of AliceBundle, the logic has been to add the possibility to include fixtures files if you wished for it and still rely on DoctrineFixturesBundle command.

For the 1.0, with the upgrade of nelmio/alice to the 2.0 which is a complete rewrite, some things changed. Relying on Doctrine command was just becoming a real pain and did not make much sense.
