### ISSUE TITLE
Cannot truncate a table referenced in a foreign key constraint

### ISSUE THREAD

**Issue by jhcasado** [hautelook/AliceBundle#109]
I updated the bundle and now I'm having this error when I try the hautelook_alice:doctrine:fixtures:load command:

[Doctrine\DBAL\DBALException]
An exception occurred while executing 'TRUNCATE Users':  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`myproject`.`RefreshTokens`, CONSTRAINT `FK_CC8337FA76ED395` FOREIGN KEY (`user_id`) REFERENCES `myproject`.`Users` (`id`))                                                                                                                               

I'm using FOSUserBundle with FOSOAuthServerBundle.

I detected the commit that caused the problem: ef5c1176aa11ad02544a2632a91ebdc124afeda3

**Comment by jhcasado** [comment]
I'm having the same error if I use --purge-with-truncate.

Maybe in the update is using truncate by default?

Could you disable database foreign key checks before truncate?

**Comment by theofidry** [comment]
That's definitely a regression, I'll check as soon as I can.

**Comment by theofidry** [comment]
The error should have been solved, keep me informed if that's not the case

**Comment by jhcasado** [comment]
Works as expected,
thanks!
