### ISSUE TITLE
Multi thread loading

### ISSUE THREAD

**Issue by Soullivaneuh** [hautelook/AliceBundle#122]
Just an idea: Would be great if fixtures loading use my 4 processors instead of 1. :-)

**Comment by theofidry** [comment]
"If you want to do Java stuff go do some Java"

Kidding, just a bad quote^^ Yeah might be worth checking this indeed

**Comment by Soullivaneuh** [comment]
Ha ha! :-)

Maybe this library will help: https://packagist.org/packages/kriswallsmith/spork

**Comment by theofidry** [comment]
Update on the issue: I'm not sure this is doable as you are loading a whole set, and this are connected to each other, and then for the persistence there is a lock done on the database so I doubt there will be any serious gain.

Unless I'm missing something here, I don't think it can be of any help.
