### ISSUE TITLE
Alice Processors not working as stated in doc

### ISSUE THREAD

**Issue by odoucet** [hautelook/AliceBundle#138]
If we follow AliceBundle documentation on processors and add the following on services.yml : 
```yml
services:
    alice.processor.user:
        class: MyBundle\DataFixtures\Processor\UserProcessor 
        tags: [ { name: hautelook_alice.alice.processor } ]
```
and follow Alice documentation on how to write a processor (https://github.com/nelmio/alice/blob/master/doc/processors.md#processors): 
```php
namespace Acme\DemoBundle\DataFixtures\ORM;

use Nelmio\Alice\ProcessorInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class UserProcessor implements ProcessorInterface
{
    /**
     * @var ContainerInterface
     */
    protected $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function preProcess($object)
    {
    }

    public function postProcess($object)
    {
    }
}

```

, we have the following error : 

**[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to xxx\Processor\UserProcessor::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, none given, called in /xxx/app/cache/test/appTestDebugProjectContainer.php on line 422 and defined**

This is because we have no arg on __construct() when calling our own Processor.

I discovered that rewriting the Processor without arg on __construct works, but do not know if this is the correct behaviour. In all case, as this differs from Alice documentation, we should explain this in AliceBundle doc.

The working Processor class : 

```php
<?php

namespace MyBundle\DataFixtures\Processor;

use Nelmio\Alice\ProcessorInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class MyProcessor implements ProcessorInterface
{
    public function __construct()
    {
    }

    public function preProcess($object)
    {
    }

    public function postProcess($object)
    {
    }
}

```

**Comment by theofidry** [comment]
You're confusing several this here. A processor **must** implement `ProcessorInterface`. That's it. If you want to make it `ContainerAware`, extend a class or inject some dependencies in it via the constructor, it's entirely up to you.

Then once you have your processor, if you want AliceBundle to use it, you have to declare it as a service and add the tag `hautelook_alice.alice.processor` to your service.

That being said, Alice example is a bit confusing, I did a PR on it for that: nelmio/alice#274

Out of curiosity what are you using a processor for?

**Comment by odoucet** [comment]
I have some entities with a field "properties" containing XML. The XML must be generated based on the other properties (I use classic Faker formatters for them). 
So if I want to make my processor ContainerAware, I must pass the ContainerInterface through the service declaration. Will try to find how, and then I'll create a pull request to explain all this in doc to save time for others :)

**Comment by theofidry** [comment]
Well as I said it does not have any importance, the only requirement is that your processor implements the `ProcessorInterface` and is declared as a tagged service with the tag `hautelook_alice.alice.processor`. So the declaration you gave is correct provided `MyProcessor` implements `ProcessorInterface`.

**Comment by theofidry** [comment]
Closing the issue for now as it's to be solved on Alice end.
