### ISSUE TITLE
Clarify install doc

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#142]
As of now it's hard to get that you should have DoctrineBundle and Doctrine data fixtures installed for both AliceBundle working with doctrine...

Ex right now if trying to use it without installing Doctrine data fixtures:

```
PHP Fatal error:  Class 'Doctrine\Common\DataFixtures\Executor\ORMExecutor' not found in /path/to/vendor/hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/ORMExecutor.php on line 25
...
```

A friendlier message as well may be welcomed.

**Comment by NovikovViktor** [comment]
"Basic usage" documentation section include information about requeired installed Doctrine bundle and Doctrine fixtures bundle, you mean move this sentence to "Instalation" section?

**Comment by theofidry** [comment]
@NovikovViktor no, I mean that if you're using Doctrine ORM, you should install the packages `doctrine/doctrine-bundle` and `doctrine/data-fixtures`. They are only suggested cf the [`composer.json` L42 and 44](https://github.com/hautelook/AliceBundle/blob/master/composer.json#L42-L44). They are not hard dependency has you may use another Doctrine flavour (Doctrine ODM or Doctrine PHPCR) or whatever database manager for which a support is provided.

**Comment by NovikovViktor** [comment]
@theofidry , so in section "Instalation", should be mention about required installed some of these bundles, depends on project requirements?

**Comment by theofidry** [comment]
Yes or maybe provide the install guide for Doctrine ORM in the README and another page for installing the other ones.

**Comment by NovikovViktor** [comment]
@theofidry, ok. Could I make pull request for this?

**Comment by theofidry** [comment]
@NovikovViktor yes sure, feel free to contribute at any time :)
