### ISSUE TITLE
Final & Immutability

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#152]

**Comment by Soullivaneuh** [comment]
Could you... elaborate? :-)

**Comment by theofidry** [comment]
Haha, nothing much it was a personal note. I would like to check again to make immutable what can be immutable and also what should be defined as final.

**Comment by theofidry** [comment]
@Soullivaneuh maybe to elaborate a bit more: I think there isn't much classes that are mutable. I could not check again yet. On the final part I would say I would like to declare as final as many classes as possible. I believe flexibility should come from a good abstraction rather than inheritance. Making classes final may also help to spot wrong logic used in few places. This may lead to BC break though.

**Comment by Soullivaneuh** [comment]
If this BC breaks, it should be on next major. ;-)

**Comment by theofidry** [comment]
Yeah for now I want to check it and we can decide later on if we put that in the next major version or not. 

Putting a class final will undoubtedly create a BC break as it will break any inheritance, although the interface does not change...
