### ISSUE TITLE
Add the ability to call load fixtures command from another command/php script (or improve doc)

### ISSUE THREAD

**Issue by Yanncha** [hautelook/AliceBundle#153]
Hello,
Thanks to all contributors for development and maintenance work.

My use case for AliceBundle is to automatically load fixtures when launching test suite with PHPUnit, so I would like to include the call in PHPUnit bootstrap's process (from a bootstrap php file), along with other needed operations.

For some other commands I managed to adapt what I found on http://php-and-symfony.matthiasnoback.nl/2011/10/symfony2-use-a-bootstrap-file-for-your-phpunit-tests-and-run-some-console-commands/
I tried to do it as well for AliceBundle, but it is not possible directly as the loader command constructor needs some arguments. 
I was able to launch the command with 
```php
$kernel = new AppKernel('test', true);
$kernel->boot();
$application = new Application($kernel);
$application->run(new StringInput('hautelook_alice:doctrine:fixtures:load --append'));
```
But for some reason, the rest of the bootstrap process stops (and PHPUnit tests are not run).

The only solution I found now is using exec().

My question is, is there a clean way to do this (or maybe I'm taking the problem from the wrong side) ?
If so, it would be nice to document it somewhere. If not, would it be possible to add some support for a similar feature ?

Best regards.

**Comment by theofidry** [comment]
Hi @Yanncha.

If you take a look at [autoload.php](https://github.com/hautelook/AliceBundle/blob/master/tests/SymfonyApp/autoload.php) you'll see that there is no mention of the App and less about booting it. The reason is you should use [`KernelTestCase`](https://github.com/symfony/framework-bundle/blob/master/Test/KernelTestCase.php). You may extend it, boot the application and do what you want with it. You can take a look at [`CommandTestCase`](https://github.com/hautelook/AliceBundle/blob/master/tests/Doctrine/Command/CommandTestCase.php) from this bundle as a reference.

Tell me if it works for you and then yeah an entry in the doc would be very appreciated!

**Comment by Yanncha** [comment]
Hi, thank you for your quick answer and tip.

I created a helper class like this: 
```php
namespace myapp\commonBundle\Utils;

use Hautelook\AliceBundle\Tests\KernelTestCase;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;

class AliceFixturesLoader extends KernelTestCase
{
    protected $application;
    
    public function __construct() 
    {
        self::bootKernel();
        
        $this->application = new Application(self::$kernel);
        $this->application->setAutoExit(false);
    }

    public function load(array $options = [])
    {
        $options['command'] = 'hautelook_alice:doctrine:fixtures:load';
        $options['-e'] = 'test';
        
        return $this->application->run(new ArrayInput($options));
    }
}
```
called by the following piece of code in my bootstrap:
```php
$loader = new AliceFixturesLoader();
$options = array(
    '--append' => true,
    '--no-debug' => true
);
$loader->load($options);
```
However I get this error when launching PHPUnit (which then call the bootstrap script):
``` Fatal error: Class 'Hautelook\AliceBundle\Tests\KernelTestCase' not found in /apppath/src/myapp/commonBundle/Utils/AliceFixturesLoader.php on line 10 ```

Did I miss some point ?

**Comment by theofidry** [comment]
Why do you call it in the bootstrap file? The way you use your helper looks very weird to me: a testcase isn't meant to be used with a `::__construct()` method but rather with `::setUp()`, and then extended for the test cases where you want to use it. You shouldn't need to use the bootstrap file, the one provided by default in Symfony should be enough.

**Comment by Yanncha** [comment]
The thing is that I want the command to be run only once when I launch PHPUnit, that's why I was using a custom bootstrap (calling default one as well), whose main purpose is to purge the database and reset it in a known state.
I don't really need to call the command from a "real" test case or for each test.

**Comment by theofidry** [comment]
Then in that case I wouldn't bother trying to play with how PHPUnit internally works and bootstrap everything to isolate each tests to now how to share everything or run something like this. I would simply ensure the database is reset and loaded in `test` environment (maybe creating another database for the test environment) and then locally you just have to run it once, for CI you just have to add this step in the build process.

**Comment by Yanncha** [comment]
Well, that was the aim, that is reset the db in a known state. I don't really need fully isolated tests (these are functional tests by the way), I just need to be sure that I will find for example 3 users in the db, 2 of them being associated with an adress entity.
PHPUnit's bootstrap is just any php script you can run before the test suite is run. I need some cross-platform way (so no shell script) to purge db, run some init php script and load fixtures before the tests, bootstrap looked the easiest way.
It works for calling doctrine commands and some internal ones, but for alice bundle, as I said, the only solution I found till now is exec(), not sure it is really cross-platform though.

**Comment by theofidry** [comment]
Well then I'm not sure :( HautelookAliceBundle has nothing out of the ordinary so it looks weird that it's the one at fault. But from what I see in the comment blog posts there was somme issues coming from tweaking the bootstrap file.

**Comment by Yanncha** [comment]
I don't know, maybe it is just that a different loading mechanism is used. For example, to drop database, I can do it from the bootstrap file using 
```php
require_once __DIR__.'/AppKernel.php';
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Input\ArrayInput;
use Doctrine\Bundle\DoctrineBundle\Command\DropDatabaseDoctrineCommand;

$kernel = new AppKernel('test', true); // create a "test" kernel
$kernel->boot();
$application = new Application($kernel);

$command = new DropDatabaseDoctrineCommand();
$application->add($command);
$input = new ArrayInput(array(
    'command' => 'doctrine:database:drop',
    '--force' => true,
    '--no-debug' =>true
));
$command->run($input, new ConsoleOutput());
```

**Comment by theofidry** [comment]
by the way I think you should shut down the app after the loading. I'll try to take a look at that in the weekend.

**Comment by danielrestrepo** [comment]
Hello! Have you find a solution for this issue. I've been trying to do the same to load the fixtures before executing my test but to no avail.

My function is as follow:

```php
public function executeFixtures()
    {
        $kernel = $this->getContainer()->get('kernel');
        $aplication = new Application($kernel);
        $aplication->setAutoExit(false);

        $input = new ArrayInput(array(
            'command' => 'hautelook_alice:doctrine:fixtures:load'
        ));

        $output = new NullOutput();
        $aplication->run($input, $output);

        return new Response("");
    }
```

In this case the fixtures are not executed at all.

Thanks

**Comment by theofidry** [comment]
@danielrestrepo what is the context? Is your function part of a `KernelTestCase` or `WebTestCase`? Did you boot the kernel?

**Comment by danielrestrepo** [comment]
@theofidry it is part of WebTestCase. I did not boot the kernel, I was working on getting it to work  with exec().

**Comment by theofidry** [comment]
Sorry @danielrestrepo and @Yanncha, I can't work on this right now. @Soullivaneuh maybe have you tried to make it work this way?

**Comment by Yanncha** [comment]
Hello back,

for my use case, that is to load a small set of yml fixtures files from a php script, in the end it looks that the cleaner way to do it is to directly call nelmio alice loader
```php
$objects = \Nelmio\Alice\Fixtures::load(__DIR__.'/path/testFixtures.yml', $entityManager);
```
I think that it is better than calling AliceBundle using exec: ```exec('php app/console hautelook_alice:doctrine:fixtures:load --append --no-debug');``` even if this works.

**Comment by theofidry** [comment]
@Yanncha you may do that but then the issue is that you're not using the good faker instance so if you have custom providers and processors, or locale, this won't work.

**Comment by Yanncha** [comment]
Ah yes you're right. As for now I don't use custom providers, but for sure I have to adjust the config to use the right locale.

**Comment by theofidry** [comment]
It should be doable in the bootstrap still. I'm sorry I can't search for this right now, I hope someone will find an issue soon otherwise you'll have to wait a bit until I find some free time for that.

**Comment by Yanncha** [comment]
Ok. No problem for now as I have a workaround. Thanks a lot for your help anyways :)

**Comment by danielrestrepo** [comment]
@Yanncha @theofidry I found a quick and dirty workaround using exec as well:

```php
exec("cd /home/daniel/web/tests/tmootb/app && ./console h:d:f:l -e test --no-interaction");
```

I was in a hurry. Given enough time I'll find the proper way to do it and hopefully send a merge request. If you have any suggestion for finding a solution together I'll be more than happy to invest some hours in it.

Cheers!

**Comment by theofidry** [comment]
@danielrestrepo interesting. What I have in mind is roughly (haven't tested and written on the fly so I expect some errors):

```php
#!/usr/bin/env php
<?php

set_time_limit(0);
require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/app/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';
if ($debug) {
    Debug::enable();
}
error_reporting(E_ALL & ~E_USER_DEPRECATED);

$kernel = new AppKernel($env, $debug);
$kernel->boot();
$application = new Application($kernel);

$input = new ArrayInput(array(
    'command' => 'h:d:f:l',
    '--force' => true
));
$application->run($input);

$kernel->shutdown();
```

I don't often use `exec` so I'm not sure of how to bootstrap it with it. Any PR or work on this is welcome!

**Comment by danielrestrepo** [comment]
@theofidry great! I'll work on it and let you now.

**Comment by estahn** [comment]
@theofidry Did you had a chance to look at this? LiipFunctionBundle implements a `loadFixtures` method which can be called in the `setUp` method, e.g.:

```php
        $this->fixtures = $this->loadFixtureFiles(array(
            '@...Bundle/DataFixtures/ORM/baseline.yml',
            '@...Bundle/DataFixtures/ORM/users.yml'
        ));
```

Unfortunately it doesn't support custom faker/provider/processor atm which why i added a callout to Hautelook (https://github.com/liip/LiipFunctionalTestBundle/issues/181). It would obviously much better if thats implemented directly in AliceBundle.

I'm thinking about something like this:
```php
class SomeControllerTest extends BaseWebTestCase
{
    /**
     * An array with a list of generated fixture objects
     *
     * @var array
     */
    protected $fixtures;

    public function setUp()
    {
        $this->fixtures = $this->loadFixtureFiles(array(
            '@SomeBundle/DataFixtures/ORM/baseline.yml',
            '@SomeBundle/DataFixtures/ORM/users.yml'
        ));
    }

    public function testSomething()
    {

    }
}
```

**Comment by theofidry** [comment]
Ah no did check that :/ Will add it to my todo list of the weekend.

**Comment by theofidry** [comment]
OK here's how you should do it:

```php
<?php

use Doctrine\ORM\EntityManagerInterface;
use Hautelook\AliceBundle\Alice\DataFixtures\Loader;
use Nelmio\Alice\Persister\Doctrine as DoctrinePersister;

class DummyTest extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase
{
    public function setUp()
    {
        static::bootKernel();

        /* @var Loader $fixturesLoader */
        $fixturesLoader = static::$kernel->getContainer()->get('hautelook_alice.alice.fixtures.loader');
        /* @var EntityManagerInterface $entityManager */
        $entityManager = static::$kernel->getContainer()->get('doctrine.orm.entity_manager');

        $fixturesLoader->load(new DoctrinePersister($entityManager), [
           // ... fixtures files
        ]);
    }
}
```

Key points:

* You must boot your kernel first to be able to get services from the container
* you must use the `'hautelook_alice.alice.fixtures.loader'` service (`Hautelook\AliceBundle\Alice\DataFixtures\Loader`)
* You must get your persister (an `ObjectManager`, be it from Doctrine ORM, ODM...)

**Comment by johnmadrak** [comment]
We wanted to load fixtures from this bundle in our tests and since it seems many others have been trying to do it as well, I wanted to share our method:

```
        $container
            ->get('hautelook_alice.doctrine.executor.fixtures_executor')
            ->execute(
                    $entityManager,
                    $container->get('hautelook_alice.doctrine.orm.loader_generator')->generate($container->get('hautelook_alice.fixtures.loader'), $container->get('hautelook_alice.alice.fixtures.loader'), $application->getKernel()->getBundles(), 'test'),
                    $container->get('hautelook_alice.doctrine.orm.fixtures_finder')->resolveFixtures($application->getKernel(), $this->getFixturesToLoad()),
                    false, //If true, data will not be purged
                    function ($message) { }, //Can be used for logging, if needed
                    true); //If true, truncates instead of deleting
```

Where ```getFixturesToLoad()``` returns an array of fixtures to load. This also supports ```@BundleName``` notation.

**Comment by PWalkow** [comment]
I've struggled with exact same problem. Your @johnmadrak seem very complicated but at least it works. Also these 'getFixturesToLoad' has to specify all files that you need to load per test so it hurts flexibility and not so clear about dependencies like in standard doctrine fixtures by 'DependentFixtureInterface' where you don't have to specify all files.

**Comment by theofidry** [comment]
@PWalkow you shouldn't rely on `DependentFixtureInterface`. It's a DoctrineFixturesBundle thing, which is supported in 1.x but is deprecated.

If you only have regular files, https://github.com/hautelook/AliceBundle/issues/153#issuecomment-186655721 works well enough. If you want a bit more of flexibility and resolve files bath, you have `hautelook_alice.doctrine.orm.fixtures_finder` for example to handle that.

**Comment by theofidry** [comment]
https://github.com/hautelook/AliceBundle/issues/153#issuecomment-148926549 should definitely work (we do it in the tests), there's also a mention regarding how to run commands from a controller or somewhere else: http://symfony.com/doc/current/console/command_in_controller.html
