### ISSUE TITLE
Non-existent service "doctrine"

### ISSUE THREAD

**Issue by PawelJi** [hautelook/AliceBundle#156]
Symfony version 2.7.5

Followed by install instruction, after bundle enable I get terminal error for any command:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]           
  The service "hautelook_alice.doctrine.command.deprecated_load_command" has a depend  
  ency on a non-existent service "doctrine".   

Used for mongoDB.

**Comment by theofidry** [comment]
Indeed if you're using mongoDB you have DoctrineODM installed an no DoctrineORM right? That being said it's really weird as if the service `doctrine` does not exist, the commands for DoctrineORM should not be registered. Could you please print me the result of `php app/console debug:container | grep hautelook`?

**Comment by PawelJi** [comment]
Unfortunately, any use of app/console with included this bundle ends with above exeception thrown. DoctrineODM is used as DoctrineMongoDBBundle does it.

**Comment by theofidry** [comment]
Very strange as it is working for me. Could you show me which Doctrine bundles are registered in your `AppKernel.php` and the doctrine packages installed in your `composer.json`? Of course if you can share your app it would be easier.

**Comment by PawelJi** [comment]
$bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new FOS\UserBundle\FOSUserBundle(),
            new Knp\Bundle\PaginatorBundle\KnpPaginatorBundle(),
            new Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle(),
            new Gsup\ForumBundle\GsupForumBundle(),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle()
        );

        if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();
            $bundles[] = new Liip\FunctionalTestBundle\LiipFunctionalTestBundle();
            $bundles[] = new Hautelook\AliceBundle\HautelookAliceBundle();
        }

"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "symfony/phpunit-bridge": "~2.7.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "doctrine/mongodb-odm": "1.0.*@dev",
        "doctrine/mongodb-odm-bundle": "3.0.*@dev",
        "knplabs/knp-paginator-bundle": "~2.4",
        "mopa/bootstrap-bundle": "v3.0.0-rc1",
        "twbs/bootstrap-sass": "~3.3.0",
        "knplabs/knp-paginator-bundle": "dev-master",
        "knplabs/knp-menu-bundle": "dev-master",
        "vich/uploader-bundle": "*",
        "liip/imagine-bundle": "*",
        "michelf/php-markdown": "*",
        "league/html-to-markdown": "~4.0",
        "components/angular.js": "*",
        "doctrine/doctrine-fixtures-bundle": "^2.2",
        "stof/doctrine-extensions-bundle":      "*"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "liip/functional-test-bundle": "^1.2",
        "hautelook/alice-bundle": "^1.0"
    },

**Comment by theofidry** [comment]
Looks like you have `DoctrineBundle` installed too. Is this one properly configured in `config.yml`?

**Comment by PawelJi** [comment]
You are right. I do not use doctrine orm(doctrine/mongodb-odm instead), so after  that bundle has been disable, Alice starts to work. 

Thanks.
