### ISSUE TITLE
Integrating LafourchetteFixturesBundle

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#157]
see lafourchette/FixturesBundle#11

**Comment by Soullivaneuh** [comment]
What do you mean by "integrating"?

**Comment by theofidry** [comment]
I mean to port the functionnalities we're missing from their bundle to ours.

**Comment by Soullivaneuh** [comment]
I see. Would be great to update this ticket with a todo list. ;-)

**Comment by theofidry** [comment]
Well, did really find the time to take a good look at LafourchetteFixturesBundle to check the missing features actually.

**Comment by vincentchalamon** [comment]
LaFourchetteFixturesBundle is now abandoned. We now use @theofidry KnpLabsFriendlyContexts for managing our test fixtures for Behat, and HautelookAliceBundle for managing out dev fixtures.

**Comment by theofidry** [comment]
Yep, but isn't there something worth integrating still @vincentchalamon? As you used the 3 you're in a better position to tell :)

**Comment by vincentchalamon** [comment]
I think only a few things were good in LaFourchetteFixturesBundle:
- it allowed us to group our fixtures (but this was only useful for our tests, and finally KnpLabsFriendlyContexts is sooooo much better for this need)
- it allowed to set objects ids (which is very useful for our cross-database continuous migration process)

By the time, this bundle became complicated, not really documented, only 1 person was able to maintain it and it was one more fixtures bundle in this world… And HautelookAliceBundle replaced it for our dev fixtures :)

I may recommend only the last point (setting objects ids), but it's specific and can be integrated easily directly in the main project through events for example.

**Comment by theofidry** [comment]
>I may recommend only the last point (setting objects ids), but it's specific and can be integrated easily directly in the main project through events for example.

@vincentchalamon can you elaborate on this point? Sorry it's been a while and I can't figure out what you are referring to from the conversion/LaFouchetteBundle.

**Comment by vincentchalamon** [comment]
I think you can forget it, cause using `purge-with-truncate` and organizing its fixtures could do the same
