### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by bigfoot90** [hautelook/AliceBundle#159]
You should add ```doctrine/doctrine-fixtures-bundle``` as dependency

```
  [Symfony\Component\Debug\Exception\ClassNotFoundException]                   
  Attempted to load class "ORMExecutor" from namespace "Doctrine\Common\DataF  
  ixtures\Executor".                                                           
  Did you forget a "use" statement for another namespace?                      
```

**Comment by theofidry** [comment]
This doesn't come from `doctrine/doctrine-fixtures-bundle` but from `doctrine/data-fixtures`. This is a [suggested dependency](https://github.com/hautelook/AliceBundle/blob/master/composer.json#L42) which is required to use AliceBundle with Doctrine. Unfortunately as the bundle has no hard dependency on Doctrine, this dependency can't be a hard one.
