### ISSUE TITLE
Create schema on run

### ISSUE THREAD

**Issue by crash21** [hautelook/AliceBundle#163]
Hello,

I haven't found any way reading the docs to create the schema on every run. So if you run this on test environment and you have an sql lite db you should run every time before fixtures:

doctrine:schema:create --env=test
And then
hautelook_alice:doctrine:fixtures:load --env=test 

Is that true or there is a way everytime I run hautelook_alice:doctrine:fixtures:load --env=test to automatically create the schema?

Thanks

**Comment by Soullivaneuh** [comment]
Doctrine schema management and fixtures loading are two separated processes.

So yes, you have to create the schema before loading the fixtures.

**Comment by theofidry** [comment]
>there is a way everytime I run hautelook_alice:doctrine:fixtures:load --env=test to automatically create the schema?

At the moment it is down manually as explained @Soullivaneuh it is two different processes. You can reload your fixtures without changing the schema at all. Creating the schema is your ORM work, loading the data is AliceBundle work.
