### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by adrienbrault** [hautelook/AliceBundle#165]
Hey,

The build is failing

**Comment by theofidry** [comment]
Just seen it. Quite strange but I don't really have the time to look at it today maybe some this weekend, @Soullivaneuh will you have some time to look into it?

**Comment by Soullivaneuh** [comment]
Don't really now but seems to be a BC break change on doctrine phpcr odm.

**Comment by theofidry** [comment]
Indeed: https://travis-ci.org/hautelook/AliceBundle/builds/92290445

**Comment by theofidry** [comment]
The problem has been solved by now right?

**Comment by Soullivaneuh** [comment]
Seems to.
