### ISSUE TITLE
Cannot install to Symfony 3

### ISSUE THREAD

**Issue by luchaninov** [hautelook/AliceBundle#168]
I've added to composer.json `"hautelook/alice-bundle": "dev-master",`, but it cannot install because it requires  `nelmio/alice ~2.1` and it cannot work with Symfony 3.

Composer install log
```
  Problem 1
    - Installation request for hautelook/alice-bundle dev-master -> satisfiable by hautelook/alice-bundle[dev-master].
    - hautelook/alice-bundle dev-master requires nelmio/alice ~2.1 -> no matching package found.
```

Please change requirements in your dev-master to `nelmio/alice dev-master` - it supports Symfony 3.

**Comment by theofidry** [comment]
Yes this bundle is not compatible yet with Symfony3. Sadly I have no time at the moment, maybe this weekend, but PR are welcomed. There should not be much to do to ensure the compatibility actually. Maybe @Soullivaneuh has more time?^^

**Comment by Soullivaneuh** [comment]
> Please change requirements in your dev-master to nelmio/alice dev-master - it supports Symfony 3.

Changing nelmio/alice to dev-master is not up to us. You can force requirement on your composer.json, or add a `conflicts` key.

> Yes this bundle is not compatible yet with Symfony3.

What is missing?

**Comment by theofidry** [comment]
Note sure, let's find out: https://github.com/hautelook/AliceBundle/pull/169/files

**Comment by Soullivaneuh** [comment]
Found two BC break on `LoadDataFixturesCommand` and `AbstractLoader`. Will take a look.

**Comment by Soullivaneuh** [comment]
`AbstractLoader` is already fixed.

**Comment by Soullivaneuh** [comment]
For `LoadDataFixturesCommand`, this is more complicated because this class extends `ContainerAware` that will be removed in SF 3.0. The solution is to use trait, but we will drop php 5.3 support.

**Comment by theofidry** [comment]
Not sure of what you mean `LoadDataFixturesCommand` extends `Command` rather

**Comment by Soullivaneuh** [comment]
Well, I say the inverse of what I was thinking. `AbstractLoader` is problematic, not `LoadDataFixturesCommand`.

Will submit a PR right now. :+1:

**Comment by luchaninov** [comment]
For a moment I've made a fork and put in composer.json this forked repository

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/luchaninov/AliceBundle"
        }
    ],
```

I've changed only one line - https://github.com/luchaninov/AliceBundle/commit/2a8883d5f689d1dd7cc274c9f6b2c35e94f2e021

This may be not good solution but works for me - I've tested, my fixtures load good and I can use Symfony 3.0.

**Comment by Soullivaneuh** [comment]
I insist, you have to put this require on your project `composer.json` file.

This fork works, but this is a painless way.

**Comment by Soullivaneuh** [comment]
Example:

```json
{
    "name": "my/project",
    "require": {
        "php": ">=5.4.0",
        "hautelook/alice-bundle": "~2.1"
    },
    "conflict": {
        "nelmio/alice": "<=2.1.1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

With this, `nelmio/alice` will be automaticaly updated to dev-master until a new stable release is coming.

**Comment by theofidry** [comment]
By the way `nelmio/alice` just release the [2.1.2](https://github.com/nelmio/alice/releases/tag/2.1.2) ;)

**Comment by Soullivaneuh** [comment]
BTW, 2.1.2 is out: https://github.com/nelmio/alice/releases/tag/2.1.2

So you should not have this problem anymore.

Closing.

**Comment by luchaninov** [comment]
```
    "conflict": {
        "nelmio/alice": "<=2.1.1"
    },
```
works great. Thanks!
