### ISSUE TITLE
Allow configuring fixture location

### ISSUE THREAD

**Issue by elnur** [hautelook/AliceBundle#180]
A lot of Symfony applications don't use bundles. Without the ability to specify a custom location of fixture files, this bundle is useless in the no-bundles setup.

**Comment by theofidry** [comment]
Well, I wouldn't say that *a lot* Symfony applications are not using bundles, but there is at least some and making this configuration would be a good feature. This is in progress, see #71, but unfortunately I couldn't find the time to finish it, maybe at the end of the year. Any help on that is welcomed :)

**Comment by elnur** [comment]
I solved the problem locally by overriding the `Hautelook\AliceBundle\Doctrine\Finder\FixturesFinder` class in a compiler pass with this code:

```php
<?php
namespace App\Misc;

use Hautelook\AliceBundle\Doctrine\Finder\FixturesFinder as BaseFixturesFinder;

class FixturesFinder extends BaseFixturesFinder
{
    /**
     * @var string
     */
    private $rootDir;

    /**
     * @param string $rootDir
     */
    public function setRootDir($rootDir)
    {
        $this->rootDir = $rootDir;
    }

    protected function getLoadersPaths(array $bundles, $environment)
    {
        return [$this->rootDir.'/DataFixtures/ORM'];
    }
}
```

```php
<?php
namespace App\Misc;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class OverrideServiceCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('hautelook_alice.doctrine.orm.fixtures_finder');
        $definition->setClass(FixturesFinder::class);
        $definition->addMethodCall('setRootDir', [$container->getParameter('kernel.root_dir')]);
    }
}
```

It was pretty easy to do. I'd be even easier to do if you didn't hardcode the class used for `hautelook_alice.doctrine.orm.fixtures_finder` so that I could override it with a parameter.

I'm short on time myself. Otherwise I'd help with the bundle. :wink: I might one day though.

**Comment by theofidry** [comment]
Ha your solution is good enough for a temporary solution :)

Yeah I'm not a big fan of classes as parameters, but you have the `FixturesFinderInterface` so you can just roll your own Finder and override the finder service completely (instead of changing the classname via a parameter).

**Comment by elnur** [comment]
Using parameters for classnames instead of hardcoding them is a very common and idiomatic approach for reusable bundles. :wink:

**Comment by theofidry** [comment]
It used to be considered as a best practice, but it often resulted with tons of parameters never used for most people and needlessly polluting your parameter bag. It's arguable, but IMO for such specific use cases you're as good to declare your own service to override the bundle one instead of just trying to change the bundle service classname. Besides, it often hides the real problem. Here for example, the configuration path should be configurable, and it should be made so instead of providing a more hacky way to solve that.

But well in the end it's more a matter of taste ;)

**Comment by theofidry** [comment]
Little update on the issue, a easy temporary solution besides yours is to override the service used:

```xml
<service id="hautelook_alice.doctrine.orm.fixtures_finder"
                 class="Hautelook\AliceBundle\Doctrine\Finder\FixturesFinder">
            <argument type="string">DataFixtures/ORM</argument>
            <call method="setContainer">
                <argument type="service" id="service_container" />
            </call>
        </service>
```

I don't have much time to continue to work on 1.x, there was https://github.com/hautelook/AliceBundle/pull/71 but I could not finish it.

2.x will support it.

**Comment by theofidry** [comment]
The support has been added to 2.x :)

**Comment by elnur** [comment]
Cool. Thanks. 🙂
