### ISSUE TITLE
How to set name from array using custom provider?

### ISSUE THREAD

**Issue by reypm** [hautelook/AliceBundle#181]
I want to create three unique (name is unique) carrier items and I have this fixture definition:

    PlatformBundle\Entity\Carrier:
        carrier{1..3}:
            name: <carrierName()>
            description: <text(150)>
            active: <boolean(31)>
            createdAt: <dateTimeThisYear()>
            updatedAt: <dateTimeThisYear()>

I have made this custom provider (proper register under services as explained in docs here):

    class CarrierNameProvider
    {
        public static function carrierName()
        {
            $names = [
                'Movistar',
                'Digitel',
                'Movilnet'
            ];
    
            return $names;
        }
    }

But any time I run the fixtures I got this error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Notice: Array to string conversion

What I am doing wrong here? What is the right way to achieve this?

**UPDATE:**

I have tried an alternative way in another fixtures as shown below but can't get it to work either:

    PlatformBundle\Entity\IdentifierType:
        identifier_type{Loterías,Mamis,Psiquico Chat,Videos,Por defecto,Amistad,Variedades,Psiquico SMS,Psiquico SMS Automático,Adulto SMS,Deportes}:
            name: <current()>
            description: <text(150)>
            active: <boolean(31)>
            process_type_id: @process_type*
            createdAt: <dateTimeThisYear()>
            updatedAt: <dateTimeThisYear()>

In this case this is the error:

> [Doctrine\DBAL\Exception\UniqueConstraintViolationException]
  An exception occurred while executing 'INSERT INTO cm_identifier_type (name, description, created_at, updated_at, active, process_type_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["Videos", "Molestias nemo officiis veritatis
  aut ad. Ipsa et quia voluptas sit reiciendis quam. At qui aperiam veritatis eius harum.", "2015-02-08 11:43:40", "2015-05-06 18:53:25", 1, 1]:
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'UNIQ_3555570A8D345646'

**Comment by theofidry** [comment]
This is because `$names` is an array, and what you are doing is assigning a `string`, hence the error:

```
[Symfony\Component\Debug\Exception\ContextErrorException]
Notice: Array to string conversion
```

I would recommend you using (works only for PHP 5.6+):

```php
class CarrierNameProvider
{
    public static NAMES = [
        'Movistar',
        'Digitel',
        'Movilnet',
    ];

    public static function carrierName()
    {
        return $names[mt_rand(0,2)];
    }
}
```

**Comment by reypm** [comment]
@theofidry you mean this piece of code:

```
class CarrierNameProvider {
	public static $NAMES = [
		'Movistar',
		'Digitel',
		'Movilnet'
	];

	public static function carrierName() {
		return CarrierNameProvider::$NAMES[ mt_rand( 0, 2 ) ];
	}
}
```

phpStorm mark yours as incorrect

**Comment by theofidry** [comment]
Sorry fix the comment. Also make sure your PHP version is up to date
