### ISSUE TITLE
Could we tag a 1.1.1 - Symfony 3 support needs it

### ISSUE THREAD

**Issue by weaverryan** [hautelook/AliceBundle#186]
Hey @theofidry!

It looks like you already have Symfony 3 support, but there hasn't been a tag yet. The commits on master since the last tag are *very* minor, so I'm hoping you can create a 1.1.1 tag. I'm hoping to use the bundle in a KnpU tutorial very soon - but I just hit the 3.0 incompat.

Thanks!

**Comment by theofidry** [comment]
Hi @weaverryan. I cant' remember where things were left at, had busy times lately ~. Gonna check that today :)

**Comment by weaverryan** [comment]
Awesome, thanks!

**Comment by theofidry** [comment]
[v1.1.1](https://github.com/hautelook/AliceBundle/releases/tag/v1.1.1) released. If there is any issue let me know!
