### ISSUE TITLE
Q: It's possible to access current iteration value starting on zero? [migrated]

### ISSUE THREAD

**Issue by reypm** [hautelook/AliceBundle#192]
@theofidry coming from this [issue][1] on Alice I will continue the discussion here. I have check your solution but still *random* and that's not the behavior I need or I am looking for. Take a look at the code below:

    public function load(ObjectManager $manager)
    {
        $defaults = array(
            'UNKNOW', 'VIVO', 'CLARO', 'TELEMIG', 'OI', 'TIM', 'CTBC', 
            'SERCOMTEL', 'BRT', 'TELCEL', 'NEXTEL', 'MOBILESYS', 'MOVISTAR AR'
        );

        $faker = new CustomFaker();

        foreach ($defaults as $key => $value) {
            $carrier = new Carrier();
            $carrier->setName($value);
            $carrier->setCarrierId($key);
            $carrier->setDescription($faker->getRandomDescription());

            $this->addReference('carrier-'.$key, $carrier);
            $manager->persist($carrier);
        }

        $manager->flush();
    }

This is how I did using only Doctrine Fixtures and I am trying to do the same using your bundle that's why your previous solution will not work for me. The big idea is pick each element on the big array `NAMES` from your example and add each one also note I need the position on the array because it will be set as `carrierId`. Having that info would you recommend me another solution?

Thx

 [1]: https://github.com/nelmio/alice/issues/310

**Comment by theofidry** [comment]
Maybe you could try:

```yaml
PlatformAdminBundle\Entity\Carrier:
    carrier{1..X}:
        name: <carrierName(current())>
```

with:

```php
class CarrierProvider {
  private $names = [
    'val1',
    'val2',
    '...',
  ];

  public function carrierName($index) {
    return $this->names[$index];
  }
}
```

although this is rather fragile. I'm not sure of the syntax `<carrierName(current())>` so needs to be checked. Otherwise you could keep your old loader, you just need to make it return your collection of objects without persisting them if I remember right.

**Comment by reypm** [comment]
I have checked and I got this error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Warning: current() expects exactly 1 parameter, 0 given

As for your second suggestion I am not sure what are you trying to tell me here

**Comment by theofidry** [comment]
Oh, that's an unexpected error...

For the second suggestion, if I remember right, DoctrineFixtures loaders can still be used (they are loaded as if you were using DoctrineFixturesBundle).

**Comment by theofidry** [comment]
That could be easily checked by doing a `dump()` in your loader method.

**Comment by reypm** [comment]
@theofidry you mean something like this?

    public function load(ObjectManager $manager)
    {
        ...
        $faker = new CustomFaker();

        foreach ($defaults as $key => $value) {
            $carrier = new Carrier();
            $carrier->setName($value);
            $carrier->setCarrierId($key);
            $carrier->setDescription($faker->getRandomDescription());

            $this->addReference('carrier-'.$key, $carrier);
        }

	    dump($manager);
    }

Return the `$manager` and then persist them as follow? 

    // optional persistence
    $persister = new \Nelmio\Alice\Persister\Doctrine($manager);
    $persister->persist(); // => what to persist here?

**Comment by theofidry** [comment]
err no I just mean to keep your old dataloader as it is :)

**Comment by reypm** [comment]
Lol, sorry I am not following you, *keep the dataloader as it is* means 

- keep using Doctrine Fixtures rather than your bundle?
- keep the fixture as I have on the first post where I ask for the iteration value?

**Comment by theofidry** [comment]
I'm saying the data loader you were using for DoctrineFixturesBundle should be compatible with this Bundle :)

**Comment by reypm** [comment]
Ohhhh ok I think you are talking about [this][1], I am right? Using this I need to take care of the order of each fixture, I am right?

 [1]: https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/advanced-usage.md#using-data-loaders

**Comment by theofidry** [comment]
Nope, talking about [that](https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/doctrine-fixtures-bundle.md)

**Comment by reypm** [comment]
Ok, I will keep this open while I am doing my test and if all is good all I will close as fixed, thank you for your support

**Comment by reypm** [comment]
I am have a problem here since apparently the Doctrine Fixtures are not included when I run the command which is causing a second issue describe below. Take a look to the directory structure:

```
src/PlatformAdminBundle/DataFixtures/ORM/
├── Alias.yml
├── Category.yml
├── Command.yml
├── Group.yml
├── IdentifierType.yml
├── LoadCarrier.php
├── LoadOperator.php
├── Msisdn.yml
├── ProcessType.yml
└── User.yml

```

`LoadCarrier.php` and `LoadOperator.php` are both implementing `Doctrine\Common\DataFixtures\FixtureInterface` meaning:

    class LoadOperator extends AbstractFixture implements FixtureInterface { ... }

When I run the command: ` hautelook_alice:doctrine:fixtures:load` this is the output at console:

```
Careful, database will be purged. Do you want to continue y/N ?y
  > fixtures found:
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Msisdn.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Command.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/IdentifierType.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Group.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/User.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Alias.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/ProcessType.yml
      - /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Category.yml
  > purging database
```

As you can see the `*.php` are not included which case this second issue:

  [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]
  Loading files limit of 5 reached. Could not load the following files:
  /var/www/html/platform-cm/src/PlatformAdminBundle/DataFixtures/ORM/Msisdn.yml:
   - Instance mask "operator*" did not match any existing instance, make sure the object is created after its references

I am missing something?

**Comment by theofidry** [comment]
Err can't remember how much DoctrineFixturesBundle is integrated, gonna look into that sorry for the inconvenience :(

**Comment by theofidry** [comment]
No indeed this won't work at all, the `load()` function of Doctrine loaders is completely ignored so for such an edge case you must stick to `DoctrineFixturesBundle`. That being said, if you need it *only* for that then you can just keep only this loader and keep using AliceBundle for the rest of it.

**Comment by reypm** [comment]
I am not sure what are you telling me :-| you mean execute a command for run Alice fixtures and a second one for Doctrine fixtures? That's?

**Comment by theofidry** [comment]
>you mean execute a command for run Alice fixtures and a second one for Doctrine fixtures?

yeah :/ The fact that you depend on the order of the names 'UNKNOW', 'VIVO', 'CLARO' and so makes it too much an edge case sadly.

**Comment by reypm** [comment]
@theofidry can I access references from Doctrine Fixtures Bundle in your bundle? I mean I will run first the Doctrines fixtures and then Hautelook ones but I need to access some references from Doctrine in Hautelook fixtures, can I do that?

**Comment by theofidry** [comment]
Nope.

To me from what you've said in this issue you have two solutions:

1. Keep it as it is and rely to DoctrineFixturesBundle
2. Accept some changes (ex here not depending on the order of the names 'UNKNOW', 'VIVO', 'CLARO', etc.)

It may be a bit weird but this bundle (v1) provides an easy upgrade from DoctrineFixturesBundle, not a full BC. Your current way of doing things right now is very very specific to DoctrineFixturesBundle. Hence sticking with it (choice 1.), or change a bit for the upgrade (2).

Sorry of not being able to help more than that :/

**Comment by reypm** [comment]
No problem, you help me and that's great!
