### ISSUE TITLE
Get generated phone number value before persist

### ISSUE THREAD

**Issue by reypm** [hautelook/AliceBundle#193]
This is another edge case where I need some advice. Take a look to the fixture below:

```
PlatformAdminBundle\Entity\Msisdn:
    msisdn{1..500}:
        msisdn: <phoneNumber()>
        operator: @operator*
        blocked: <boolean(35)>
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>
```

Is there any chance to know and/or catch the `phoneNumber()` generated? I need to know the prefix because `operator` depends on its. So @theofidry any idea from your side is more than welcome.

**Comment by reypm** [comment]
@theofidry any advice around this?

**Comment by theofidry** [comment]
Yep, you can use [alice variables](https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#variables). So in your case you can use `$msisdn`:)

**Comment by theofidry** [comment]
Did that solve your issue @reypm?

**Comment by reypm** [comment]
@theofidry no, not yet I don't think this is what I am looking for since I need to perform a few actions on that generated number, any other ideas?

**Comment by theofidry** [comment]
What kind of actions? You could have a faker provider to do those operations no?

**Comment by reypm** [comment]
@theofidry this set of fixtures are mean to be use for generate fake data for application on Venezuela market so here is the thing. In Venezuela are 3 main phone operator: `Movilnet`, `Digitel` and `Movistar`. Movilnet has asigned numbers prefixed by 0416 and 0426 digits, Digitel numbers prefixed by 0412 and Movistar numbers prefixed by 0414 and 0424.

I want - or at least this is what I am trying to do - get the generated number so I can play with it an see what those prefixes are in order to assign the operator more accurate as I can. I don't know if there is any way to achieve this so this is what I am trying to access that value.

**Comment by theofidry** [comment]
So you want to assign the phone operator depending of the phone number is that right?

**Comment by reypm** [comment]
@theofidry yes, exactly, that's right!

**Comment by theofidry** [comment]
So you should be able to create a custom faker provider, which has a function `getMobileProvider($phoneNumber): $phoneNumber`. You then just have to pass it the generated phone number.

As a rule, any processing of a generated variable, anything to pick a random value in a custom list, goes into faker providers.

**Comment by reypm** [comment]
Ok, thanks for your help.
