### ISSUE TITLE
FatalThrowableError on Symfony 3

### ISSUE THREAD

**Issue by vincentchalamon** [hautelook/AliceBundle#196]
When installing this bundle on a Symfony 3 project, it throws me the following error:
>PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to HautelookAliceBundleDoctrineCommandLoadDataFixturesCommand_0000000026fd623a000000001b1de43bfd1d045c229b5d6073aa43c1abccf3da::__construct() must implement interface Doctrine\Common\Persistence\ManagerRegistry, none given, called in /Users/vincent/Sites/tennis/var/cache/dev/appDevDebugProjectContainer.php on line 2023 in /Users/vincent/Sites/tennis/var/cache/dev/appDevDebugProjectContainer.php:7245

Here is part of my composer.json:
```json
"require-dev": {
    "sensio/generator-bundle": "^3.0",
    "symfony/phpunit-bridge": "^2.7",
    ...
    "hautelook/alice-bundle": "^1.2"
},
```

The issue disappears if I comment the declaration of HautelookAliceBundle on AppKernel class.

**Comment by theofidry** [comment]
Hm, that's weird, especially as there is Travis build for that one and they are passing

**Comment by theofidry** [comment]
It's clearly an error coming from the service registration, the bundle should be able to detect (see the [Extension](https://github.com/hautelook/AliceBundle/blob/1.x/src/DependencyInjection/HautelookAliceExtension.php)) which flavour of Doctrine ORM is being used and load the appropriate service file. In your case it looks like it tried to get the service `doctrine` without success... which is weird as if this service doesn't exist the config file shouldn't be loaded.

**Comment by vincentchalamon** [comment]
I'll investigate and once I'll find a solution I'll comment it here :)

**Comment by EddyLane** [comment]
I am also getting this error with Symfony 3.0.2

**Comment by theofidry** [comment]
Does any of you would be able to link a repository where you encounter this issue?

**Comment by vincentchalamon** [comment]
@theofidry I just added in read you on the project where I've this issue

**Comment by theofidry** [comment]
Thanks, will try to check it tonight :)

**Comment by vincentchalamon** [comment]
Ask me if you have any question about it. I think you can just get the error when using any Symfony command (like at the end of a `composer install` for example)

**Comment by EddyLane** [comment]
When I try and get the 'doctrine' service from the container in the HautelookAliceExtension I get `The service definition "doctrine" does not exist.`. I'm not sure if that helps at all; not too hot on how the container is built up.

**Comment by theofidry** [comment]
@EddyLane it helps, although if you can provide a list of your dependencies would be great as well :)

**Comment by EddyLane** [comment]
@theofidry sure thing.

Require:

    "php": ">=7.0.0",
    "symfony/symfony": "~2.8",
    "doctrine/orm": "^2.4.8",
    "doctrine/doctrine-bundle": "~1.4",
    "doctrine/migrations": "@dev",
    "doctrine/doctrine-migrations-bundle": "dev-master@dev",
    "doctrine/doctrine-fixtures-bundle": "dev-master@dev",
    "nelmio/alice": "~2.1",
    "symfony/assetic-bundle": "~2.7",
    "symfony/monolog-bundle": "~2.4",
    "twig/extensions": "1.0.*",
    "sensio/distribution-bundle": "~5.0",
    "sensio/framework-extra-bundle": "~3.0",
    "sensio/generator-bundle": "3.0.*",
    "incenteev/composer-parameter-handler": "~2.0",
    "jms/serializer-bundle": "1.1.*",
    "friendsofsymfony/rest-bundle": "1.7.*",
    "friendsofsymfony/user-bundle": "dev-master",
    "symfony/swiftmailer-bundle": "^2.3",
    "swiftmailer/swiftmailer": "^5.4",
    "ircmaxell/random-lib": "~1.1",
    "ekino/newrelic-bundle": "master-dev",
    "php-amqplib/rabbitmq-bundle": "1.8.*",
    "guzzlehttp/guzzle": "4.*",
    "knplabs/knp-snappy-bundle": "~1.2",
    "aws/aws-sdk-php": "~2.7",
    "simple-bus/symfony-bridge": "^4.1",
    "simple-bus/doctrine-orm-bridge": "^4.0",
    "snc/redis-bundle": "dev-master@dev",
    "predis/predis": "^1.0"

Require dev:

    "behat/symfony2-extension": "2.*",
    "phpunit/phpunit": "4.7.*@dev",
    "phpspec/phpspec": "~2.0",
    "kriswallsmith/buzz": "dev-master",
    "phpmd/phpmd": "@stable",
    "behat/behat": "3.1.0rc2",
    "behat/web-api-extension": "~1.0@dev",
    "hautelook/alice-bundle": "^1.2",
    "doctrine/data-fixtures": "^1.1"

**Comment by theofidry** [comment]
Cheers, I'll come back to you after investigating a little. I can't guarantee a result this week but will do my best :)

**Comment by EddyLane** [comment]
@theofidry No problem. Thanks a lot :)

**Comment by luchaninov** [comment]
I have the same problem and found how to "fix" it.

`vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php:77`

add `return '';` instead of returning of lazyLoad code

```
return <<<EOF
        if (\$lazyLoad) {

            $instantiation new $proxyClass(
                function (&\$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface \$proxy) {
                    \$wrappedInstance = \$this->$methodName(false);

                    \$proxy->setProxyInitializer(null);

                    return true;
                }
            );
        }


EOF;
```

Then remove `var/cache/dev/appDevDebugProjectContainer.php` and everything works.

I understand that it's not real fix but it may give a clue how to fix it properly.

**Comment by luchaninov** [comment]
It is also possible to fix just disabling lazy load in AliceBundle.

For those who need to make thinks work right now you can replace `hautelook/alice-bundle` to `luchaninov/alice-bundle` in `composer.json` and then replace back after this issue is resolved.

**Comment by luchaninov** [comment]
It is also possible to fix just disabling lazy load in AliceBundle.

For those who need to make thinks work right now you can replace `hautelook/alice-bundle` to `luchaninov/alice-bundle` in composer.json and `composer update` and then replace back after this issue is resolved.

**Comment by vincentchalamon** [comment]
Thanks @luchaninov, indeed removing `lazy` mode can solve it. But personally I don't find it as a definitive solution, but I agree this should work temporary.
We should investigate on *why lazy services throw this exception in Symfony*

**Comment by DZunke** [comment]
i'd fixed this problem by using ```ocramius/proxy-manager``` in version ```1.0.2```, explicit set by my composer.json. it was the last version worked with this bundle. I think there was an update that broke the ProxyManager Birdge with lazy services.

**Comment by theofidry** [comment]
It may be a unintended BC break as well.

**Comment by vincentchalamon** [comment]
@theofidry something also that can help (maybe): LaFourchette project now runs on Symfony 3 with AliceBundle, but we don't have this issue…

**Comment by theofidry** [comment]
Oh, good to know indeed.

**Comment by theofidry** [comment]
I could investigate a bit and the source of the error on HautelookAliceBundle is dead simple: it's the usage of lazy services. Now *why* is this causing an error is another story. I don't have a deep enough understanding of Symfony Container to be able to tell. Also making the command not lazy doesn't solve the issue as the next one coming is:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to HautelookAliceBundleFakerProviderProviderChain_00000000307b29b0000000001bae2a67bda46bc60598b9aac9f38d52539ba3cf::__construct() must be of the type array, object given, called in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php on line 1792 in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php:5112
Stack trace:
#0 /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php(1792): HautelookAliceBundleFakerProviderProviderChain_00000000307b29b0000000001bae2a67bda46bc60598b9aac9f38d52539ba3cf->__construct(Object(Closure))
#1 /Users/Theo/Sites/GitHub/tennis-handisport/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(273): appDevDebugProjectContainer->getHautelookAlice_Faker_ProviderChainService()
#2 /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.p in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php on line 5112

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to HautelookAliceBundleFakerProviderProviderChain_00000000307b29b0000000001bae2a67bda46bc60598b9aac9f38d52539ba3cf::__construct() must be of the type array, object given, called in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php on line 1792 in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php:5112
Stack trace:
#0 /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php(1792): HautelookAliceBundleFakerProviderProviderChain_00000000307b29b0000000001bae2a67bda46bc60598b9aac9f38d52539ba3cf->__construct(Object(Closure))
#1 /Users/Theo/Sites/GitHub/tennis-handisport/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(273): appDevDebugProjectContainer->getHautelookAlice_Faker_ProviderChainService()
#2 /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.p in /Users/Theo/Sites/GitHub/tennis-handisport/var/cache/dev/appDevDebugProjectContainer.php on line 5112
```

After a dump indeed the object got by `ProviderChain::__construct(array $providers)` is:

<img width="698" alt="screen shot 2016-02-27 at 14 47 43" src="https://cloud.githubusercontent.com/assets/5175937/13373485/1c59b0fe-dd61-11e5-83c2-c2432ed32ed0.png">

@vincentchalamon do you have any idea on this?

@dunglas maybe you have also a say on that? Could it be due to a change introduced with the auto-wiring?

**Comment by vincentchalamon** [comment]
FYI, I've just updated `dunglas/api-bundle` to last ~2.0@dev and I don't have this issue anymore (/cc @dunglas @theofidry)

**Comment by theofidry** [comment]
Urg, still weird..., but that just says @dunglas broke everything with his v2 :laughing:

**Comment by vincentchalamon** [comment]
@theofidry maybe…maybe not, cause not sure other reporters use API Platform (even on 2.0).
@DZunke @EddyLane @luchaninov do you use API Platform on your projects that have this issue ?

**Comment by theofidry** [comment]
@vincentchalamon obviously I wasn't serious, but it makes things a bit more annoying as I don't have this issue on a clean install...

**Comment by dunglas** [comment]
ApiBundle v2 doesn't use lazy services anymore. If it can help...

**Comment by theofidry** [comment]
As said before, removing every `lazy: true` in HautelookAliceBundle solves the issue. But I still don't understand why lazy services are suddenly becoming a problem :/

**Comment by vincentchalamon** [comment]
So strange also that updating API Platform to last commits solve the issue…

**Comment by DZunke** [comment]
@vincentchalamon i am using plain symfony 3.0.2. haven't tested if the new symfony version 3.0.3 fix this issue. like i said, it was fixed by setting the package ```ocramius/proxy-manager``` to version ```1.0.2``` which was updated at symfony to 2.0 and fixed some bugs in symfony 3.0.4 with this package.

https://github.com/symfony/symfony/pull/17919

**Comment by harentius** [comment]
I just updated symfony to 3.0.3 (from 3.0.2) and it works in my case...

**Comment by theofidry** [comment]
That's good to hear @harentius, looks like there was a eventually a bug with lazy services then. Will keep the issue open just in case still :)

**Comment by theofidry** [comment]
Closing has an easy fix has been found.
