### ISSUE TITLE
File include should use locateResource

### ISSUE THREAD

**Issue by estahn** [hautelook/AliceBundle#203]
Hi,

Our fixtures grow quite large and we usually split them up and use the include feature. It's quite annoying to use a relative path, it would be great to specify the bundle path.

Example status quo: 

``` yaml
include:
  - "../../Bundle/DataBundle/DataFixtures/ORM/Templates/something.yml"
```

Example expected:

``` yaml
include:
  - "@SomeDataBundle/DataFixtures/ORM/Templates/something.yml"
```

I guess we would need to go through the files and use `static::$kernel->locateResource('@...')` to translate the paths into actual file paths.

Thoughts?

**Comment by theofidry** [comment]
Hi @estahn,

Well I'm a bit lost at *why* you have to use relative paths or `include` statements. You can use [this convention](https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/advanced-usage.md#environment-specific-fixtures) to use an environment base fixtures. If you need something more granular, you can always [DataLoaders](https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/advanced-usage.md#using-data-loaders), in which case you can use the bundle path.

If it's not clear enough, maybe try to give me you're current usage: how are you loading the fixtures and how are you organising fixtures files?

**Comment by estahn** [comment]
@theofidry It doesn't relate to environments, rather to different bundles. Our setup for symfony is `ApiBundle`, `DataBundle`, `StorefrontBundle`, `BackOfficeBundle`, etc. In `DataBundle` we have our `base` fixtures, e.g. `users`, `countries`, etc. Now i want to be able to write fixtures in `ApiBundle` that include those base fixtures.

In regards to the `DataLoaders` i don't see the need and would rather avoid using them. Our `setUp` method looks like:
```php
    public function setUp()
    {
        $this->fixtures = $this->loadFixtureFiles(array(
            '@DataBundle/DataFixtures/ORM/some_controller_test.yml',
        ));
    }
```
Does this clarify it?

**Comment by theofidry** [comment]
Sorry for the late answer @estahn.

The fixture loader indeed takes only care of loading fixture files, loading them, checking for duplicates, resolving paths, are not its job, they are done by the `Finder`s and `Resolver`s.

But you could have your own wrapper to do this more easily for you use case.

**Comment by theofidry** [comment]
@estahn I doubt it will change anything for you right now, but that's something that will be changed for AliceBundle v2 which will rely on alice v3.

**Comment by theofidry** [comment]
This has been integrated to AliceBundle 2.x :)
