### ISSUE TITLE
Embeddable (or none-entity) support when using Doctrine ORM?

### ISSUE THREAD

**Issue by matt-usurp** [hautelook/AliceBundle#215]
I am using a doctrine entity that makes use of embeddable's. Without copying all my code over I am doing something down the lines of the following:

```yaml
RateLimitEmbeddable:
  rate-limit-1:
    schemeType: Unlimited
    customLimit: ~

AccessToken:
  access-token-1:
    token: abcdef
    rateLimit: '@rate-limit-1'
```

Here are my classes:
```php
/** @ORM\Embeddable() */
class RateLimitEmbeddable
{

    /** @ORM\Column(name="scheme_type", type="integer") */
    public $schemeType;

    /** @ORM\Column(name="custom_limit", type="integer", nullable=true) */
    public $customLimit;

}
```

```php
/**
 * @ORM\Entity(repositoryClass="AccessTokenRepository")
 * @ORM\Table(name="`user_access_token`")
 */
class AccessToken implements EntityInterface, AccessTokenInterface
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(name="id", type="integer")
     */
    public $id;

    /** @ORM\Column(name="token", type="string", length=40) */
    public $token;

    /** @ORM\Embedded(columnPrefix="rate_limit_", class="RateLimitEmbeddable") */
    public $rateLimit;

}
```

I expected this to kind of work, I had the sneaky suspicion that it was going to try to persist my embeddable but was hoping that the mapping meta was referenced before attempting so.

```
[Doctrine\ORM\ORMInvalidArgumentException]                                                                                                                                                                        
  The given entity of type 'SomeEmbeddable' (SomeEmbeddable@000000004a2b0daf00000000000f5563) has no identity/no id values set. It cannot be added to the identity map.
```

Now I am totally willing to accept that I have made a boo-boo somewhere and will need to hunt for this. Essentially are `@Embeddable` supported and if so how can I construct none-entities using the YAML without it trying to persist to the database through the manager?

**Comment by vincentchalamon** [comment]
Hi, can you just print us your Doctrine entities `SomeEmbeddable` & `SomeEntity` mapping please? It seems an issue in your mapping

**Comment by matt-usurp** [comment]
Updated the main ticket with the legit examples, its just missing setter/getters.

**Comment by vincentchalamon** [comment]
Currently, AliceBundle does not support `Embeddable` Doctrine objects. In your example, AliceBundle will consider `RateLimitEmbeddable` as an entity, which is not.

Feel free to open a PR on it to detect if object is an entity or an embeddable. /cc @theofidry

**Comment by theofidry** [comment]
I agree it would really be nice to have it. @vincentchalamon do you know if doctrine ignore when you try to persist an embeddable entity or we have to remove embeddables from the list of persisted objects?

**Comment by vincentchalamon** [comment]
I never used embeddable objects, but I guess we have to detect them before merge to prevent `persist` & `flush` them

**Comment by matt-usurp** [comment]
Is it not possible to somehow grab the mapping meta from Doctrine and check if the entities have been declared as `@Entity` before trying to persist them? This then allows you to construct anything using alice, there are a few cases where we have non-embeddable objects as requirements for our entities and this would also fall over.

I will take a look at this but if someone wants to jump on it first then go ahead. I have pretty hectic work days but I will see if I can allocate some time to familiarising myself with the code and opening a PR.

**Comment by vincentchalamon** [comment]
@matt-usurp Currently, we can manage `@Entity` & `@Embeddable` types only. If we find other types in the future, we'll open new related PRs.

**Comment by theofidry** [comment]
@vincentchalamon the loader takes a `PersisterInterface` object, so we could decorate the doctrine one to check for embeddables

**Comment by matt-usurp** [comment]
I went to checkout the code and run the tests just to make sure all was good but composer install fails because of a metric ton of requirements. Was hoping that I wouldn't require the ODM stuff to be installed but looks like I have to install Mongo and all that jazz. I am not installing this all on my machine and wouldn't feel comfortable doing the work and letting Travis run the tests for me. Is there any vagrant setup or something you use to develop this?

**Comment by theofidry** [comment]
@matt-usurp sadly no. I just went with a homestead which includes a bit a everything because I was a bit lazy and didn't really care as long as everything stayed in that box.

That being said, it requires ODM packages, but you don't have to configure it, you can disable those bundles in the AppKernel of the app used for functional tests. Some tests will fail obviously, but it will avoid you to really have to install Mongo.

**Comment by vincentchalamon** [comment]
I don't have a docker box including Mongo, but it could be pretty simple to create a Dockerfile which extends `vincentchalamon/symfony` for example

**Comment by vincentchalamon** [comment]
Something like:
```
FROM vincentchalamon/symfony

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list
RUN apt-get update && apt-get install -y mongodb-org
RUN mkdir -p /data/db

ADD supervisor.conf /etc/supervisor/conf.d/supervisor.conf

EXPOSE 27017
```

And for `supervisor.conf` file:
```conf
[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx
autorestart=false
redirect_stderr=true

[program:php5-fpm]
command=/usr/sbin/php5-fpm
autorestart=false
redirect_stderr=true

[program: mongod]
command=/usr/bin/mongod
autorestart=false
redirect_stderr=true
```

**Comment by theofidry** [comment]
@matt-usurp I've just discovered that so sorry for the late solution. You can use the [local flag](https://github.com/nelmio/alice/blob/9c05a9187135687d28e013423d583dff4be75359/doc/customizing-data-generation.md#reuse-generated-data-using-objects-value) to mark you embedded objects as objects that should not be persisted.

**Comment by matt-usurp** [comment]
So the `(local)` flag does pass the problem although I do not feel this is the accepted solution. It does however lessen the priority on this issue as it can be bypasses. Maybe its as simple in the code then to detect the embeddable entity and simply flag it under the bonnet as local? Either way this has fixed my first issue. I have another but I will be making another ticket for this.

**Comment by theofidry** [comment]
>So the (local) flag does pass the problem although I do not feel this is the accepted solution.

I feel the same. In the end it's just a workaround, but realistically I'm unlikely to work on it and would rather spend my time on the new version of alice instead. That being said that's just me and my personal time, any work on it is warmly welcomed.

**Comment by matt-usurp** [comment]
Is there a new version of Alice? I wouldn't mind getting involved with this. The main repository doesn't really have much activity or branches so I am assuming this is private for now?

**Comment by theofidry** [comment]
I'm working on it :)

- https://github.com/nelmio/alice/issues/329
- https://github.com/nelmio/alice/issues/328
- https://github.com/nelmio/alice/issues/265
- https://gist.github.com/theofidry/2b1de50bb17fc06cb502

And PRs are coming, although for now there is only https://github.com/nelmio/alice/pull/326

It's a bit of a slow process because I need to wait for tshelburne review as v2 has mostly been done by him, but it's progressing. Would be happy to have other people feedback as well!

**Comment by matt-usurp** [comment]
I will give them a read through later. However you may want to go to those issues and remove the reference to this issue as the paper trail will become messy and confusing.

**Comment by theofidry** [comment]
Thinking about it, it may be fixed by updating alice Doctrine bridge. Will check that this weekend

**Comment by theofidry** [comment]
Interesting... https://github.com/nelmio/alice/pull/272

**Comment by matt-usurp** [comment]
Oh nice, didn't see this when I checked the issues. Guess thats because its a PR. So actually updating to `dev-master` might fix my problems for now?

**Comment by theofidry** [comment]
Should be, think I'll do a release at the end of the month

**Comment by theofidry** [comment]
It has been fixed in alice so it should work now :)
