### ISSUE TITLE
Allow to specify fixture directory on the command line (--fixtures=...)

### ISSUE THREAD

**Issue by mpdude** [hautelook/AliceBundle#216]
The `doctrine:fixtures:load` command in `DoctrineFixturesBundle` allows to pass one or several `--fixtures=...` arguments. In that case, only fixtures from this/these directories will be loaded.

It would be great if we could have this for this bundle as well. That switch would perfectly complement the `--bundle=` option we've already got.

**Comment by aledeg** [comment]
I think it's related to #180 and #71

**Comment by mpdude** [comment]
Indeed they are about the same feature, but I am not sure if they aim at making it a command line parameter.

Feel free to close, though.

**Comment by fnash** [comment]
@mpdude same here. I made this #242 , is this what you want?

**Comment by theofidry** [comment]
Closed via https://github.com/hautelook/AliceBundle/pull/257

**Comment by mpdude** [comment]
Awesome, thanks!
