### ISSUE TITLE
Support for different (custom) backends?

### ISSUE THREAD

**Issue by mpdude** [hautelook/AliceBundle#222]
I'd like to use this Bundle to load fixtures for some objects that would special persistence (read: legacy) logic. 

What would be the best approach to solve this? Does this bundle make any provisions for that case?

For example, it would be awesome if I could just implement some interface (say, a `persist($object)` method), tag a service implementation and then this bundle would magically pass in the right objects.

Thoughts?

**Comment by theofidry** [comment]
It's not easily doable in 1.x, but for 2.x the design has been changed and will make use of https://github.com/theofidry/AliceDataFixtures, in which, you can easily create a different implementation of the persister.
