### ISSUE TITLE
Consider adding link to AliceGeneratorBundle in readme

### ISSUE THREAD

**Issue by trappar** [hautelook/AliceBundle#228]
Hey, I just posted the initial release (0.1.0) of a new library called AliceGeneratorBundle which offers the ability to recursively convert existing Doctrine entities into Alice fixtures.

I'd appreciate if you'd have a look and consider adding a link 😄

**Comment by theofidry** [comment]
PR welcomed :) I think it can be added under the "Resources" section.

**Comment by theofidry** [comment]
Closed via #229
