### ISSUE TITLE
Don't use lafourchette/DoctrineBundle anymore

### ISSUE THREAD

**Issue by vincentchalamon** [hautelook/AliceBundle#230]
Doctrine has finally merged final PR about sharding: https://github.com/doctrine/DoctrineBundle/pull/456#issuecomment-227392688

AliceBundle requires it as a dev dependency from a fork of LaFourchette, which can be replaced by the official Doctrine (once it'll be tagged).

**Comment by theofidry** [comment]
Nice one, let's wait for it to be tagged then :)

**Comment by theofidry** [comment]
@vincentchalamon is there an easy way to add the `shard` option to the command only if it exists on doctrine side or to throw a understandable error?

**Comment by vincentchalamon** [comment]
@theofidry Why not a minimum version of Doctrine on composer.json ?

**Comment by theofidry** [comment]
Let's see... To be honest I'm too focused on alice 3.x and AliceBundle 2.x right now to touch 1.x...

**Comment by theofidry** [comment]
Doable... sorry I'm just so out of it with the upgrade I'm not sure I even
want to touch of 1.x anymore :P
