### ISSUE TITLE
Strange "hack" to make the Faker Advanced Provider work

### ISSUE THREAD

**Issue by magnetik** [hautelook/AliceBundle#231]
Hi,

I was trying to use a custom faker provider that was extending the BaseProvider but I faced an issue when trying to use it.

The code is something like this:
```php
<?php

namespace AppBundle\DataFixtures;

use Faker\Provider\Base as BaseProvider;

class NicknameProvider extends BaseProvider
{
    protected static $nameTerm = [
        "3D Waffle",
        // Here comes a big list
        "Woodland Beauty",
    ];

    protected static $nicknameFormats = [
        '{{ nameTerm }}{{ nameTerm }}{{ nameTerm }}',
        '{{ nameTerm }}{{ nameTerm }}',
        '{{ nameTerm }}',
    ];

    public function nickname()
    {
        //It doesn't work without that line
        $this->generator->addProvider($this);

        $format = static::randomElement(static::$nicknameFormats);
        return $this->generator->parse($format);
    }
}
```
And the service was declared as such:
```xml
        <service id="faker.bare_generator" class="Faker\Generator" lazy="true">
            <argument>%hautelook_alice.locale%</argument>

            <factory class="Faker\Factory" method="create" />

            <call method="seed">
                <argument>%hautelook_alice.seed%</argument>
            </call>
        </service>

        <service id="faker.provider.nickname" class="AppBundle\DataFixtures\NicknameProvider">
            <argument type="service" id="faker.bare_generator" />

            <tag name="hautelook_alice.faker.provider" />
        </service>
```

(It obviously looks overcomplicated for such an easy example, but the real pattern I use is more complex.)

What was not documented is the line `$this->generator->addProvider($this);`. Without it I was facing:

```
  [InvalidArgumentException]
  Unknown formatter "nameTerm"
```

When trying to debug, I saw that the list of formater of the generator did not contain my provider.

Is this something missing in the documentation ? a bug in this bundle ? a bug in Faker ?

Thanks

**Comment by theofidry** [comment]
You can see [here](https://github.com/hautelook/AliceBundle/blob/1.x/src/DependencyInjection/Compiler/ProviderCompilerPass.php#L33) that there is a compiler pass to get all the tagged faker provider. As long as you register it there, you should get it. If you want to debug it, I recommend to remove the cache and check the `ProviderChain` class/service.
