### ISSUE TITLE
Use custom providers when running the command

### ISSUE THREAD

**Issue by aledeg** [hautelook/AliceBundle#233]
I wrote a custom provider that is used with Faker. I can use it within Nelmio/Alice with the following syntax

```php
$container = $kernel->getContainer();
$om = $container->get('doctrine')->getManager();

Fixtures::load($files, $om, [
    "providers" => [
        $container->get('faker.provider.custom'),
    ],
]);
```

Is there a way to be able to use the same provider while running the command?

**Note** I am using SF3.1

**Comment by theofidry** [comment]
Sure, you just need to register your provider as a service like explained [here](https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/faker-providers.md).

Also I recommend you not to use `Fixtures` with HautelookAliceBundle, you have services configured for the supported ORMs and configuration for instead :)

**Comment by aledeg** [comment]
Thank you. It works well. :+1:
