### ISSUE TITLE
Defining a Circular Reference between Fixtures.

### ISSUE THREAD

**Issue by thedamnedrhino** [hautelook/AliceBundle#234]
Is there a way two define Circular References between Fixtures (used for bidirectional Associations) ? Right now It falls into an endless loop, going back and forth trying to load the Fixtures referencing each other.  
If this is not possible, what's the best way to handle it?

**Comment by theofidry** [comment]
No, if you have `@user` that gets `@group` and `@group` that gets `@user` you have a circular reference and this is a problem that should be solved in your code. You should have a circular reference even for a bidirectional association.

One way to deal with it, is to make sure that when setting a relation on one side, you are setting the relation to the other *if has not already been set*.

**Comment by thedamnedrhino** [comment]
I figured that out as soon as I posted this. I wasn't thinking of it in terms of the PHP code in place (i.e: the setter getting called), which will cause the association to to be sound at both ends.  
And since the data is persisted, it will work even if the association is not set at both ends as long as it is set on the owning side of the association.

**Comment by theofidry** [comment]
No problem :)
