### ISSUE TITLE
Creating Loaders without implementing `Doctrine\Common\DataFixtures::load()`

### ISSUE THREAD

**Issue by thedamnedrhino** [hautelook/AliceBundle#235]
I tried to create a custom loader by implementing `Hautelook\AliceBundle\Doctrine\DataFixtures::loaderInterface()`; however trying to load the fixtures I get the Error that my loader must implement the abstract method `Doctrine\Common\DataFixtures::load()`. Now the Docs gave me the impression, that it would not be necessary to implement that. Am I doing something wrong or is this the way it's supposed to be?

**Comment by theofidry** [comment]
If you are simply implementing the Doctrine interface, you will have to implement all the methods by yourself. However, you also have the abstract class [DoctrineAbstractLoader](https://github.com/hautelook/AliceBundle/blob/1.x/src/Doctrine/DataFixtures/AbstractLoader.php) which may help you with that.

**Comment by thedamnedrhino** [comment]
It would really be useful if something (e.g: base class, service, trait) was provided to take the filename and handle the Doctrine stuff.

**Comment by theofidry** [comment]
You can use [`hautelook_alice.fixtures.loader`](https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/config/services.xml#L38-L43) or use the command for that :)
