### ISSUE TITLE
Symfony 3 deprecation warnings

### ISSUE THREAD

**Issue by wikimatze** [hautelook/AliceBundle#244]
Hi,

I'm right in the middle of updating my Symfony projects, running the `deprecation-detector.phar` on the master of this projects gives me the following message:

```sh
| 2 | Calling deprecated method Symfony\Component\DependencyInjection\Definition->setFactoryService() | 100  | since version 2.6, to be removed in 3.0. |
| 3 | Calling deprecated method Symfony\Component\DependencyInjection\Definition->setFactoryMethod()  | 101  | since version 2.6, to be removed in 3.0. |
| 1 | Using deprecated interface Symfony\Component\Security\Core\SecurityContextInterface | 39   | since version 2.6, to be removed in 3.0. |
```

Are there any plans to get refactor this code?

Cheers,

Matthias

**Comment by theofidry** [comment]
The new `setFactory()` method is used [whenever possible](https://github.com/hautelook/AliceBundle/blob/1.x/src/DependencyInjection/HautelookAliceExtension.php#L67) and is falling back on the deprecated method.

Also this project is [tested under Symfony 3](https://github.com/hautelook/AliceBundle/blob/1.x/.travis.yml#L31) so don't worry about it :)
