### ISSUE TITLE
Migrate to Alice v3

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#247]
It's time to prepare HautelookAliceBundle 2.x. Nelmio Alice 3.0 beta is coming out this weak, the main features being a much more robust loader, more performant as well. The major change affecting HautelookAliceBundle besides a few changes in the interfaces is that the persistence layer has been dropped. To fill the gap I released https://github.com/theofidry/AliceDataFixtures.

Now given those two libraries, I don't HautelookAliceBundle need to be re-focused, but rather all the tweaks and patched made for alice 2.x and the persistence layer should now be removed, drastically simplifying the bundle.

@Soullivaneuh anything else in mind for HautelookAliceBundle 2.x?

**Comment by alsar** [comment]
Is there a timeline to migrate to v3 of Alice?

**Comment by theofidry** [comment]
I don't think there is much left to do in #249, I still need to add some tests but the gist of it is there. So we can hope for a beta release soon (in the two coming weeks?).

There still a lot to finish before a stable release, in part due to the fact that I have to keep up with four libraries:

- https://github.com/nelmio/alice
- https://github.com/theofidry/AliceDataFixtures
- https://github.com/theofidry/AliceBundleExtension
- https://github.com/hautelook/AliceBundle (this library)

but the beta for HautelookAliceBundle should be close.
