### ISSUE TITLE
Cannot declare class on cache:clear

### ISSUE THREAD

**Issue by toonjanssens** [hautelook/AliceBundle#250]
I get an error when I run the cache:clear command. The fist 2 runs it's ok, the 3th time i get this error. After the error occurred the cache folder is left with 2 subfolders, the local and loca_ 
When I delete both cache folders, the cache:clear command works again for 2 times, after the 3th time the error occurs again. I have no idea what is causing this error.

I'm using
`"symfony/symfony": "^3.1",
"hautelook/alice-bundle": "^1.3",`

This is the error:
`[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                            
  Compile Error: Cannot declare class DoctrineORMEntityManager_0000000000e8316f000000005c3397c63b406f9b848edc253bf0448572cdd00b, because the name is already in use`

**Comment by theofidry** [comment]
Are you sure this is because of AliceBundle?

In any case you can try to rm the content of your cache folder it should help.

**Comment by toonjanssens** [comment]
I'm not sure it only because of AliceBundle, but when I remove the bundle from my project, the error is gone too. Maybe it's in combination with an other bundle... But the AliceBundle is my only place I can start looking for now.

Removing the cache folder does to the trick, but only for 2 times.  The 3th time I always get the error.

**Comment by theofidry** [comment]
Can you provide more details on what version you're using and what packages or ideally share the source code? I can't help much with just the Symfony and AliceBundle version, it works fine on Travis.

**Comment by theofidry** [comment]
To me it looks more like a Doctrine issue than AliceBundle (AliceBundle is using Doctrine behind,  but only to call it and don't do any shady stuff with it). So unless you're able to find more info on it, or provide a 	reproducible, I can't help.

**Comment by toonjanssens** [comment]
Sorry for the late response, At the moment I don't have the time to further investigate the problem. When I've found the issue, I will let you know.
