### ISSUE TITLE
Investigate the new persisting system

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#274]
A big difference between 1.x (which uses alice 2.x) and 2.x (which uses alice 3.x) is that before, the process was:
- load a file
- persist and flush each object
- continue until all the files are loaded

Now the process is:
- load all the files
- persist each object
- flush

How much of an impact it has must be investigated, but there's a possibility that this might cause an issue. If that's the case, this case must be reported and tested.

Actually this new system is a bit equivalent to the `flush_once` option in Alice 2.x, @tshelburne did you have cases where you encountered an issue with it? It's worth noting there's a subtlety though: in Alice 2.x, the flush (with flush once enabled), was done when the file was loaded, for each file loaded. Now it is done only once when all the files are loaded.

**Comment by tshelburne** [comment]
@theofidry It seems like to me we are abandoning these internal steps in favor of a simpler, more focused system. If multiple flushes are needed for a very special use-case workflow, I would suggest the developer write the workflow, not depend on Alice for it. If it means they have a script that loads a set of files, persists those, and then loads a second set, I don't see a problem.

Maybe I'm missing a big set of use-cases here, but I feel like at a fundamental level, persistence is best used (conceptually) when it is only saving the state of existing objects. Multi-step stateful workflows definitely are more complicated than I think we should consider.

**Comment by theofidry** [comment]
So theoretically it should be ok on this side. I however think it might cause big performances issues as before as before the flush was kind of batched, which is no longer the case. Doctrine is not fond of persisting hundreds or thousands of objects in one go :/

**Comment by tshelburne** [comment]
Isn't that just something we could optimize in a bridge? If anything, it seems like having all the data at once gives us more flexibility in solving that problem.

**Comment by theofidry** [comment]
Yeah it's something that should be handled in [AliceDataFixtures](https://github.com/theofidry/AliceDataFixtures) (the persistence bridge). But I'm still not sure on how to proceed, the problem being objects with relationships. Well, to be investigated...

**Comment by tshelburne** [comment]
Why wouldn't they just be initialized with the relationships?

**Comment by theofidry** [comment]
@tshelburne it's more a problem of batch flush, if you have:

```php
$dummy = new Dummy();
$anotherDummy = new AnotherDummy($dummy);

$manager->persist($anotherDummy);
$manager->flush();
```

It will fail because `$dummy` was not persisted (unless you properly configured your cascading maybe? I must say I didn't try it much and I'm not extremely familiar with Doctrine either, but I suspect this could eventually be a problem.

Now I've taken the example with two objects, but on a graph of object for which you don't know the dependencies, this could be problematic (unless doctrine handles it fine)

**Comment by theofidry** [comment]
After a bit more checking this turns out to be ok most of the time. There may be perf issues with very big sets which may require batch flush, but they should be dealt on the user end: too much trouble on the library end. Besides, alice is more meant for small sets of data, or the user better optimise the persistence layer with some in-house stuff as any ORM cries for this kind of job, it's not what it is designed for.
