### ISSUE TITLE
Composer update causes a downgrade of nelmio/alice to 2.1.4

### ISSUE THREAD

**Issue by tifabien** [hautelook/AliceBundle#276]
I recently did a composer update on my Symfony project in order to get the latest version of the Alice bundle. I noticed that the upgrade of Alice bundle has been done but nelmio changed version in a weird way  
```  
- Removing nelmio/alice (2.2.2)
- Installing nelmio/alice (2.1.4)
```
The problem is that when I run my unit test deprecations, the following message appears again 
```
StringUtil::singularify() is deprecated since version 3.1 and will be removed in 4.0. Use Symfony\Component\Inflector\Inflector::singularize instead
```
This deprecation has been fixed in alice/nelmio v2.2.0

It seems related to #236 . Why did you change the require? Did it break something? Is there something to do to fix this?
Thanks!

**Comment by theofidry** [comment]
@tifabien this is not related to #236, as the required dev in #236 did not change (just the notation) except for the PHP bump. As to why your updated your version of alice, you should look into `composer why` :)

**Comment by tifabien** [comment]
You're right seems not related to #236 but more related to #226 as you added  < 2.2.0 in the "nelmio/alice" require which makes impossible the upgrade. The composer why tells
```
# composer why nelmio/alice
hautelook/alice-bundle  v1.4.0  requires  nelmio/alice (^2.1 < 2.2.0)
```

**Comment by theofidry** [comment]
Ah indeed, I did that because there was an issue in the 2.2.0 release and I forgot to update the constraint as I released a new version of alice. Thanks for that should be cool after #277.

**Comment by tifabien** [comment]
Great! Thanks for all your work !

**Comment by tifabien** [comment]
@theofidry It seems you tagged v1.4.1 version in the master branch !

**Comment by theofidry** [comment]
duh

**Comment by theofidry** [comment]
Fixed, soz for that

**Comment by tifabien** [comment]
Much better ! Thanks.
