### ISSUE TITLE
Symfony 3 Install

### ISSUE THREAD

**Issue by raphaelvigee** [hautelook/AliceBundle#279]
Hello !

I'm trying to install the bundle to Symfony 3, but I get this error while accessing a page :

```
Compile Error: Declaration of FidryAliceDataFixturesLoaderMultiPassLoader_00000000623f666200000000714e65f10a92a1247e3e393f1d276a731c9a4e57::load(array $fixturesFiles, array $parameters = Array, array $objects = Array) must be compatible with Fidry\AliceDataFixtures\LoaderInterface::load(array $fixturesFiles, array $parameters = Array, array $objects = Array): array
```

Here is my composer.json : 

```
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": { "Tests\\": "tests/" }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/assetic-bundle": "^2.8",
        "leafo/scssphp": "^0.6.6",
        "doctrine/doctrine-migrations-bundle": "^1.2",
        "braincrafted/bootstrap-bundle": "^2.2"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "theofidry/alice-data-fixtures": "^1.0@dev",
        "nelmio/alice": "^3.0@dev",
        "hautelook/alice-bundle": "^2.0@dev"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "platform": {
            "php": "5.5.9"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.1-dev"
        }
    }
}

```

And the relevant config : 

```
hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm'

fidry_alice_data_fixtures:
    db_drivers:
        doctrine_orm: ~
```

Any clue ?

**Comment by theofidry** [comment]
Hey!

This looks rather weird but let's try this:

- Could you give me you `composer.lock` file instead? While your dep are interesting, seeing which packages are installed might give a lead
- I see you are using the beta version, that's cool! But I think you are missing `doctrine/data-fixtures`
- Which PHP version are you using?
- Did you try to clear your cache? (`rm -rf var/cache/*`, not `bin/console cache:clear`)

Not related but a few comments on your `composer.json`:

- You should not need to require `nelmio/alice`directly (you can it's just a bit redundant)
- You config is not needed either as you are using the default values (although there is nothing wrong with it if you prefer to have them under your eyes)

I'm also in the middle of a new beta release for `theofidry/alice-data-fixtures`. The release is ready but I'm missing https://github.com/wouterj/WouterJEloquentBundle/pull/37 for it, so you might try to update your dependencies again.

**Comment by raphaelvigee** [comment]
Finally I gave up because anyway the generation of the fixtures would have needed access to services, which is much more simple by doing it the old fashion way using Faker and `doctrine/data-fixtures`

Thank you for your quick answer anyway !

**Comment by theofidry** [comment]
Ok, out of curiosity can you describe how you need to access to services to know if it's doable or worth integrating in alice?

**Comment by raphaelvigee** [comment]
I wanted to generate users so I needed the password encoder service.

**Comment by theofidry** [comment]
Isn't it what faker providers are for? You declare a faker provider as a service so you can inject anything in it.

That said if doctrine fixtures is enough for you then it's alright.

**Comment by raphaelvigee** [comment]
Yes sure, but this plus the fact that it wasn't working made me giving up.
Plus I needed some logic inside : 
```
            $isLastSession = false;
            foreach ($sessions as $ks => $session) {
                if($ks == count($sessions) - 1){
                    $isLastSession = true;
                }
                foreach ($session->getExercises() as $k => $e) {
                    if ($isLastSession && $this->f->boolean(75)) continue;
                    $feedback = new CaptainTestSessionExerciseFeedback($session, $e);
                    $feedback->setValue($this->f->numberBetween(1, 30));
                    $manager->persist($feedback);
                    $manager->flush();
                }
            }
```

**Comment by theofidry** [comment]
Haha yes I can understand, although it's a beta so it can still be a bit rough on the edge. 1.x is relatively stable though.

I think this kind of logic can still be done with alice, but if you don't have much fixtures and is easier to manage with regular PHP there is nothing wrong with it. The reason of being of this bundle is to simply make thing easier most of the time (the kind of logic you are showing to me looks extremely specific), more expressive and address some limitations of the unmaintained doctrine fixtures library.

**Comment by raphaelvigee** [comment]
The fixtures are quite tricky to generate, so it would be more reliable doing everything in pure PHP, this specific logic is much more clear like this.

**Comment by vdesdoigts** [comment]
I have the same problem `Compile Error: Declaration of FidryAliceDataFixturesLoaderMultiPassLoader_00000000623f666200000000714e65f10a92a1247e3e393f1d276a731c9a4e57::load(array $fixturesFiles, array $parameters = Array, array $objects = Array) must be compatible with Fidry\AliceDataFixtures\LoaderInterface::load(array $fixturesFiles, array $parameters = Array, array $objects = Array): array` after following https://github.com/theofidry/AliceDataFixtures#installation can you help me ?

**Comment by theofidry** [comment]
@vdesdoigts I would prefer if you open a new issue and give the versions you are using :)

**Comment by wesnick** [comment]
Just for anyone who sees this issue, this is caused by having a version of ocramius/proxy-manager that does not support all the types for the class it is proxying.

PHP5 -> v1
PHP7.0 -> v2.0
PHP7.1-> v2.1
PHP7.2-> v2.2

I was locked at v1, needed v2.1

make sure you use composer upgrade --with-dependencies to ensure that this gets bumped.

**Comment by theofidry** [comment]
good point, @wesnick would you mind opening a PR on AliceDataFixtures to add a composer conflict rule to disallow ProxyManager 1.x?
