### ISSUE TITLE
theofidry/alice-persistence cannot be found

### ISSUE THREAD

**Issue by smilesrg** [hautelook/AliceBundle#280]
```
$ composer require --dev theofidry/alice-persistence

  [InvalidArgumentException]
  Could not find package theofidry/alice-persistence at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

```

**Comment by theofidry** [comment]
Sorry about that, I've updated the doc:

```
composer require --dev hautelook/alice-bundle:^2.0@dev \
  theofidry/alice-data-fixtures:^1.0@dev \
  doctrine/orm-bundle \
  doctrine/orm:^2.5 \
  doctrine/data-fixtures
```

**Comment by smilesrg** [comment]
@theofidry I think
```
  doctrine/orm-bundle \
  doctrine/orm:^2.5 \
```
have to be removed because we need this packages not only in dev env, right?

**Comment by theofidry** [comment]
If you already have them in `require` yes they are superfluous, maybe I should separate it in two composer commands.

I'm also wondering if a meta package for that would work better, it is annoying to have to require 3-5 different packages to make the library work :/
