### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by antonyoneill** [hautelook/AliceBundle#286]
Hey,

I'm hoping to use Alice to drive fixtures in my phpunit tests. I currently have the following packages
```
        "nelmio/alice": "2.2.2",
        "hautelook/alice-bundle": "^1.4"
```
But I'm struggling to see how I can actually load the fixtures as part of the phpunit `setUp` function. We usually use the `\Liip\FunctionalTestBundle\Test\WebTestCase::loadFixtures` method where we have a bunch of php classes that build up the fixtures, but it's heavy handed and I need a quick way of setting up a handful of partial entities.

I wondered if I needed something like the FixturesFinder, but not sure where to start.

Look forward to hearing from you

Cheers

**Comment by theofidry** [comment]
Hi!

A very quick & easy way is to ensure your kernel is booted in your setup, create a console application with the fixture command and trigger it (look for how to execute a console command from a controller or something, it's the same).

As you can guess this is not the most and convenient way to do it. Unfortunately for now the fixture lookup + files resolution + database purge + loading is done in the console command (each bit has its own services, but the orchestrator is the command). So if you want something a bit more performant, you can look it up and do a bit more manual things.

In HautelookAliceBundle 2.x, I made sure not to repeat the same mistake, but I know the upgrade may be painful depending of your level of integration.

**Comment by antonyoneill** [comment]
Awesome, thanks for getting back to me so quickly!

I'll take a look at some of the command services and see if I can find an easyish way to replicate the lifecycle in the setUp method, as running the command isn't really going to be viable with the scope I have for the project.

Just wanted to make sure I wasn't missing something simple.

Have a great day
