### ISSUE TITLE
Handle translations with AliceBundle

### ISSUE THREAD

**Issue by Linkinou** [hautelook/AliceBundle#303]
Hello there and happy new year =)

I was wondering if there is a way to handle translations within my entities with AliceBundle ?
I'm using the @gedmo/Translatable annotation (https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md) to set some field to be translatable.

**Comment by theofidry** [comment]
Hi @Linkinou, happy new year :)

Is there anything preventing you from doing that? Alice just provides you a different way to write your objects, but in the end they are still plain objects.

**Comment by Linkinou** [comment]
Hey @theofidry , thank you for answering.

Well, if I write something like that : 

```YML
APIBundle\Entity\Horse\Gender:
    gender_{1..10}:
        name: <name()>
```

For my entity : 
```PHP
<?php
namespace APIBundle\Entity\Horse;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
/**
 * The gender of a horse
 *
 * @ApiResource
 * @ORM\Entity
 * @ORM\Table(name="horse_gender")
 */
class Gender
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private     $id;
    /**
     * @var string
     *
     * @Gedmo\Translatable
     * @ORM\Column(type="string")
     */
    private     $name;
    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }
    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }
}
```

I can see added rows in my database but all of them have empty name.
And if I remove @Gedmo\Translatable annotation it works well :)

Any ideas ?

**Comment by theofidry** [comment]
>but all of them have empty name

I'm not familiar with how gedmo works, but I guess they are using an event, what you could try is do step by step debugging to see why it's removing the name, maybe it consider it to be invalid?

**Comment by Linkinou** [comment]
Yes I will investigate on that, I don't know exactly how gedmo works aswell but I will look into it.

Meanwhile, I've just found this gist : https://gist.github.com/istvankis/0010cf0e318258146d4f203007aaf1e2

I will give it a try ASAP

**Comment by theofidry** [comment]
That could be a hint yes, alice has pre/post persist processors. But if gedmo works on a doctrine event, this shouldn't be needed.

**Comment by theofidry** [comment]
Closing as this has been solved. If someone stills struggle with it maybe a doc entry could be added.

**Comment by MarcDiaz** [comment]
Hi,

I use Symfony 4, your AliceBundle and the Gedmo\Translatable bundle but the translations are not inserted in the `ext_translations` table when I load my fixtures with `bin/console hautelook:fixtures:load`.

I tried to follow the instructions on this page https://gist.github.com/istvankis/0010cf0e318258146d4f203007aaf1e2 but it's for Symfony 3 (there's `AppBundle` instead of `App`).

@theofidry, can you add a doc entry about the usage of Gedmo\Translatable with the AliceBundle, as you mention it in your previous answer, please?

**Comment by theofidry** [comment]
@MarcDiaz sorry I unfortunately never had to use Gedmo. I can help out if there is a specific question regarding the lifecycle in Alice, but not much for Gedmo internals.

**Comment by pitpit** [comment]
@MarcDiaz I think you could be interested in this almost natively way to make it work with Symfony4, alice and gedmo translatable :
