### ISSUE TITLE
randomHtml() doesn't exist

### ISSUE THREAD

**Issue by Grazulex** [hautelook/AliceBundle#305]
Hello,

I can used a lot of faker provider like imageUrl but when I try randomHTML() I receiv a error that this provider doesn't exists !!??

Thanks

JMS

**Comment by theofidry** [comment]
Hi, did you check that the provider in question is registered? It may not be a default provider

**Comment by theofidry** [comment]
ping @Grazulex

**Comment by theofidry** [comment]
Closing for lack of answer. I'll re-open the issue if you can provide more info regarding the issue.
