### ISSUE TITLE
--append option throws LogicException

### ISSUE THREAD

**Issue by jverdeyen** [hautelook/AliceBundle#306]
In the `DoctrineOrmLoader` class:

```
if ($append && $purgeWithTruncate !== null) {
            throw new \LogicException(
                'Cannot append loaded fixtures and at the same time purge the database. Choose one.'
            );
        }
```

When `$purgeWithTruncate` parameters is passed from the `DoctrineOrmLoadDataFixturesCommand` and is `=== false` at that point. Meaning using only the `--append` option will throw the `LogicException`.

This can be fixed on different location, I think it should be best to do something like this in the Command:

```
$truncate = ($input->getOption('purge-with-truncate') !== false) ? : null;
```

Thanks!

**Comment by shadypierre** [comment]
I have the same issue, any news about it?

**Comment by theofidry** [comment]
yes you can check #308

**Comment by nifr** [comment]
PR #329 tries to fix the same issue.

**Comment by theofidry** [comment]
I saw both but I think the real issue is solved in https://github.com/theofidry/AliceDataFixtures/pull/42 but I need to do a PR on HautelookAliceBundle to see if that's enough

**Comment by theofidry** [comment]
This should be fixed by now :)

**Comment by curry684** [comment]
So, RC1 coming out?   😉

**Comment by theofidry** [comment]
Soon :) I would like a MongoDB support being merged first as it would allow to discuss some cases. Other than that I think we're good
