### ISSUE TITLE
Difference with nelmio/alice bundle not clear

### ISSUE THREAD

**Issue by Kwadz** [hautelook/AliceBundle#310]
Could you explain the difference between `hautelook/AliceBundle` and   `NelmioAliceBundle` which is [stated here](https://github.com/nelmio/alice/blob/master/doc/getting-started.md#framework-integration).

The difference seems not to be clear in the documentation.

**Comment by theofidry** [comment]
Sorry I didn't see your question earlier!

There is a big difference, `NelmioAliceBundle` is just the glue between the library and the framework, namely it exposes a configuration and register services to the Symfony DIC. There is not added feature compared to the library: it's just a dead simple framework integration. The alternative to that bundle is the `NativeLoader` which doesn't use any DIC and for which customization is done by extending methods to refer to services & co.

HautelookAliceBundle on the other hand provides a few features on top of `NelmioAliceBundle` and `FidryAliceDataFixtures` (cf. https://github.com/theofidry/AliceDataFixtures), namely it adds commands to easily load fixtures and use a persistence layer on top of alice.

If you check the code, you'll see that the code in 3.x is relatively simple, it's mostly related to locating fixtures. It used to be more complex in 2.x, but I manager to simply it by providing a better design/API for nelmio/alice and theofidry/AliceDataFixtures.
