### ISSUE TITLE
Sharing objects between fixtures

### ISSUE THREAD

**Issue by Kwadz** [hautelook/AliceBundle#311]
DoctrineFixturesBundle allows [Sharing Objects between Fixtures](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#sharing-objects-between-fixtures).

Is it possible with AliceBundle?

**Comment by theofidry** [comment]
No as you don't need it: just have your objects fined in different fixture files, all the files will be loaded in the right order so there is no problem. You could also have your objects in the same fixture file if you want to actually.
