### ISSUE TITLE
How to manage relations with InheritanceType in Doctrine?

### ISSUE THREAD

**Issue by Kwadz** [hautelook/AliceBundle#312]
I am using entities which use [Class Table Inheritance](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#class-table-inheritance): 

```php
<?php
namespace MyProject\Model;

/**
 * @Entity
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"person" = "Person", "employee" = "Employee"})
 */
class Person
{
    // ...
}

/** @Entity */
class Employee extends Person
{
    // ...
}
```

How to manage with AliceBundle to link an `Employee` entry with a `Person` entry?

**Comment by theofidry** [comment]
If you need an `Employee` instance declare it as `Employee`, if you need a `Person` instance.

AliceBundle, by using alice, simply transform a declaration file into an collection of plain PHP objects, which are later persisted. If you're not sure how you should do things, think how you would do it in plain PHP first. Alice is just a bit of abstraction to write those things more easily.
