### ISSUE TITLE
[Q] fixtures ordering

### ISSUE THREAD

**Issue by versh23** [hautelook/AliceBundle#314]
what is a best way to order fixtures loading ? is it a naming files?

for exampl

```
001.yml
App\Class1:
    b_1:
        name: '123'
    b_2:
        name: '321'


002.yml
App\Class2:
    a_1:
       ref: @b_{1..2}
```

I try to use include, but after load fixtures i have a 4 records of class1

**Comment by theofidry** [comment]
@versh23 you shouldn't worry about the order. Alice tries to load all the files in one pass, then if some could not be loaded (because were missing a fixture which is defined in a file not loaded yet), retries after and continues until either all the files are loaded or a limit in the number of passes is reached.

**Comment by versh23** [comment]
@theofidry yes, there are no errors, but i have a duplicate records instead

**Comment by theofidry** [comment]
Hm indeed this should not be happening, I'll look into it.

**Comment by versh23** [comment]
@theofidry i create a simple bundle to reproduce error.
https://github.com/versh23/alice_test

but now i have a error
  [Nelmio\Alice\Throwable\Exception\FixtureNotFoundException]
  Could not find the fixture "industry_1".

**Comment by theofidry** [comment]
👌

**Comment by Kwadz** [comment]
> or a limit in the number of passes is reached.

How to increase the limit? It seems to be 5 by default:

```
Loading files limit of 5 reached. Could not load the following files:
[…] 
```

**Comment by JeromeGill** [comment]
What cascade settings have you on the entities? We gave up with this bundle for a similar error. It isn't clear how to force flush prior to referencing entities later. Failing to do this causes cascade={"persist"} to result in duplicates.

**Comment by theofidry** [comment]
If the order of the fixtures is really important, you [should implement your own finder](https://github.com/hautelook/AliceBundle/blob/master/src/FixtureLocatorInterface.php) to sort them in the order you want (by decorating the existing one and just manipulate the result).
