### ISSUE TITLE
Install Instructions for 3.0 are quite complex!

### ISSUE THREAD

**Issue by weaverryan** [hautelook/AliceBundle#315]
Hi guys!

One of the benefits of this bundle is how powerful, and how fun it is (once again) to add fixtures. But the install instructions for 3.0 are a little nuts :). I think some of this might just be because all of the libraries aren't released yet... but it still seems like it will ultimately be a lot. I mean:

```
# Ryan: I think this line should not be here: it's a huge edge case to be looking to use this bundle
# with Doctrine, but not have these installed already. And in that edge case, you probably
# know what you are doing :)
# If you are using Symfony standard edition, you can skip this step
composer require doctrine/doctrine-bundle doctrine/orm:^2.5

# Ryan: 4 dependencies? I think nelmio/alice might go away later, but will we still need to
# list 3 dependencies? As a user, I just want to create some YAML files for my fixtures.
# This is an ugly barrier to entry
composer require --dev hautelook/alice-bundle:^2.0@beta \
  nelmio/alice:^3.0@beta \
  theofidry/alice-data-fixtures:^1.0@beta \
  doctrine/data-fixtures
```

The same is true for adding 3 bundles to `registerBundles()`, however I'm less concerned about this, as this will probably be automated when Symfony Flex comes out.

My ideal situation would be to:
1) Run a simple require statement (one library)
2) Create my first YAML file

(again, Flex would eventually take care of registering the bundles, so I didn't include that).

Could we do this perhaps with some sort of a meta package?

**Comment by theofidry** [comment]
haha spot on ;)

You're right it's a lot of deps, but once the stable versions are released, it will become:

```
composer require --dev hautelook/alice-bundle:^2.0 doctrine/data-fixtures
```

which is already way more reasonable to me.

>Could we do this perhaps with some sort of a meta package?

Actually I've been thinking about it for a while now and I think adding a doctrine flavour would be a good idea. For adding the bundles, it might be a bit annoying, but I'm a bit let convinced that it's a good idea to add more magic there.

I've been quite busy lately but I'll have some time to polish a new beta which hopefully will be the last one really soon.

**Comment by weaverryan** [comment]
Ah, that's so much better already! This one line is short enough already (and maybe the `^2.0` would also not be needed?). I'm also not worried about adding the bundles - because it should (in theory) be fixed with with Flex.

Thanks - looking forward to the stable releases!
