### ISSUE TITLE
Create directories for image stubs

### ISSUE THREAD

**Issue by ScreamingDev** [hautelook/AliceBundle#316]
Imagine having this in the fixture:

```
EntityClass:
  foo1:
    image: <image(./tmp/me/user/1/profile/1, 600, 1200, 'business')>
```

Running `hautelook:fixtures:load` would bring up an exception:

    [InvalidArgumentException]                                    
    Cannot write to directory "./tmp/me/user/1/profile/1" 

By now the directories needed to be created by hand
or with some scaffold script only for testing.
Would be great if the alice bundle tries to create those directories.

**Comment by theofidry** [comment]
I have mixed feelings about this. Whilst I agree it would be convenient, it adds undesirable side-effects. Plus, I would actually say it's not something to be done in alice but in Faker rather.

**Comment by sourcerer-mike** [comment]
I had mixed feelings too until I thought "could be an option" like `--mkdir`.
I didn't open this issue in Faker because I thought faker happens more in PHP than the AliceBundle does.
The AliceBundle allows using yml files which are pure configs so it should take care of missing directories.

If Faker handles yml as well and you just forward the exception, then it is a Faker issue - I didn't look that up.

**Comment by theofidry** [comment]
No Faker doesn't handle YAML, but at the end of the day in your example all that alice does is `$faker->image(./tmp/me/user/1/profile/1, 600, 1200, 'business')`, so creating the directory could be done there.

**Comment by sourcerer-mike** [comment]
That would be great!
By now I dunno any other solution (maybe processor) to create directories on demand.

**Comment by theofidry** [comment]
Yes, but that introduces side-effects with a couple of potential problem (file perms for instance). So rather than patching something here which could be annoying to maintain, I would prefer to solve the issue at the root :)

**Comment by theofidry** [comment]
Actually this can easily be fixed userland by using a custom Faker provider decorating the existing one to create the directory when necessary. I don't really think this should be in the core or maybe this could be pushed to Faker :)
