### ISSUE TITLE
Using Doctrine AbstractFixture

### ISSUE THREAD

**Issue by versgui** [hautelook/AliceBundle#320]
Hi,
I'd like to know if it is possible to use [Doctrine AbstractFixture](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#sharing-objects-between-fixtures) like that : 

    namespace DashboardBundle\DataFixtures\ORM;

    use DashboardBundle\Entity\Property;
    use Doctrine\Common\DataFixtures\AbstractFixture;
    use Doctrine\Common\DataFixtures\FixtureInterface;
    use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
    use Doctrine\Common\Persistence\ObjectManager;
    use Symfony\Component\DependencyInjection\ContainerAwareInterface;
    use Symfony\Component\DependencyInjection\ContainerInterface;

    class LoadPropertyData extends AbstractFixture implements FixtureInterface, ContainerAwareInterface, OrderedFixtureInterface
    {
        /** @var  ContainerInterface */
        private $container;

        public function setContainer(ContainerInterface $container = null)
        {
            $this->container = $container;
        }

        public function load(ObjectManager $manager)
        {
            $properties = $this->container->get('dashboard.properties_generator');

            foreach ($properties as $key => $propertyConfig) {
                $property = new Property();
                $property->setName($key);
                $property->setType($propertyConfig);

                $this->addReference('property-' . $key, $property);

                $manager->persist($property);
            }

            $manager->flush();
        }

        public function getOrder()
        {
            return  1;
        }
    }

When I try this, I get this error : 

`
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                    
  Compile Error: Cannot declare class DashboardBundle\DataFixtures\ORM\LoadPropertyData, because the name is already in use
`

The aim is to generate dynamically some fixtures from a config file, and to be able to reference them from other fixtures.

**Comment by theofidry** [comment]
HautelookAliceBundle 1.x provides a partial support for DoctrineFixtures support, cf. https://github.com/hautelook/AliceBundle/blob/1.x/src/Resources/doc/doctrine-fixtures-bundle.md only to ease the upgrade from a dev version to a stable version.

As you can see there, ordered fixtures is not supported, neither does it makes sense to support it. That said, you can use both together, it's just that in that situation, you may not want to use Alice to load those fixtures and let DoctrineFixtures do it.

**Comment by versgui** [comment]
How use both together? It seems that AliceBundle takes precedence on DoctrineFixtures. Did I miss something in config or in my files organization?

**Comment by theofidry** [comment]
>It seems that AliceBundle takes precedence on DoctrineFixtures

There is a bridge between AliceBundle and DoctrineFixtures, to be able to use some features of DoctrineFixtures in AliceBundle (e.g. loading Doctrine fixtures via Alice), but you can actually use them completely separated (i.e. don't use that bridge, and use both AliceBundle & DoctrineFixture commands)
