### ISSUE TITLE
image always return full path

### ISSUE THREAD

**Issue by versh23** [hautelook/AliceBundle#321]
```
AppBundle\Entity\File:
    image_large_{1..30}:
        name: 'large_<current()>'
        path: '/dummy/<image("<{upload_path}>/dummy", 1024, 768, "business", false)>'
```

its return a full path, but i expected only filename

**Comment by versh23** [comment]
`return $fullPath ? $filepath : $filename;`


because $fullpath is string in fzaninotto/faker/src/Faker/Provider/Image.php

**Comment by apetitpa** [comment]
Experiencing same issue on my projet.

**Comment by theofidry** [comment]
Yes, as it stands the last argument of `image()` will be `'false'` not `false`. You need to cast it first
