### ISSUE TITLE
Can I use Fixtures parameters in yaml keys to set number of loops?

### ISSUE THREAD

**Issue by GabLeRoux** [hautelook/AliceBundle#326]
Hi :wave: 
I'd like to use [Fixture parameters as described in the docs](https://github.com/hautelook/AliceBundle/blob/master/doc/advanced-usage.md#fixtures-parameters) :books:  to generate a bunch of users and other things, but I'd like to pass a quantity. For my local tests, I'm generating 100, but in the end, the desired quantity would be 15'000 and I don't want to set it everywhere each time (I have a lot of models to generate).

I created a `app/Resources/fixtures/orm/parameters.yml` that looks something like this:
```yaml
parameters:
    fixture.load_users.users_to_create: 1..100
```

And I'd like to use it this way:

```yaml
Project\Bundle\SomeBundle\Entity\Users:
    some_user_{<{fixture.load_users.users_to_create}>} (extends user_template):
        username: '<username()>'
```

But I get the following error:
```
Template user_template is not defined
- Entity with Id @some_user_<{fixture.load_users.users_to_create}> and Class Project\Bundle  
  \SomeBundle\Entity\Users not found        
```

Note that the `user_template` is defined and it just works when I replace
```yaml
some_user_{<{fixture.load_users.users_to_create}>} (extends user_template):
```
with
```yaml
some_user_{1..100} (extends user_template):
```

Should I use some php instead? Anyone done something like this before?

**Comment by theofidry** [comment]
Nope. It's doable by manually looping to create the desired number of fixtures, but right now at least this is not possible. So you can either go back to PHP templates to achieve what you want, or extend the library to resolve those parameters in the name which is totally doable but does require you to dig a bit in it.
