### ISSUE TITLE
Do not truncate views

### ISSUE THREAD

**Issue by ScreamingDev** [hautelook/AliceBundle#331]
Within my database I have some views and defined them as read-only for Doctrine.
Anyways the `hautelook:fixtures:load` (with or without `--purge-with-truncate`) tries to truncate or delete the views.
This shouldn't happen as views only gather information and can not be truncated. Neither shall they be deleted as your bundle won't bring them up afterwards.

How to exclude this view? 
Will it be built in to check if a table is a view or not?
Why does this bundle even try to remove this table? I didn't mention it in any fixture.

**Comment by theofidry** [comment]
The bundle tries to truncate _all_ the tables known by Doctrine. I'm not sure how to extend it, you'll have to look at how the purger is injected and if is extendable :)

**Comment by sourcerer-mike** [comment]
> I'm not sure how to extend it

The config should be (esp. for views):

```
    <entity name="WalletPerMonth"
            table="wallet_month"
            read-only="true">

...

    </entity>

```

See the "read-only" attribute. Would help if AliceBundle does not delete those tables. Neither truncates them. Both mean to change data so it is the opposite of read-only.

**Comment by sourcerer-mike** [comment]
Sorry. I just saw this:

Code for hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/FixturesExecutor.php:61

```
                $metaData = $manager->getMetadataFactory()->getAllMetadata();

                $excluded = [];
                foreach ($metaData as $classMetadata) {
                    /** @var ClassMetadata $classMetadata */
                    if ($classMetadata->isReadOnly) {
                        $excluded[] = $classMetadata->getTableName();
                    }
                }
```

And then you do:

```
$purger = new ORMPurger($manager, $excluded);
```

First steps for this issue ;)

**Comment by theofidry** [comment]
Closed via https://github.com/theofidry/AliceDataFixtures/commit/9067351141e1105d6bb9c74f0be4f7d6c8b11a00
