### ISSUE TITLE
Collection not populated in Many to Many relationship

### ISSUE THREAD

**Issue by oniric85** [hautelook/AliceBundle#332]
Hi all,
I'm using this bundle to load some fixture files in our integration tests. I'm using this simple approach:

```
$this->fixtures = $fixturesLoader->load(new DoctrinePersister($entityManager), $files);
```
This worked fine until recently when we discovered that when referencing a fixture from those returned by the above method we got

```
$related = $this->fixtures['my_fixture']->getRelatedEntities();
```
The **$related collection is empty** but in the database when we load these fixtures the tables are correctly populated. I don't know the inner workings of this bundle and perhaps I'm missing something obvious.

BTW, I'm using version v1.4.1 of this bundle.

**Comment by theofidry** [comment]
I'm not sure what is causing this exactly, might have to do with the way your entities are configured or a manager that has been cleared somewhere... Could you provide me some details there?

**Comment by oniric85** [comment]
Hi @theofidry, thanks for your interest.

I load the fixtures on each method and I don't explicitly clear the manager myself after loading the fixtures. I have all the fixtures in separated files. The entity classes are in two different bundles but not sure if this can cause issues.

I've built the fixture for the pivot table like this (just an example):

```
My\AppBundle\Entity\UserGroup:
    usergroup_1:
        user:         '@user_1'
        group:      '@group_1'
```

While the user fixture is built this way:

```
My\AppBundle\Entity\User:
    user_1:
        name: 'Foobar'
```

Do you need any other specific information?

**Comment by theofidry** [comment]
yes, the entity code :) The fixtures are fine, the usage as well. So it must come from somewhere else: either in the mapping, custom code, or an edge case with Doctrine.

**Comment by oniric85** [comment]
Here is the relevant part of User entity code

```
<?php

class User
{
    private $id;
    private $name;
    private $groups;

    public function __construct()
    {
        $this->groups = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setName($name)
    {
        $this->name= $name;

        return $this;
    }

    public function getName()
    {
        return $this->name;
    }

    public function addGroup(Group $group)
    {
        $this->groups[] = $group;

        return $this;
    }

    public function removeGroup(Group $group)
    {
        $this->groups->removeElement($group);
    }

    public function getGroups()
    {
        return $this->groups;
    }
}
```
The Group entity code is very similar but there are only the methods to set/get the user.
Is there something I need to consider in the entity code to make the fixtures work fine?

**Comment by theofidry** [comment]
Hm, nothing abnormal :/ I guess I'll have to dig into it.

Last lead I have (but requires debugging): might be related on how the group is set. There is a bit of magic in alice 2.x regarding that which I removed in 3.x.

**Comment by oniric85** [comment]
@theofidry I'm willing to look into that if you provide more details :)

**Comment by theofidry** [comment]
well, I'm actually not sure what level of details you need :P One thing would be to check _how_ the property are set and if the result is the good one (done in `Hydrator` in alice), then check the result _after_ the loading see what are the diff (a persist()/flush() must have been done in-between).

**Comment by theofidry** [comment]
to give a bit of insight regarding the mechanisms:

- HautelookAliceBundle looks for the files to load and try to load them one by one (don't bail on failure)
- if some files could not be loaded, retry to load them (as the results of the previous files are injected as it goes, they may succeed this time)
- repeat the process until all files are loaded or loading limit reached

When loading a file, here's what happens:

- all the fixtures found in the file are instantiated
- then they are populated one by one
- then they are persisted

Be it 2.x or 3.x, this high level logic is the same

**Comment by oniric85** [comment]
Should I define both sides of the association in my fixture files to make this work? I wonder how the process works if I don't.

**Comment by theofidry** [comment]
That depends on your entities. To be honest there is not much alice-specific there, just plain old doctrine :P I'm not saying that to dismiss the issue, but more to say this is directly related on how you use your entities. What is done by alice is in the end something similar to:

```php
$user1 = new User();
$user1->setName('Foobar');

$group_1 = ...;

$usergroup_1 = new UserGroup();
$usergroup_1->setUser($user1);
$usergroup_1->setGroup($group_1);

$doctrineManager->persist($user1);
$doctrineManager->persist($group_1);
$doctrineManager->persist($usergroup_1);

$doctrineManager->flush();
```

**Comment by oniric85** [comment]
Isn't also necessary to have `$user1->addUserGroup($userGroup_1)` to populate also the User side of the association? See [here](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#synchronizing-bidirectional-collections) from the Doctrine doc.

**Comment by theofidry** [comment]
Then you need to specify it in Alice :) There is no way to guess that for
Alice, as you could very well set the other direction directly in your
setter.

**Comment by oniric85** [comment]
I tried to setup a `usergroups` property in the User fixture but it seems like it's causing a circular issue as the UserGroup entity needs a User and the User needs a UserGroup. I now get various 'Instance user_1 is not defined' and 'Instance usergroup_1 is not defined' messages.

**Comment by theofidry** [comment]
Ah it's true there is this issue :/ Either configure a custom setter or
define the other side directly in your setter.

An alternative solution would be to migrate to 3.0 where this problem is
solved

**Comment by oniric85** [comment]
I'm not sure what you mean by configuring a custom setter, is there something in the doc about this? BTW, you mean migrating to HautelookAliceBundle 2.0? I don't see any 3.0 version :)

**Comment by theofidry** [comment]
Yeah, just there https://github.com/nelmio/alice/blob/2.x/doc/complete-reference.md#custom-setter :)

>you mean migrating to HautelookAliceBundle 2.0? I don't see any 3.0 version :)

Yes, which uses alice 3.0. Maybe I should allign the version of the 3 projects...

**Comment by oniric85** [comment]
I see but I would prefer not to add a new method on my entities to make fixtures work. Do you think a Process can be used to solve this? Like this:

- Process the UserGroup entity
- Get the User object from it
- Call a setter on the User to add the UserGroup to that side of the association

**Comment by theofidry** [comment]
I think the setter is the way to go :)

**Comment by oniric85** [comment]
I was able to make it work with the processor! This is already something :) I don't like the idea of adding magic stuff to my entities, also seems deprecated in the next version. For the moment I'll stick with the processor approach. Do you think something about this issue is worth adding into the doc?

**Comment by theofidry** [comment]
Yeah this could definitely be added in the doc, as I think it's a not so rare use case.

What is deprecated in the next version is the custom setter, as there is more elegant ways to do it. In alice 3.0 you could either:

- Add a configurator (not supported yet though)
- Add a custom hydrator to ensure whenever you are setting one part of the relationship you do it on the other side
- Add a pre-processor to go through all your users to set the other direction

**Comment by carlosival** [comment]
@oniric85 can you share the solution for anyone in the same situation ?

**Comment by theofidry** [comment]
Closing as it's not really specific to HautelookAliceBundle unless there is something specific missing in the doc that you are expecting.
