### ISSUE TITLE
--purge-with-truncate fails because of foreign key constraints

### ISSUE THREAD

**Issue by WillGibson** [hautelook/AliceBundle#333]
Hi, I am experiencing this with v2.0.0-beta.3...

```
# ./bin/console hautelook:fixtures:load -n --purge-with-truncate

  [Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException]
  An exception occurred while executing 'DELETE FROM fos_user':
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`some_database_name`.`some_table`, CONST
  RAINT `FK_C7440455D3564642` FOREIGN KEY (`createdBy`) REFERENCES `fos_user` (`id`))
```

Other tables are affected too.

I have a temporary fudge in place, basically drop the schema and run the Doctrine migrations, but it's not pretty.

Maybe I'm missing something, or something needs fiddling?

Happy to pitch in and try to help with a PR if it needs doing.

**Comment by theofidry** [comment]
Hi, I believe https://github.com/theofidry/AliceDataFixtures/pull/32 can fix this issue.

I unfortunately didn't have the time to properly review it, and as I think there's a hole in the test suite regarding that peculiar part, a manual check is necessary.

So if you can help with the review (actually more the manual test) and fix the tests, then I could merge the PRs without further delay :)

**Comment by WillGibson** [comment]
I'll have a look at the PR over lunch, but anything more may have to wait until our next spike day as there are deadlines and things.

**Comment by WillGibson** [comment]
@theofidry Looking at that PR, assuming we don't want the disabling of foreign keys in this project, as I think we both agree that it would maybe belong in Doctrine\Common\DataFixtures\Purger\ORMPurger, not here, I don't think that PR actually changes anything.

I've also been playing with our cascading delete, but the purging with truncate still falls over the foreign keys, so I have dealt with the purge outside of here.

It does seem that the --purge-with-truncate option does not get through to \Fidry\AliceDataFixtures\Loader\PurgerLoader::load() though.

I doubt I'll be able to look at that today, because now we are doing our truncating outside of here, we just want to append, and are getting caught out by this...

```
./bin/console hautelook:fixtures:load -n --append --env=dev

  [LogicException]
  Cannot append loaded fixtures and at the same time purge the database. Choose one.
```

I think I'll close this issue and maybe have a look at that.
