### ISSUE TITLE
Cant set locale in my symfony config

### ISSUE THREAD

**Issue by chucky2305** [hautelook/AliceBundle#335]
```
hautelook_alice:
    fixtures_path: '/DatabaseFixtures/alice'
    locale: de_DE
```

When i try to load my fixtures by `php bin/console hautelook:fixtures:load` i get:

```
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
 Unrecognized option "locale" under "hautelook_alice"
```

**Comment by theofidry** [comment]
In HautelookAliceBundle 2.x, that part of the configuration has been moved down to [alice](https://github.com/nelmio/alice/blob/master/doc/getting-started.md#symfony).

**Comment by chucky2305** [comment]
Thank you very much Théo!
