### ISSUE TITLE
bin/console does not work without database when bundle is active

### ISSUE THREAD

**Issue by NerdyProjects** [hautelook/AliceBundle#337]
After installing the AliceBundle, I cannot use `bin/console doctrine:database:create` with a not existing database as initialization of this bundle wants to access the database:
`./bin/console --env=test -vv`:
```
[Doctrine\DBAL\Exception\ConnectionException]                                               
  An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'foodsharing_test'  
                                                                                              

Exception trace:
 () at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145
 Doctrine\DBAL\DBALException::driverException() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:47
 Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
 Doctrine\DBAL\Connection->connect() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
 Doctrine\DBAL\Connection->getDatabasePlatform() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:763
 Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:616
 Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:174
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:115
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php:69
 Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister->getPersistableClasses() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php:42
 Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister->__construct() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/var/cache/test/appTestDebugProjectContainer.php:1196
 appTestDebugProjectContainer->getFidryAliceDataFixtures_Persistence_Persister_Doctrine_ObjectManagerPersisterService() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310
 Symfony\Component\DependencyInjection\Container->get() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/var/cache/test/appTestDebugProjectContainer.php:1136
 appTestDebugProjectContainer->getFidryAliceDataFixtures_Doctrine_PersisterLoaderService() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310
 Symfony\Component\DependencyInjection\Container->get() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/var/cache/test/appTestDebugProjectContainer.php:2279
 appTestDebugProjectContainer->getHautelookAlice_Loader_DoctrineOrmLoaderService() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310
 Symfony\Component\DependencyInjection\Container->get() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/var/cache/test/appTestDebugProjectContainer.php:2253
 appTestDebugProjectContainer->getHautelookAlice_Console_Command_Doctrine_DoctrineOrmLoadDataFixturesCommandService() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:310
 Symfony\Component\DependencyInjection\Container->get() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:141
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:108
 Symfony\Bundle\FrameworkBundle\Console\Application->all() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:72
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /home/matthias/Projekte/foodsharing/src/foodsharing-api/bin/console:28
```

You can check out https://github.com/foodsharing-dev/foodsharing-api/commit/b34e67a727616e8d25c380545f24e0b68f730e41 to try that or just use the project you are on currently and run `./bin/console doctrine:database:drop --force`. Afterwards you need to manually recreate it before the console command will work again.

**Comment by theofidry** [comment]
You get that problem because your application tries to establish a connection on startup, which is not really desirable and you could get around that by installing `ocramius/proxy-manager`. Otherwise yeah you need to create the database accordingly. I'm not sure what could be done here except having a custom proxy which I don't really want to have (it's more to maintain for something for which installing the right package solve).

**Comment by NerdyProjects** [comment]
Thanks for your quick reply. Please forgive me asking again - this is my first symfony project and I am still trying out things.

I setup the project basically following the documentation on Symfony as well as FOSRestBundle and am trying to build up a nice stack for this project.

You stated, that my 

> application tries to establish a connection on startup, which is not really desirable

and I don't have a clue how to get around this or why not all projects using AliceBundle suffer from the problem I wrote above? To clarify, I setup a test project:
```
symfony new test-alicebundle
cd test-alicebundle
composer require --dev hautelook/alice-bundle:^2.0@beta \                                                  1 ↵
  nelmio/alice:^3.0@beta \
  theofidry/alice-data-fixtures:^1.0@beta \
  doctrine/data-fixtures
```
I also set parameters.yml to a valid database connection and enable AliceBundle. Now, I can use
`./bin/console doctrine:database:drop --force` as well as `./bin/console doctrine:database:create`.

As soon as I add an Entity declaration,
```
<?php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity
 */
class User {
  /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
}
```
(and run doctrine:generate:entities AppBundle)
I cannot recreate the database after dropping it. Stacktrace is conceptually the same as above. As soon as I remove AliceBundle from AppKernel.php (and remove the corresponding configuration), it works again.

So is this really expected behaviour, that in a default symfony installation adding this bundle might break the console utility when the database is missing? I am also not sure, how the proxy-manager should help me here.

**Comment by theofidry** [comment]
As it stands, you application tries to establish a connection when the kernel is booting (so when handling a request or starting a command). If the parameters are wrong, then it fails...

So there is several solution possible:

- Create the database first (either via doctrine before installing the bundle or a simple mysql command) and provide the right parameters. Then you'll be able to update your schema and more as usual
- Prevent your application to establish a database connection when booting

For the second point, that is where lazy loading comes. The doctrine entity manager tries to establish a connection when _instantiated_. As it is registered as a service and injected somewhere in your app, it is instantiated when starting your application. However if your service is declared as lazy, then it won't be instantiated directly, but instead a proxy will be passed (it actually depends on how the lazy loading is implemented but the idea remains the same). That proxy will, once used, call the underlying service to do the real work. In other words, in the case above, the entity manager will not be instantiated (and hence trigger a DB connection) before it is actually called.

ocramius/proxy-manager is just a standard library helping with lazy loading. When installed, any service declared as `lazy=true` will be lazy loaded (otherwise that declaration doesn't do anything).

**Comment by NerdyProjects** [comment]
Okay, I tried it using ocramius/proxy-manager. Funny thing: Symfony magic alone was enough - just having that installed fixed the problem, no configuration at all involved. (Double checked by removing the package).

Your proposed solutions are clear to me, it just did not get into my head that the stacktrace shew AliceDataFixtures in between still that not being the cause.

So thanks again :-)

**Comment by theofidry** [comment]
You're welcome
