### ISSUE TITLE
How to set without ID? I use UUID for my data

### ISSUE THREAD

**Issue by synchr0n123r** [hautelook/AliceBundle#339]
Hi There,

Is anyone have problem when use UUID?
i got this error:

`  [Doctrine\ORM\ORMException]                                                                                                                                                 
  Entity of type AppBundle\Entity\Brand is missing an assigned ID for field  'uuid'. The identifier generation strategy for this entity requires the ID field to be populate  
  d before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.    `

is there any way to work with UUID?

**Comment by theofidry** [comment]
The message is quite self-explanatory, just assign a UUID to your entity when creating it or at any point before persisting it (e.g. in a pre-processor).
