### ISSUE TITLE
Unable to use file provider

### ISSUE THREAD

**Issue by apetitpa** [hautelook/AliceBundle#341]
Using `<file('/foo', '/bar', false)>` in .yml file throws `[Symfony\Component\Debug\Exception\FatalThrowableError] Type error: file() expects parameter 2 to be integer, string given` when loading fixtures.

**Comment by theofidry** [comment]
Well, this is still YAML so yes `file` will receive `'false'`, not `false`. If you want that you have to cast it via a custom faker provider, having a param or use `settype()`
