### ISSUE TITLE
Class OrmPurger not found (actually named Purger)

### ISSUE THREAD

**Issue by Gounlaf** [hautelook/AliceBundle#346]
Hi,

I just installed this bundler:

```json
"require-dev": {
        [...]
        "hautelook/alice-bundle": "^2.0@beta",
        "nelmio/alice": "^3.0@beta",
        "theofidry/alice-data-fixtures": "^1.0@beta",
        "doctrine/data-fixtures": "^1.2"
}
```

Resolved as:

```
hautelook/alice-bundle: v2.0.0-beta.3
nelmio/alice: v3.0.0-RC.1 
theofidry/alice-data-fixtures: v1.0.0-beta.5
doctrine/data-fixtures: v1.2.2
```

I got an exception:

> hautelook:fixtures:load -vvv
> Careful, database will be purged. Do you want to continue y/N ?y
> [2017-06-29 20:48:51] app.INFO: fixtures found {"files":[]} 
> 
>                                                                                                         
>   [Symfony\Component\Debug\Exception\ClassNotFoundException]                                            
>   Attempted to load class "OrmPurger" from namespace "Fidry\AliceDataFixtures\Bridge\Doctrine\Purger".  
>   Did you forget a "use" statement for another namespace?                                               
>                                                                                                         
> 
> Exception trace:
>  () at /path/to/my/project/vendor/hautelook/alice-bundle/src/Loader/DoctrineOrmLoader.php:168
>  Hautelook\AliceBundle\Loader\DoctrineOrmLoader->loadFixtures() at /path/to/my/project/vendor/hautelook/alice-bundle/src/Loader/DoctrineOrmLoader.php:104
>  Hautelook\AliceBundle\Loader\DoctrineOrmLoader->load() at /path/to/my/project/vendor/hautelook/alice-bundle/src/Console/Command/Doctrine/DoctrineOrmLoadDataFixturesCommand.php:139
>  Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand->execute() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
>  Symfony\Component\Console\Command\Command->run() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:854
>  Symfony\Component\Console\Application->doRunCommand() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:201
>  Symfony\Component\Console\Application->doRun() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/to/my/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:125
>  Symfony\Component\Console\Application->run() at /path/to/my/project/bin/console:27

https://github.com/hautelook/AliceBundle/blob/master/src/Loader/DoctrineOrmLoader.php#L8

Class name have changed?
=> https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Purger/Purger.php

Regards

**Comment by theofidry** [comment]
Tcheh. Indeed it did change, downgrade to `theofidry/alice-data-fixtures: 1.0.0-beta.5@beta` that should do the trick. The latest version of AliceDataFixtures has some BC breaks and I need to update HautelookAliceBundle accordingly (will be done during the weekend)

**Comment by Gounlaf** [comment]
Hi @theofidry,

I changed the line manually in vendor (yeah... I know, it's ugly).
As expected it works again :) It will be ok until the next version ^^

Thanks

**Comment by curry684** [comment]
Workaround for now is to use this in your bootstrap:
```
class_alias('Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\Purger', 'Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\OrmPurger');
```

**Comment by theofidry** [comment]
Should be fixed now :)
