### ISSUE TITLE
Attempt at loading ORMPurger fails

### ISSUE THREAD

**Issue by nmeirik** [hautelook/AliceBundle#352]
After installing the bundle according to the documentation, and then attempting to load fixtures, I get the following error:

```
[Symfony\Component\Debug\Exception\ClassNotFoundException]                         
  Attempted to load class "OrmPurger" from namespace "Fidry\AliceDataFixtures\Bridg  
  e\Doctrine\Purger".                                                                
  Did you forget a "use" statement for another namespace?  
```

I suspect the error being related to [this discussion](https://github.com/theofidry/AliceDataFixtures/pull/42#issuecomment-303733362). Am I correct in creating this issue?

**Comment by theofidry** [comment]
Could you show which versions you're using?

**Comment by nmeirik** [comment]
I utilized the [installation instructions](https://github.com/hautelook/AliceBundle):

```
composer require --dev hautelook/alice-bundle:^2.0@beta \
  nelmio/alice:^3.0@beta \
  theofidry/alice-data-fixtures:^1.0@beta \
  doctrine/data-fixtures
```
which got me:

* hautelook/alice-bundle: v2.0.0-beta.3
* theofidry/alice-data-fixtures: v1.0.0-beta.5
* nelmio/alice: v3.0.0-RC.1

**Comment by theofidry** [comment]
I think you just need to update `hautelook/alice-bundle` to `v2.0.0-beta.4` then :)

**Comment by nmeirik** [comment]
Thanks a lot, that did the trick! Also, running the installation command from scratch now appears to install beta.4. Did you perhaps make some change on Packagist in the mean time?

**Comment by theofidry** [comment]
Hm no that version has been published almost 10 days ago now, but glad that you sorted that out :)

**Comment by nmeirik** [comment]
I was thinking you perhaps removed beta.5 as it does not appear to be listed as the most recent package on Packagist now. In any case - thanks a lot for your help!
