### ISSUE TITLE
Project root directory changes when upgrading to Symfony 3.3

### ISSUE THREAD

**Issue by nmeirik** [hautelook/AliceBundle#353]
I noticed the following which might be relevant to mention in the documentation.

After upgrading to Symfony 3.3, the loading of fixtures started to failed without any warning. After some digging, I tracked it down to [this piece of code](https://github.com/hautelook/AliceBundle/blob/master/src/DependencyInjection/HautelookAliceExtension.php#L96) which makes use of `kernel.project_dir`if it exists (which is does in Symfony 3.3), otherwise it uses `kernel.root_dir`. I guess the latter points to the `app/`directory, while the former points to the root of the entire Symfony directory structure.

After realizing this, all I had to do was to add `app/` to the `hautelook_alice.fixtures_path` to get it working again. However, you might want to alter this behaviour (keeping the behaviour consistent across Symfony versions) or mentioning it somewhere in the documentation.

**Comment by robertfausk** [comment]
Same as #355

**Comment by robertfausk** [comment]
@theofidry You can close this now:)
