### ISSUE TITLE
`hautelook_alice.resolver.bundle` is hardcoded to use only default_entity_manager

### ISSUE THREAD

**Issue by raulferras** [hautelook/AliceBundle#356]
I'm using multiple entity managers in my application and cannot persist entities that are not defined in the default manager because `hautelook_alice.data_fixtures.loader` service defines to use the `default_entity_manager` by hard-coding it in the configuration file.

Is there an easy way to force using mine without changing environments?

**Comment by theofidry** [comment]
An easy way is to override the configuration: if you have one entity manager that can handle everything then override the service using that entity manager. If you don't and need to use different managers depending of the entity persisted you'll have to change two things:

- The persister service
- The purger

For the first, I think it's rather trivial: check the entity class and depending of it pick manager X or Y. For the later I don't have any idea as we actually rely on Doctrine purgers which takes a single entity manager as an argument. So maybe you'll need to use several purgers at once...

The theory should remain the same regardless of the version you are using, but if you need further help I need more info :)

**Comment by raulferras** [comment]
My scenario covers the second case, every entity manager can handle a collection of different entities.
So if I'm not mistaken, I need to clone and specify my own entity manager:
- `fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister`

and also:
- `fidry_alice_data_fixtures.doctrine.persister_loader` 

Which is the service that uses the persister.
