### ISSUE TITLE
Randomizing Bridge (Many-to-many relationship) Tables while retaining Integrity to Parent

### ISSUE THREAD

**Issue by davidlarrimore** [hautelook/AliceBundle#357]
Hi!,

I use AliceBundle to generate random data. My database is moderately complex with many-to-many relationships where the entities themselves are a child of a common parent (one-to-many) entity. 

Example:

```
Teams can have many Students
Students can be apart of many Teams
This is managed by a separate TeamStudent Entity that includes other information about the relationship
```

In this environment, both *Team* and *Student* entities are many-to-one child of a *Campaign* entity.

Example:

```
Campaigns can have many Students
Campaigns can have many Teams
This is managed by a traditional one-to-many entity relationship
```

Current Fixtures:

```
AppBundle\Entity\Student:
    student{1..1000}:
        name: <firstName()> <lastName()>
        campaign: '@campaign*'

AppBundle\Entity\Team:
    team{1..10}:
        name: 'Team <current()>'
        url: 'team<current()>'
        campaign: '@campaign*'
        user: '@user<current()>'
        teamType: '@teamType2'
        fundingGoal: <randomFloat(2, 50, 200)>

AppBundle\Entity\TeamStudent:
    br_team_student{1..100}:
        student: '@student*'
        team: '@team*'
        name: <firstName()> <lastName()>

```

This will randomize the elements without ensuring that the student and team are apart of the same campaign. Is there a way to maintain referencial integrity with the parent *Campaign* entity?

Thanks!

**Comment by theofidry** [comment]
I don't think there's an easy out-of-the-box way to do it. Indeed your assignment of `campaign` depends of rules requiring all the other relationships to be completed. So the way to go IMO would be to decorate the loader to set the campaign after all the entities are loaded. Note that you can still assign them randomly by calling faker directly

**Comment by davidlarrimore** [comment]
I apologize for my ignorance of Alice, Faker, and your AliceBundle, but how do I create a custom loader (which is what I assume is what you mean by decorate the loader)?

**Comment by theofidry** [comment]
>which is what I assume is what you mean by decorate the loader

Right assumption :) In symfony it can easily bone by declaring your own service with the same service ID.

**Comment by davidlarrimore** [comment]
I have so many questions on declaring my own service, but thats on me research. I'll be happy to share if I am able to come to a good resolution on this.

Meanwhile, another possible way to solve the problem would be to design the fixtures to load one campaign at a time with its Teams, Students, and TeamStudents. I know I can use the "--append" option to repeat the process from a CI/CD perspective, but is there a hautelook:fixtures:load option and to only run a specific set of fixtures? the "--fixtures" option doesn't exist.

**Comment by theofidry** [comment]
>I have so many questions on declaring my own service

Feel free to ask for help on symfony-dev: [Slack invite](https://symfony.com/slack-invite)

>is there a hautelook:fixtures:load option and to only run a specific set of fixtures? the "--fixtures" option doesn't exist.

That could be a new feature indeed :)

**Comment by theofidry** [comment]
Closing as the question has been answered. Feel free to ping me on slack for those kind of questions :)
