### ISSUE TITLE
Force an explicit load order

### ISSUE THREAD

**Issue by JeromeGill** [hautelook/AliceBundle#359]
Is it currently possible to force an explicit load order for fixture files?

I.e if I have a directory structure

../AppBundle/Resources/fixtures/test/001_fixtures_file1.yml
../AppBundle/Resources/fixtures/test/002_fixtures_file2.yml
../AppBundle/Resources/fixtures/test/003_fixtures_file3.yml

Is there some way to force flush between each file? ATM it seems to try to call flush on all files simultaneously which is limiting in terms of making sure identities etc are available in later fixtures or am I missing something?

**Comment by theofidry** [comment]
>Is it currently possible to force an explicit load order for fixture files?

Yes, you can manually order them by decorating the loader or the finder.

>Is there some way to force flush between each file

The easiest way to do so would be to create your own loader. You can use the existing services to locate the files and load a file, you just need to adapt the logic to load them one at a time.

> ATM it seems to try to call flush on all files simultaneously which is limiting in terms of making sure identities etc are available in later fixtures or am I missing something?

Right now it loads all the files to get the PHP objects and then persist each of them before doing a big flush

**Comment by JeromeGill** [comment]
I thought custom loaders were deprecated and removed at some point?

**Comment by theofidry** [comment]
Not sure where you got that impression, but no. The thing that changes between HautelookAliceBundle 1.x and 2.x is that a lot of workaround done in 1.x have been merged back to Alice 3.x and theofidry/AliceDataFixtures to make things either especially when it comes to customising things

**Comment by theofidry** [comment]
That said if you are using HautelookAliceBundle 1.x, I think what I said above is wrong. IIRC the files are loaded one by one with a flush for each of them

**Comment by theofidry** [comment]
Closed via #369
