### ISSUE TITLE
Can't install with PHP7.1

### ISSUE THREAD

**Issue by JeremyGreaux** [hautelook/AliceBundle#360]
Hi, 
I want to use AliceBundle, but I have an error on composer install:
`
 Problem 1
    - hautelook/alice-bundle v2.0.0-beta.4 requires php ^7.0 -> your PHP version (7.1.8-2+0~20170804100723.7+jessie~1.gbpae7f04) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
`
It is possible to add php 7.X compatibility ? (If I install with "--ignore-platform-reqs", it's work)

**Comment by theofidry** [comment]
This library _is_ compatibly with PHP 7 (`php: ^7.0` so `7.1.*` is allowed).

>overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.

This line looks suspicious to me. Do you have a platform version configured in your `composer.json`?

**Comment by JeremyGreaux** [comment]
Sorry, it's on my own composer.json config ...
