### ISSUE TITLE
Why not just user nelmio/alice with doctrine fixtures?

### ISSUE THREAD

**Issue by DudleyDawson** [hautelook/AliceBundle#362]
My apologies if this has been asked before, but I think it can be better documented in the readme. I googled a bit for an answer to this to no avail.
 It's my understanding that this is a thin wrapper over those libraries/bundles. I'm not quite sure why I would use this as opposed to directly using nelmio/alice?

**Comment by curry684** [comment]
Why would anyone install the Facebook SDK? In the end it's just a thin wrapper over an HTTP REST client. Why not just grab Guzzle and use that directly?

The answer is the same: convenience. Having a structured, supported and maintained central point of entry towards multiple related libraries and packages. Less code on your end, less bugs, less development time. More time for coding the fun stuff of your application.

**Comment by theofidry** [comment]
Feel free to use alice directly, I do so sometimes :)

I think this should be added in a FAQ:

- NelmioAlice is about loading fixtures (plain PHP objects)
- FidryAliceDataFixtures is about adding a persistence layer, i.e. wrapping NelmioAlice to persist the loaded fixtures
- HautelookAliceBundle is about discovering the fixture files to load

**Comment by DudleyDawson** [comment]
Thank you @curry684 & @theofidry for the prompt responses. If some time frees up this week I'll submit a PR with this added to the readme(as an FAQ section).
