### ISSUE TITLE
How to load fixtures for only one specific entity

### ISSUE THREAD

**Issue by lbenz** [hautelook/AliceBundle#377]
Hi,

I can't find a way to generate fixtures for only one entity like we can do with "doctrine:fixtures:load --fixtures="/path/entity" ?

Are there any solutions for this ?

**Comment by theofidry** [comment]
Not really as first `doctrine:fixtures:load` is a command from DoctrineDataFixturesBundle not HautelookAliceBundle and second I don't think it would be easy to do. If you need specific fixtures for your tests for example, you're better off getting the loader service and load the specific files you want rather

**Comment by lbenz** [comment]
Thank you very much i have found a way to do this easily thanks to you.
`protected function setUp() {
        $kernel = self::bootKernel();
        $this->manager = $kernel->getContainer()->get('doctrine.orm.entity_manager');
        $this->loader = $kernel->getContainer()->get('hautelook_alice.fixtures.loader');
        $this->loadFixtures();
    }

    /**
     *
     */
    protected function loadFixtures() {

        $this->loader->load(
            new DoctrinePersister($this->manager),
            array(
                static::$kernel->locateResource('@ApiBundle/Resources/fixtures/api.yml'),
            )
        );
    }`

**Comment by atunjeafolabi** [comment]
Any solution for this yet? I'm trying to load a fixture for a specific entity like _Ibenz_ specificed.

**Comment by atunjeafolabi** [comment]
Any solution for this yet? I'm trying to load a fixture for a specific entity like _Ibenz_ specificed.
