### ISSUE TITLE
How to set `loading_limit` ? 

### ISSUE THREAD

**Issue by shubaivan** [hautelook/AliceBundle#381]
After update `hautelook/alice-bundle` to version 1.4 I have error

    Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException: Loading files limit of 5 reached. Could not load the following files:
    path to file
    - Instance user_1 is not defined

How to set `loading_limit` for more five time loading ?

**Comment by theofidry** [comment]
You have an option [in the config](https://github.com/hautelook/AliceBundle/tree/1.x#installation) for it

**Comment by shubaivan** [comment]
It's work, but after set loading_limit 20 I still have error 

`Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException: Loading files limit of 20 reached. Could not load the following files:
path to file
- Instance user_1 is not defined`

this my fixtures

`AppBundle\Entity\Employee:
    employee_1:
        level: "@employeeLevel_1"
        user: "@user_1"
        serviceCompany: "@serviceCompany_1"
        salary: 10
        guaranteedSalary: 0
        costObjectId: "@costObject_1"
        commissionModel: "@commissionModel_1"
        contractStart: <dateTimeThisMonth('now')>
        ssn: 'ssn'`

**Comment by theofidry** [comment]
can you try a verbose mode and check which files are being loaded?

**Comment by shubaivan** [comment]
I debaged it and first loaded `user_1` then `employee_1` with references employeeLevel_1 serviceCompany_1 costObject_1 commissionModel_1 but without user_1 because this fixture loaded early

**Comment by theofidry** [comment]
HautelookAliceBundle tries to be smart about it and if cannot load a file because depend of fixtures from another file then it loads the other files and retry the failed files after. This is why I'm asking the verbose mode to see what's going on

**Comment by theofidry** [comment]
Any news regarding this issue @shubaivan?

**Comment by theofidry** [comment]
Since 1.x is no longer maintained and there was no answer, I'll be closing this one
