### ISSUE TITLE
Unrecognized option "db_drivers" under "hautelook_alice"

### ISSUE THREAD

**Issue by nalekberov** [hautelook/AliceBundle#386]
I have installed `hautelook/alice-bundle package` package from `symfony.sh` on a Symfony Flex application, however when I run `./bin/console cache:run` it outputs this error:
`
Unrecognized option "db_drivers" under "hautelook_alice"
`
I looked up the `Configuration.php` of the package. There are just two options:
`fixtures_path` and `root_dirs`.

I have used this bundle in old symfony packages without any issues.

I wonder whether I'm missing any necessary package?

**Comment by theofidry** [comment]
Hi, I think you simply installed 2.0.0 which no longer has `db_drivers` for now at least :)

**Comment by nalekberov** [comment]
Thank you @theofidry !

**Comment by ebuildy** [comment]
+1

In a Symfony 4 project, running ``composer require --dev hautelook/alice-bundle``

![installation via composer](https://beemapp2.s3.amazonaws.com/83ad6eaf-5fbe-44e6-99bd-94f3b11ba20d.jpg)

**Comment by theofidry** [comment]
The flex recipe above says `>=1.4` but that's wrong, it should be `^1.4` so maybe the recipe for 1.x needs to be fixed.

[Also 2.0 doesn't have a recipe yet.](https://github.com/hautelook/AliceBundle/issues/380#issuecomment-348811984)

**Comment by ebuildy** [comment]
I have just ran ``require`` without version, from a fresh install of Symfony 4.

**Comment by theofidry** [comment]
Well you are prompted a `Do you want to execute that recipe?` in which you can say `no` instead of `yes`.

That said there is definitely a bug as it should not be `>=1.4`... And a 2.0 recipe would be nice :)
