### ISSUE TITLE
Loading a single file/list of files.

### ISSUE THREAD

**Issue by ndyakov** [hautelook/AliceBundle#390]
Is there a way to load a set of files rather than all fixtures for a specific bundle?

**Comment by theofidry** [comment]
You can specify which bundle to use. But if you have a better idea on which files need to be loaded, you can directly use the loader of AliceDataFixtures instead

**Comment by ndyakov** [comment]
@theofidry Do you mean using the loader in a script?

**Comment by theofidry** [comment]
Yes, or if you want a command still you can always declare your own command for it

**Comment by ndyakov** [comment]
@theofidry Thank you, I will look at `AliceDataFixtures` and try to define a custom command for my needs.
