### ISSUE TITLE
Loading fixtures from folder

### ISSUE THREAD

**Issue by novacp** [hautelook/AliceBundle#398]
Trying to load specific fixtures for my tests using version ^2.0 of this bundle:
1) for phpunit tests, living in the subfolder /test_phpunit/user.yml
2) for behat tests, living in the subfolder /test_behat/user.yml

In the past, I could simply specify the folder to load from by using --env=test_phpunit or --env=test_behat *WITHOUT* these environments to actually exist in symfony. Now I cannot find a way to specify target folders anymore when using version ^2.0 of this bundle .. when trying the old method, I get the error "There are no commands defined in the "hautelook:fixtures" namespace.".. 

How is it possible to solve the above (common) usecase? I also took a look at the loader service, which doesn't fit either for this case imho.

Regards.

**Comment by theofidry** [comment]
>by using --env=test_phpunit or --env=test_behat WITHOUT these environments to actually exist in symfony

This _will_ use Symfony environments. However Symfony has no restriction on which environment is used at all so `--env=random` works fine. The difference between environments lies in your configuration: which bundle you configure in what environment. Some are configured in all and some others only in `test` or `dev` by default.

In this specific case, it looks like `HautelookAliceBundle` is not registered in those environments.

>I also took a look at the loader service, which doesn't fit either for this case imho.

Are those fixtures used across _all_ your tests? If so I would recommend against it in the first place but you can also take a look at https://github.com/theofidry/AliceDataFixtures#usage-in-tests

**Comment by Awkan** [comment]
Hi,

I am currently experiencing the same problem due to Symfony Bundles environment declaration.    

I have my fixtures inside `Resources/fixtures/event/` folder. By following the doc about environment, I run the command `bin/console hautelook:fixtures:load --env=event`. However I only use this bundle for dev environment which lead to the following config (flex):
```php
return [
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true],
    Hautelook\AliceBundle\HautelookAliceBundle::class => ['dev' => true, 'test' => true],
];
```

But to use my fixture folder I have to declare bundles like:

```php
return [
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true, 'event' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true, 'event' => true],
    Hautelook\AliceBundle\HautelookAliceBundle::class => ['dev' => true, 'test' => true, 'event' => true],
];
```

I don't like to mix SF env & fixtures env. The solution could be to use a new option in command like `--folder=event` in order to dissociate SF env & fixtures env ?

**Comment by theofidry** [comment]
@Awkan the SF env should be the same as the fixtures env. A typical example is if you have a set of fixtures for dev and staging. When you do `env=dev` and `env=staging` then you expect the fixtures to be persisted in their respective databases.

>The solution could be to use a new option in command like --folder=event

You could rename it `--dir` or event `--dirs` instead but yes I'm fine with that. I have no idea on how much work is required for make it to work though.

**Comment by novacp** [comment]
Well, the mixture has pros and cons. Think of testing env with multiple test stages, that all have their own fixtures: phpunit, behat.. it feels not right to create a symfony environment for each testing stage, as different fixtures are needed. In the last version, their was no mixture of symfony and fixtures environments, at least it wasn't enforced, maybei the idea was the same.

**Comment by theofidry** [comment]
>In the last version, their was no mixture of symfony and fixtures environments, at least it wasn't enforced, maybei the idea was the same.

As far as I can remember it was. The difference was how you could register the bundles which allowed you to more easily register it in different kind of environments. Actually this is still possible: just look at your kernel class how bundles are registered you can extend it to register this specific bundle in more dynamic environments. The only caveat is if there is ever any flex recipe this is not gonna work automatically with flex (which is also fine, just be aware of it)

**Comment by novacp** [comment]
Yes that could be correct @theofidry . Which env did symfony then use when specifying some random env name, e.g. "test_phpunit" without config files for this env? Did it use as default env "dev", or "test"?

**Comment by theofidry** [comment]
>Which env did symfony then use when specifying some random env name, e.g. "test_phpunit" without config files for this env? Did it use as default env "dev", or "test"?

If you did `--env=test_phpunit` then it was using the `test_phpunit` environment. There is no magic there. As to what bundle and things are configured in those environments entirely depends on your kernel configuration

**Comment by alcalyn** [comment]
This is a feature I'd like to have.

I don't need fixtures related to an environment, but just a folder, like `base/` for features I always need, `demo/` for a specific dataset used to easily test the application with some fake data.

"Environnement specific fixtures" almost does the thing, but I don't expect folders related to environment.

*However, for integration testing, I use independently loaded fixtures in each Scenario or Feature, with something like `Given I have loaded fixtures from :filename`*
