### ISSUE TITLE
Reverse insertion in many to many relation does not work

### ISSUE THREAD

**Issue by tejasnavghane** [hautelook/AliceBundle#399]
```
AppBundle\Entity\User:
    user{1..100}:
        vouchers: ['@voucher<numberBetween(1, 100)>']

AppBundle\Entity\Voucher:
    voucher{1..200}:
        name: <text(255)>
        slug (unique): <sha256()>
        code (unique): <sha256()>
        cashAvailable: <numberBetween(1, 500)>
        cashReserved: <numberBetween(1, 10)>
        cashUsed: <numberBetween(1, 10)>
        active: <boolean(95)>
        createdAt: <dateTime()>
        updatedAt: <dateTime()>
        start: <dateTimeBetween('-1 month', 'now')>
        end: <dateTimeInInterval('now' , '+ 6 months')>
        plan: '@plan<numberBetween(1, 100)>'
```

user_voucher table will insert 100 entries only. These entries will have following types of entries:

User 1 => Voucher 1
User 2 => Voucher 1
User 3 => Voucher 2 and so on..

This means multiple users can have 1 voucher.

But, how do I achieve following:

User 10 => Voucher 12
User 10 => Voucher 13
User 10 => Voucher 14 and so on..

If I do this,
```
AppBundle\Entity\Voucher:
    voucher{1..200}:
        users: ['@user<numberBetween(1, 100)>']
```

It does not insert anything into join table.

That means how do I achieve multiple vouchers for 1 user?

**Comment by theofidry** [comment]
Apologize for the late answer. This should work so I can't really tell what is wrong but I would suppose it depends of how you configured your objects (both PHP & the doctrine mapping). I would suggest to inspect the generated graph of objects to see if it's the expected result and then check if they are persisted properly.

For further questions please ask on the Slack channel
