### ISSUE TITLE
hardcode relation id on table with relations when loading fixtures

### ISSUE THREAD

**Issue by dlanoire** [hautelook/AliceBundle#401]
In my test database, I load some configuration tables from xml files with Symfony console command application.
I also load some tables with hautelook alice fixtures. My problem comes when I try in my fixture, to set a relation column (one-to-many, many-to-one, ...) from a table previously filled by my console command.
If I fill the relation column id with the id value previously generated, the relation column is always NULL and the fixture loading fails.

For instance, I have a table T1 with a primary key id column = 33. This table is loaded by console command application.
I also have a T2 table with a relation column to T1 pk id, loaded by a fixture.
The yaml fixture's excerpt is : 
```
T2:
   data1:
    id: 1 # T2 primary key
    t2_relation_id: 33 # always set to NULL because of the tables relation

```
I need the relation because it eases the Doctrine DQL queries, otherwise I need to manually join the tables and this is dirty coding with an ORM. I also need relations to define foreign keys.

Is there a way to bypass relation objects to hardcode relation id directly ?
I tried to use metadata to bypass relations as I do with AUTOINCREMENT ids, but never succeed.
I also tried to set dummy relation entities but it was not working because of entity database persistence :(

**Comment by tejasnavghane** [comment]
Hi @dlanoire, May be you can try this, similar to T2 fixture, you must be having T1 fixture. Assuming it is like this (given below),
`T1:
t1_data:`
`id: 1 # T1 primary key` (sorry for this sort of formating ;))

Now, for your T2 fixture try this,
`t2_relation_id: '@t1_data33'`

Hope this helps. Please revert if it doesn't. 

Thank you.

**Comment by dlanoire** [comment]
Hi @tejasnavghane,
Thank you for you answer but this is not working because it tries to insert data in T1 previously loaded by a Symfony application, so I get a duplicate key error.

To summarize my problem : part of my data are loaded by a Symfony application (console command) and the remaining, by a yaml Alice fixture and they have relations to table not loaded by fixtures.

Have a nice day (night ?) :)
Regards

**Comment by theofidry** [comment]
Hi,

You can inject those related objects while loading it: https://github.com/theofidry/AliceDataFixtures/blob/master/src/LoaderInterface.php#L25

For further support questions, please ask on the Symfony slack or other
