### ISSUE TITLE
Option "--purge-with-truncate" seems not work

### ISSUE THREAD

**Issue by bastos71** [hautelook/AliceBundle#411]
Hi there ! 

It seems that the option `--purge-with-truncate` does not correctly truncate tables.
I did not have error messages, but when I ran my test suite, I had errors that clearly show IDs' increment were not reset 

```
... cannot take "3" as a value (possible values: 12, 13, 14, 15, 16, 17, 18, 19, 20, 21) ...
```

I recently ran a `composer update`, and now running on `hautelook/alice-bundle v1.4.1`

**Comment by theofidry** [comment]
Hi, sorry I'm not really willing to look at the 1.x version anymore. I'll gladly receive any PR fix provided the CI is green but not more.
