### ISSUE TITLE
Shortcut for "--manager" option does not work

### ISSUE THREAD

**Issue by benr77** [hautelook/AliceBundle#433]
If I run `hautelook:fixtures:load --manager=someothermanager` then it tries to operate with the specified entity manager instead of the default. (side note, I don't think this is currently working - am following https://github.com/theofidry/AliceDataFixtures/pull/99 - please advise if this is the case)

The `--manager` option  has a shortcut version specified as `-em`. However, this does not work, and instead the console command tried to look for an environment called `m` via the `-e` switch, which globally is a shortcut for `--env`. So I don't think an option shortcut should have more than 1 character.

Other Symfony commands use `--em` to specify the entity manager, and it's confusing that this bundle uses `--manager` instead. Would it be possible to remove the broken option shortcut `-em` and replace it with another full option `--em` which would both fix the problem and make things consistent with other commands and be backwards compatible.

Any thoughts?

**Comment by theofidry** [comment]
If the shortcut `-em` does not work then it should be fixed or removed, but I'm a bit more reluctant to change `--manager` to `--em` unless it's done in a BC way

**Comment by theofidry** [comment]
>Why don't we change -em to just -m which is currently unused and is a logical shortcut for --manager?

Oh I see, yeah 👍 for that one then, PRs are more than welcome :)

>But it does seems a bit odd having two options that do the same thing so happy to skip this one if you agree?

Agree

**Comment by benr77** [comment]
Done in #435
