### ISSUE TITLE
automatic encoding of password still working ?

### ISSUE THREAD

**Issue by pfleu** [hautelook/AliceBundle#437]
With symfony 4.1 / hautelook 2.3, is the password field of an instance of User class supposed to be filled automatically by encoding 'plainPassword' field, asi it used to be with older versions ? I can't make it work and don't know how to do it "manually".

**Comment by Babacooll** [comment]
Hi, 

I have the same problem here, it does not seem for work.

**Comment by Rikijs** [comment]
Does anyone have found a way to bypass this problem?
Would be grateful for solution.

**Comment by theofidry** [comment]
Could someone pass the link of the feature? It's unclear to me where this is happening.

I vaguely remember an issue with FosUserBundle but IIRC it was solvable by using a custom processor for the user entities. Granted it's not the most DX friendly solution but so far no one has come up with a decent PR addressing this issue.

**Comment by MendicantBias90** [comment]
I cannot find this feature, but  the fastest solution I found was register a custom faker provider, something along the line of:
```
namespace App\Faker\Provider;

use Faker\Provider\Base as BaseProvider;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

final class PasswordProvider extends BaseProvider
{
    private $encoder;

    public function __construct(UserPasswordEncoderInterface $encoder) {
        $this->encoder = $encoder;
    }

    public function encodePassword($user, string $plainPassword)
    {
        return $this->encoder->encodePassword($user, $plainPassword);
    }
}
```
and them using it in my fixture file like:
```
App\Entity\User:
    user:
        password: <encodePassword(@user, 'yourpassword')>
        email: tirengarfio@gmail.com
```

**Comment by theofidry** [comment]
I think @MendicantBias90 way is the way to go. I don't know if a generic way could be provided, but alternatively maybe setting the encoding to plain password for the tests (which also speed them up btw) would help.
