### ISSUE TITLE
Using pre-exists value

### ISSUE THREAD

**Issue by iBasit** [hautelook/AliceBundle#443]
I have a table that has pre-filled values from start, which I can't purge it (as a company requirement).

How can I use foreign key entity existing value in my object? 

If I just use the value id 3, the class object return error, saying only entity object needs to be added and not the integer. 

How can I fetch entity value and add that as a foreign key value in the object I'm storing?

**Comment by theofidry** [comment]
You won't be able to do that with the native command, you either will have to extend it or decorate a loader used.

The core issue is that you are using IDs and foreign keys to set your relations with auto-generated values: this is a very bad idea in general for various reasons.

But back to your issue: one thing you could do retrieve the existing objects from your DB and inject them while loading the fixtures: https://github.com/theofidry/AliceDataFixtures/blob/master/src/LoaderInterface.php#L25
