### ISSUE TITLE
Usage with in memory SQLite 

### ISSUE THREAD

**Issue by GaryPEGEOT** [hautelook/AliceBundle#446]
I'm trying to use the bundle in test environment with `ReloadDatabaseTrait`, but as my database doesn't exists, I get an error saying it can execute `DELETE FROM my_table`. Is there a "nice way" to recreate the database schema on the fly with the bundle?

**Comment by theofidry** [comment]
Maybe it's possible, but AFAICS the code currently assumes you have a schema up to date and it looks reasonable to me to ensure the schema is up to date before running the tests. The bundle either delete or truncate the data and I don't it should drop and create again the whole schema.

**Comment by theofidry** [comment]
Alternatively you could have a `bootstrap.php` file for your tests where you set-up the database

**Comment by theofidry** [comment]
After thinking about it, I guess that's fine. Not a big fan of it but I suppose there is some usages. Thanks for the PR, it has been merged. I'll try to take a look this week or next for a release
