### ISSUE TITLE
Problems with non entity objects and phpcr-odm

### ISSUE THREAD

**Issue by uwej711** [hautelook/AliceBundle#45]
currently phpcr-odm throws an exception, when asking for metadata of a non mapped class, so the check in hasIdentity in https://github.com/hautelook/AliceBundle/blob/master/Alice/Loader.php#L187 fails with an exception. Also detaching the references in https://github.com/hautelook/AliceBundle/blob/master/Alice/Loader.php#L109 should honour non entity objects.

I propose to add a method contains to class Doctrine and use that for checking for non entity objects (can do the PR ...)

**Comment by veewee** [comment]
Also having this issue with ValueObjects located outside the Entity folder in ORM.
The solution seems to catch the Doctrine\Common\Persistence\Mapping\MappingException error.
When no mapping is found: it is a value object.
