### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#450]
It looks like PHP-CS-Fixer is being run against the Symfony fixture app cache which it shouldn't: https://travis-ci.org/hautelook/AliceBundle/builds/462907694?utm_source=github_status&utm_medium=notification

**Comment by GaryPEGEOT** [comment]
It has been fixed by https://github.com/hautelook/AliceBundle/pull/447, but I thing we should probably include `src` and `tests` instead of `__DIR__`, that will prevent bad surpises

**Comment by theofidry** [comment]
Indeed that would be a better way to do it
