### ISSUE TITLE
Dynamic parameters do not work as stated in the documentation

### ISSUE THREAD

**Issue by lucassimonin** [hautelook/AliceBundle#452]
- PHP 7.2
- Symfony 4.2
- hautelook/alice-bundle: 2.3.0

```
parameters:
    stock_1: 10
    stock_2: 0
App\Entity\ProductLog:
    productLog{1..2}:
        stock: '<{stock_<current()>}>'
```

```
In ExpressionLanguageExceptionFactory.php line 69:
                                
  Could not lex the value ">".
```

the documentation: https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#dynamic-parameters

What am I doing wrong?

**Comment by theofidry** [comment]
I think the doc and syntax is ok. It's probably Alice's lexer that has an issue. Could you open an issue about it in `nelmio/alice`?

**Comment by lucassimonin** [comment]
Ok no problem :)
