### ISSUE TITLE
 The file "/srv/fixtures/AliceFixtures.php" must return a PHP array.

### ISSUE THREAD

**Issue by tudorluchy** [hautelook/AliceBundle#454]
Hello,

I use symfony4 and mongodb, Hautelook bundle to make some fixtures.
First question, it is compatible with MongoDB ?

After installing it, I want to load some fixture but i always have the same error.

```php
<?php

use Doctrine\ORM\EntityManagerInterface;
use Hautelook\AliceBundle\LoaderInterface;
use Symfony\Bundle\FrameworkBundle\Console\Application;

class AliceFixtures implements LoaderInterface
{
    public function load(Application $application, EntityManagerInterface $manager, array $bundles, string $environment, bool $append, bool $purgeWithTruncate, string $shard = null)
    {
        $files = [
            __DIR__ . '/trainee.yml',
        ];
        return $files;
    }
}
```

>  The file "/srv/fixtures/AliceFixtures.php" must return a PHP array.

Can anyone help me please ? Thanks

**Comment by theofidry** [comment]
>First question, it is compatible with MongoDB ?

MongoDB support has been added in [theofidry/AliceDataFixtures](https://github.com/theofidry/AliceDataFixtures). There is currently no support for it in HautelookAliceBundle but that could be added without too much trouble. [Here](https://github.com/hautelook/AliceBundle/tree/master/src/Console/Command/Doctrine) is the example for the Doctrine ORM command, another class could be added for Doctrine ODM.

**Comment by theofidry** [comment]
Ah actually I figured it out, I think you are confusing something. HautelookAliceBundle no longer supports the custom loaders like there was before a la DoctrineFixturesBundle. If you just want your file `'trainee.yml'` to be loaded put it in `fixtures` and running the command will load it.

You can ask more questions about it in the Slack channel (cf. the badge in the readme) for more answers :)

**Comment by tudorluchy** [comment]
I have put it in fixtures folder but nothing happens : 

$ docker-compose exec app php bin/console hautelook:fixtures:load
Careful, database will be purged. Do you want to continue y/N ?y

and nothing in the database...

**Comment by tudorluchy** [comment]
Do you have an exemple of php class of theofidry/AliceDataFixtures to load yml files ?

Thanks

**Comment by theofidry** [comment]
>I have put it in fixtures folder but nothing happens

You need to check your configuration, cf the end of [the installation instructions](https://github.com/hautelook/AliceBundle#installation). You can also use `-vvv` to list the files found.

>Do you have an exemple of php class of theofidry/AliceDataFixtures to load yml files ?

[The basic usage in theofidry/AliceDataFixtures](https://github.com/theofidry/AliceDataFixtures#basic-usage) should have you covered. If you are confused as to what is from AliceDataFixtures and what is from HautelookAliceBundle, I recommend you to read [this section](https://github.com/hautelook/AliceBundle#when-to-use-this-bundle)

**Comment by tudorluchy** [comment]
```
$ docker-compose exec app php bin/console hautelook:fixtures:load -vvv
Careful, database will be purged. Do you want to continue y/N ?y
20:33:04 INFO      [app] fixtures found
[
  "files" => []
]
20:33:04 INFO      [app] Purging database with purge mode "DELETE_MODE".
20:33:04 INFO      [app] Loading fixtures.
20:33:04 INFO      [app] Pre-processing objects.
20:33:04 INFO      [app] Flushing objects.
20:33:04 INFO      [app] Post-processing objects.
20:33:04 INFO      [app] Done.
20:33:04 INFO      [app] fixtures loaded
`

**Comment by tudorluchy** [comment]
```
$ docker-compose exec app php bin/console hautelook:fixtures:load -vvv
Careful, database will be purged. Do you want to continue y/N ?y
20:34:30 INFO      [app] fixtures found
[
  "files" => [
    "/srv/src/fixtures/trainee.yml"
  ]
]
20:34:30 INFO      [app] Purging database with purge mode "DELETE_MODE".
20:34:30 INFO      [app] Loading fixtures.
20:34:31 INFO      [app] Pre-processing objects.
20:34:31 INFO      [app] Flushing objects.
20:34:31 INFO      [app] Post-processing objects.
20:34:31 INFO      [app] Done.
20:34:31 INFO      [app] fixtures loaded
`

**Comment by theofidry** [comment]
>But nothing to the mongodb database.

I would double check what is going on in `Flushing objects.` (e.g. with a breakpoint), like see if the right object manager is being used

**Comment by tudorluchy** [comment]
I'm using mongodb, so hautelook command does not work which is normal I understand.
