### ISSUE TITLE
@ORM\OneToOne: Multiple non-persisted new entities were found.

### ISSUE THREAD

**Issue by tulik** [hautelook/AliceBundle#459]
Hello, I have an issue with loading fixtures with Entity that has `OneToOne` relation. 

My entities:

**Foo.php**

```php
class Foo
{
    /**
     * @ORM\Id
     * @ORM\Column
     * @ORM\GeneratedValue
     *
     */
    public $id;

    /**
     * @ORM\OneToOne(targetEntity=Bar::class)
     */
    public $bar;
}
```

**Bar.php**

```php
class Bar
{
    /**
     * @ORM\Id
     * @ORM\Column
     * @ORM\GeneratedValue
     *
     */
    public $id;

    /**
     * @var string
     *
     * @ORM\Column
     */
    public $any;
}
```

**data.yaml**

```yaml
include:
  - data/bars.yaml
  - data/foos.yaml
```
**bars.yaml**

```yaml
App\Entity\Bar:
  bar_{1..10}:
    any: '<md5()>'
```

**foos.yaml**

```yaml
App\Entity\Foo:
  foo_{1..10}:
    bar (unique): '@bar_*'
```

Fixtures directory structure:

```
fixtures
└── dev
    ├── data
    │   ├── bars.yaml
    │   └── foos.yaml
    └── data.yaml
```

### Error:

> Multiple non-persisted new entities were found through the given association graph:
> 
>    * A new entity was found through the relationship 'App\Entity\Foo#bar' that was not configured to cascade persist operations for entity: App\Entity\Bar@000000004a2b0c9c0000000000e83503. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"
>   persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\Bar#__toString()' to get a clue.
> ...

When  `..., cascade={"persist"}` is present I have duplicated (20 in total) _Bars_ in DB.

**Comment by theofidry** [comment]
Can you try to create a dedicated repository to reproduce the issue?

**Comment by tulik** [comment]
I solved the issue by removing `unique` and changing  `@bar_*` to `@bar_<current()>` .

**foos.yaml**

```yaml
App\Entity\Foo:
  foo_{1..10}:
    bar: '@bar_<current()>'
```
Thanks.
