### ISSUE TITLE
The DoctrineOrmLoadDataFixturesCommand is not extendable

### ISSUE THREAD

**Issue by Maxooo** [hautelook/AliceBundle#460]
Hello,

It is currently impossible to override the `hautelook_alice.console.command.doctrine.doctrine_orm_load_data_fixtures_command` service (command) as the `DoctrineOrmLoadDataFixturesCommand` is currently declared as a `final class`.
In fact it's possible to override the service but we have to copy past the most of this class code which is quite frustrating.

Did I missed something ? Is it a special choice or an oversight (in which case I can do the PR) ?

Thank you for the bundle and the support you are providing.

**Comment by theofidry** [comment]
It was probably more out of fear of exposing bad extensions points than anything I think. It's probably fine to make it non-final by now. If I may ask however, what do you need to expand the command for?

**Comment by Maxooo** [comment]
Thank you for your fast answer (and sorry for my late one).
I understand your point of vue and the impact on the modelization (class and properties visibility, services exposition, etc.). You're right, my use case may help you to understand if this request need to be paid attention.

Since the version 2 it's possible to use environments to contextualize generated data : this was one of the great improvements of this version (with performance enhancements). But you know it, more is never enough. We (me and our teams) now need to use this system with contextualized data. For example I need to generate production-like data (environment feature support it) but in the IT domain (which is a context) with this kind of records : computers, motherboard, memory, etc. But tomorrow, I would like to generate production-like data in the food domain with this kind of records : Wine, Beer, Cider, etc.

So, I am overriding the `DoctrineOrmLoadDataFixturesCommand` command to support a new optional argument `contexts` (comma separated list) to provide a custom fixtures categorization and I also will use a `CustomFixtureFilesLocator` (as described in the documentation to change loading order) to load fixtures files depending on the provided contexts. 

I am thinking about this directory structure : 
```
└── fixtures/ or app/Resources/fixtures/
    ├── environmentless-fixture1.yml
    ├── ...
    ├── inte
    |   ├── prod-fixture1.yml
    |   └── ...
    ├── dev
    |   ├── dev-fixture1.yml
    |   └── ...
    └── custom
        ├── food
        |   └── food-fixture1.yml
        ├── it
        |   └── it-fixture1.yml
        └── ...
```

As you can imagine, in my Command class overriding the `DoctrineOrmLoadDataFixturesCommand` service I just need to add an option in the `configure` method which I can't do without copying/pasting the original `final` class.

If I am not clear enough, please let me know : I will do my best to reformulate.
I dont know if this use case can interest anyone, but if so, may be this could be a new feature to consider with a better implementation than this (tricky) one.

Thank you again.

**Comment by theofidry** [comment]
Not it makes sense to me, I think it's ok to remove the final for the commands
