### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

### ISSUE THREAD

**Issue by gabiudrescu** [hautelook/AliceBundle#461]
The message in the issue description is displayed when this bundle is installed on a Symfony 4.2 app.

I can provide a fix as a PR.

**Comment by mdeboer** [comment]
The fix is already in master but hasn't been released yet. I wonder when we see a new release.

**Comment by pierrejolly** [comment]
Just to know, [2.5.0](https://github.com/hautelook/AliceBundle/releases/tag/2.5.0) has been released few days ago and issue still present, I have missed something ?
