### ISSUE TITLE
Typo in semantic version (2.5.0 -> v2.5.0)

### ISSUE THREAD

**Issue by thomas-rolling** [hautelook/AliceBundle#471]
Here is a typo in semantic version.

Last version is `2.5.0` instead of `v2.5.0`

**Comment by theofidry** [comment]
I fixed the name in the release list but changing the tag would be overkill for it and it shouldn't affect the way you request versions in your `composer.json`

**Comment by thomas-rolling** [comment]
Thanks Theo
