### ISSUE TITLE
ensureKernelTestCase is wrong

### ISSUE THREAD

**Issue by MLDMoritz** [hautelook/AliceBundle#472]
Hey,

I'm using JsonApiTestCase which extends ApiTestCase which extends WebTestCase which extends KernelTestCase.

It's throwing the LogicException mentioned in ensureKernelTestCase.

If I comment out `static::ensureKernelTestCase();` it's working just fine.

**Comment by theofidry** [comment]
Sorry cannot help without any stack trace or more detailed error
