### ISSUE TITLE
What's the cleanest way to enable both RecreateDatabaseTrait and RefreshDatabaseTrait?

### ISSUE THREAD

**Issue by Evertt** [hautelook/AliceBundle#477]
Because if I just mention both traits then I get a conflict:

```
PHP Fatal error:  Trait method bootKernel has not been applied, because there are collisions with other trait methods on App\Tests\ApiTest in /Users/evert/Sites/todo/tests/ApiTest.php on line 14
```

**Comment by theofidry** [comment]
I don't think you should:

- recreate is meant to drop and create the schema in-between each test on `setUp()`
- refresh is meant to wrap each test in a transaction and rollback on `tearDown()`

What would be the use case for having  a combinaison of both?
