### ISSUE TITLE
Trying to use --env= parameter without success event after following documentation

### ISSUE THREAD

**Issue by zehunter** [hautelook/AliceBundle#481]
Hi, 

in need to use fixture as basic preloaded data for now on prod env before using real data. So i'm in PROD and i tryed to put fixutes into ./fixtures/ directory (in flex symfony 4 project)

When you read doc, ./fixtures/ is envoronment-less files ... but i get this :

php bin/console hautelook:fixtures:load -vvv 
Careful, database will be purged. Do you want to continue y/N ?y
18:02:53 INFO      [app] fixtures found
[
  "files" => []
]
18:02:53 INFO      [app] Purging database with purge mode "DELETE_MODE".
18:02:53 INFO      [app] Loading fixtures.
18:02:53 INFO      [app] Pre-processing objects.
18:02:53 INFO      [app] Flushing objects.
18:02:53 INFO      [app] Post-processing objects.
18:02:53 INFO      [app] Done.
18:02:53 INFO      [app] fixtures loaded

i tryed --env=inte like in the documentation, and move my files to ./fixtures/inte/ but i have this result : 

php bin/console hautelook:fixtures:load -vvv --env=inte
Careful, database will be purged. Do you want to continue y/N ?y
'NOTHING IN OUTPUT CONSOLE'

and if i try --env=prod it's the as without --env (still no fixture files found). Like only DEV is taking into account. 

Any one can help me understand ? documentation is wrong? there is a bug ?

**Comment by theofidry** [comment]
Hi, thanks for the report. Is there any way to reproduce this or even better could you provide a reproducer?

**Comment by zehunter** [comment]
Sorry it was my mistake i didn't copy the config on prod folder
