### ISSUE TITLE
Fixtures and cascade persist ?

### ISSUE THREAD

**Issue by apsylone** [hautelook/AliceBundle#483]
Hi,

I met a strange problem. Maybe Am I using it not correctly ?

I have two entities : "Quiz" and "Question".

```
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quiz", inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $quiz;

...
}

class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Question", mappedBy="quiz", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $questions;

...
}
```

```
App\Entity\Quiz:
  quiz_{1..5}:
    questions (unique): '4x @question_*'

App\Entity\Question:
  question_{1..20}:
    question (unique): '<sentence()> ?'
```

You could see the relation "questions" in "Quiz" is a ManyToOne with a cascade persist/remove.

I have to remove the "@ORM\JoinColumn(nullable=false)" on it to make it works because I have 40 questions generated in database ("5 x '4x @question_*' = 20" + "question_{1..20}"). 

That's a bit strange because I think I would have to generate 20 questions (5 quiz x '4x @question_*' ).

So the "unique" give "NULL" on the relation because there's no more Quizz (5 quizz with 5 questions vs 40 questions generated in total) available.

A bit strange, no ? I hope i'm clear :)

**Comment by theofidry** [comment]
I am not entirely sure how unique operates with objects, but I would suggest dumping/inspecting your fixtures before they are being persisted to identify if it's a nelmio/alice problem/a fixture problem or a doctrine/persistence problem
