### ISSUE TITLE
installation details

### ISSUE THREAD

**Issue by allotmentandy** [hautelook/AliceBundle#49]
the readme.md file says install alice (version 0.2 is now the default)

then it says install alice v.0.1 which removes the 0.2 version you just installed. 

what you recommend?

**Comment by theofidry** [comment]
From what I see any version earlier than the 0.1.4 is a pre-release, so at least the 0.1.4. If you can use the last version, do so :)

**Comment by theofidry** [comment]
@allotmentandy should be cleared in the new version.

**Comment by theofidry** [comment]
Closing it for now as the question is very old. Feel free to manifest yourself.
