### ISSUE TITLE
Data Provider operations are being cleaned before test method when using DB traits

### ISSUE THREAD

**Issue by Scrocrix** [hautelook/AliceBundle#490]
Hi everyone,

Recently I've caught up myself trying to resolve (what I assume it's a bug) an issue I was having while using either `RecreateDatabaseTrait`, `RefreshDatabaseTrait` or `ReloadDatabaseTrait` with `@dataProvider` annotation from PHPUnit.

As for the [PHPUnit documentation](https://phpunit.readthedocs.io/en/8.5/writing-tests-for-phpunit.html) this what they say:

> All data providers are executed before both the call to the `setUpBeforeClass()` static method and the first call to the `setUp()` method. Because of that you can’t access any variables you create there from within a data provider. This is required in order for PHPUnit to be able to compute the total number of tests.

Accordingly to the statement above, the Data Providers are executed even before the class is set up which causes a bit of overhead when performing functional test operations (in my case I'm interacting with Doctrine's Entity Manager).

Very well I've created my own provider methods, that basically build up a new entity class and then I persist/flush it into my test database. Then I declare it using the `@dataProvider` annotation to use it in my tests.

Now here comes the problem, because all Data Provider methods get executed before the test, it seems like the DB traits from Alice are wrapping these the operations (e.g. persist/flush) in a transaction and then getting rid of it after (before executing my test).

In some cases, if I ran just one test method, let's call it `Method B` using `@dataProvider A`, it would fail because PHPUnit would execute all Data Providers, the DB traits would wrap those operations up and clean it after the execution, making `Method B` fail since it would end up using the `@dataProvider B` from another test method, for example.

**Comment by theofidry** [comment]
The main issue here IMO is that you are trying to set up fixtures with side effects (persisting stuff in the DB) in the data provider. This is as you are experiencing quite troublesome because the data provider time of execution might change (e.g. there is plans to make it lazily in PHPUnit 9 IIRC whereas it's one of the first thing called right now to know all the tests to execute).

IMO you are better off either having global fixtures loaded before running your tests (which I don't recommend as it tends to make your test more brittle) or on a test basis by loading them within the test (and then will be rolledback by the transaction)

**Comment by Scrocrix** [comment]
> @theofidry or on a test basis by loading them within the test (and then will be rolledback by the transaction)

My solution exactly 😄 I've been pondering the idea of using Data Providers for side-effected fixtures as you said. It seems to me like an elegant way of handling such situations, instead of calling it within my tests.

Although now I realize that my previous approach was not "so good" since Data Providers were conceived to solve static-like fixtures situations.

Thank you for such a fast response. I'm alright with closing this issue if you don't have anything else to say.
