### ISSUE TITLE
Improvement: Access references after fixtures load

### ISSUE THREAD

**Issue by pierre-moire** [hautelook/AliceBundle#491]
I would like to use this library to load fixtures during PHPUnit tests setUp and have the ability to use objects I created in my tests by getting them through references.

The main interest here would be a way to have very clean and understandable test cases by using meaningful reference names. DoctrineFixturesBundle allows this (getReference / setReference) but lacks a lot of powerful features brought by this library and requires the fixtures to be written in PHP (vs yaml).

The issue is: references are used in the context of the load and are not accessible after the load. Loaders that could probably allow this have no public method to access them.

Any idea how it can be done or what can be changed in this library to do this?

**Comment by theofidry** [comment]
I think https://github.com/theofidry/AliceDataFixtures would be a better fit than HautelookAliceBundle for that

**Comment by pierre-moire** [comment]
Hi, thanks for the feedback. Should I recreate this ticket there then?

**Comment by theofidry** [comment]
I think you already have this: you can inject the objects for the load (you have an `parameters` and `objects` optional parameters for the loader) and you can retrieve the loaded objects as well. Or is it something else?

**Comment by pierre-moire** [comment]
Hmm sorry I don't see how it could work. Here are more details about how I would like to achieve it

My fixtures
```
App\Entity\User:
  dummyUser:
    name : ...
```

My tests:
```
public function __construct(<injected loader or something>){
  $this->loader = $loader;
{

public function setUp(){
<load the fixtures (how?)>
}

testMyUser(){
$dummyUser = $loader->getReference("dummyUser");
... test it...
}
```

**Comment by theofidry** [comment]
As per https://github.com/theofidry/AliceDataFixtures#basic-usage

```php
<?php

$files = [
    'path/to/src/AppBundle/Resources/fixtures/dummy.yml',
    'path/to/src/AppBundle/Resources/fixtures/related_dummy.yml',
];

$loader = $container->get('fidry_alice_data_fixtures.loader.doctrine');

$objects = $loader->load($files);

$dummyUser = $objects['dummyUser'];
```

**Comment by pierre-moire** [comment]
Seems great but are objects keeping original references?

By reading the documentation I thought $objects is an array of unkeyed objects or something like 
```
[
"AppBundle\Entity\Dummy" => (array of items without keys),
... another entity type
]
```

Is it the case?

**Comment by theofidry** [comment]
The loader creates objects and return them: there is no clear in-between so what you have _are_ the original ones. `$objects` is an array with all the fixture IDs as keys

**Comment by pierre-moire** [comment]
I am not sure I was totally clear but I could see how it is structured and access data, thanks for your help!

```
var_dump(self::$fixtures["utilisateur_organisme_1"]->getId());
var_dump(self::$fixtures["utilisateur_organisme_1"]->getPrenom());
```

![image](https://user-images.githubusercontent.com/2143238/72078266-1348b900-32f9-11ea-8d0e-bd0c24b6e31c.png)

**Comment by pierre-moire** [comment]
I wanted to achieve something like this :

![image](https://user-images.githubusercontent.com/2143238/72078467-6fabd880-32f9-11ea-9668-59dbb61d3d85.png)
