### ISSUE TITLE
File type from vichuploadbundle

### ISSUE THREAD

**Issue by bettinz** [hautelook/AliceBundle#498]
Hello, I've an entity called "MediaObject" and an Entity called "MediaObjectImage" that extends MediaObject.

In MediaObjectImage I've this property:

```php
/**
     * @var File|null
     *
     * @Assert\NotNull(groups={"media_object_create"})
     * @Assert\File(
     *     maxSize="5242880",
     *     mimeTypes = {
     *          "application/jpg"
     *      }
     * )
     * @Vich\UploadableField(mapping="media_object_image", fileNameProperty="filePath", mimeType="mimeType")
     */
    private $file;
```

How can I "pass" a file from Fixtures yaml? I've tried with the path like:
App\Entity\MediaObjectImage:
  media_financial_image_1:
    file: '@./build/dummy/image/image.jpg'
    id : '0d1253f2-ebb6-4194-a22c-57c4b2e10b94'

But the error is:
```
  Expected argument of type "Symfony\Component\HttpFoundation\File\File or null", "string" given at property path "file".  
```

Can you help me? Thanks

**Comment by theofidry** [comment]
I think you would either need to create an instance of the file first:

```yaml
Symfony\Component\HttpFoundation\File\File:
  image_1:
    __construct: ['./build/dummy/image/image.jpg']
```

(this is pseudo code you would need to check how that object needs to be instantiated)

Or rely on a [custom data provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers)

**Comment by bettinz** [comment]
Thanks 😄
