### ISSUE TITLE
RefreshDatabaseTrait without initial import of fixtures

### ISSUE THREAD

**Issue by tjveldhuizen** [hautelook/AliceBundle#506]
Is it possible to use the RefreshDatabaseTrait on my tests, without truncating the database and importing al fixtures? As long as the trait is used on all tests, the final state of the database is OK to start with in the next test run. This would speed up my test runs.

**Comment by bachinblack** [comment]
Hey!

Just spent some time playing around with the database traits, so I might be able to help you.

I'm not sure what you mean, you'd like to prevent the trait from loading the fixtures before the first test and then have it work normally (reload the database before each test)? Doing so would only save a second.

**Comment by tjveldhuizen** [comment]
My database has 318 tables, with many foreign keys between them. Truncating all tables takes like 15 seconds and inserting all fixtures also takes some time. All my tests use the RefreshDatabaseTrait and don't use the static::$fixtures-array.

While developing, I'ld like to run the tests for a specific class very often (and almost a minute waiting time is a pain). Because the trait prevents modifications to the database, it is not necessary to bring the database back to the initial state, since it's in that state already.

So I really want to get the advantages of the 'start transaction' and 'rollback' in the bootkernel and ensurekernelshutdown-hooks, but I don't need the DB initialization at that moment. When I need initialization, I can do that manually using the bin/console-command.

PS. Using delete-statements is faster, but unfortunately many tests depend on the ID's of objects, which change in each reload without truncate.

**Comment by bachinblack** [comment]
Then how about making your own `DatabaseTrait`?  
`RefreshDatabaseTrait` is fairly simple, I had no trouble changing the logic to my tastes:
- Replaced `TRUNCATE` with `DELETE` (which apparently you can't do)
- Made it so that `populateDatabase()` would only be called after a test has altered the db.

It's fine for my small project but I understand it's not enough for yours.
I haven't tried `START TRANSACTION` and `ROLLBACK` so I won't be of any help, sorry.
However, I'm not sure it's still related to how `RefreshDatabaseTrait` works.

**Comment by tjveldhuizen** [comment]
The relation is that the trait does the `START TRANSACTION` and `ROLLBACK`. Of course, overriding is an option, but I don't want to do that if it's an existing feature. Hence my question.

**Comment by theofidry** [comment]
I think rolling your own trait would be the solution here. I'm not too keen to add different ways to use such a small trait, even more so because it's a trait which is brittle by nature
