### ISSUE TITLE
ReloadDatabaseTrait does not reload the database

### ISSUE THREAD

**Issue by adityarai** [hautelook/AliceBundle#509]
Hi, I have installed symfony 4.4.11 and have added some test cases for importing csv data to database through command line but when I run testcases it does not purge database.

``<?php

namespace App\Tests\Command;

use Hautelook\AliceBundle\PhpUnit\ReloadDatabaseTrait;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class ImportUserCommandTest extends KernelTestCase
{
    use ReloadDatabaseTrait;

    public function testCommandUploadInitUserCsv()
    {
        $kernel = static::createKernel();
        $application = new Application($kernel);

        $command = $application->find('app:import-user');
        $commandTester = new CommandTester($command);
        $commandTester->execute([
            // pass arguments to the helper
            'file' => 'tests/Import/new_user.csv',

            // prefix the key with two dashes when passing options,
            // e.g: '--some-option' => 'option_value',
        ]);

        // the output of the command in the console
        $output = $commandTester->getDisplay();
        $this->assertContains('Finished importing products.', $output);
    }
}``

**Comment by theofidry** [comment]
Are you properly booting the kernel?

**Comment by adityarai** [comment]
@theofidry .. thanks, self boot kernel did the job..
``<?php

namespace App\Tests\Command;

use App\Entity\Employee;
use App\Tests\Service\BaseBuilderService;
use App\Tests\Service\BookingBuilderService;
use App\Tests\Service\EmployeeBuilderService;
use Hautelook\AliceBundle\PhpUnit\ReloadDatabaseTrait;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class ImportUserCommandTest extends KernelTestCase
{
    use ReloadDatabaseTrait;

    public function testCommandImportSimpleEmployeeCsv()
    {
        $application = new Application(self::bootKernel());

        $command = $application->find('app:import-user');
        $commandTester = new CommandTester($command);
        $commandTester->execute([
            // pass arguments to the helper
            'file' => 'tests/Import/new_user.csv',
        ]);

        // the output of the command in the console
        $output = $commandTester->getDisplay();
        $this->assertContains('[OK] Total no. of employee(s) added : 4', $output);
    }
}``
