### ISSUE TITLE
Is this bundle dead?

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#51]

**Comment by hjr3** [comment]
@baldurrensch do you have any interest in keeping this bundle up to date?

**Comment by theofidry** [comment]
:(

**Comment by hjr3** [comment]
A few things:

1) Alice does not scale well for a large fixture data set. We use it some places, but have moved to a different system that handles our large data set better.
2) The person who wrote this bundle, @baldurrensch , is at a different company.

If someone wants to help maintain this bundle, we can ceratainly provide write access or we will support a fork.

**Comment by theofidry** [comment]
Thanks for your answer @hjr3.

Well, IMO there is several issues:
* generators are kept internal to loaders making it difficult to share the same instance of Faker (which might be useful if you wish to set a specific seed)
* keeping the generators internal doesn't make really sense since most providers needs to be injected a faker instance to be instantiated and we inject directly providers to loaders
* the responsibility of the [DataFixturesLoader][2] is not clear: it behaves as both a Doctrine fixtures interface and a provider
* defining custom providers outside the [DataFixturesLoader][2], like [Faker's providers](https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider), is not simple

Some issues make it difficult to scale it for large set of data, which is a pity since a really useful system to play with different set of data, for testing, integration and production purpose.

Regardless of some design issues, the lack of reactivity for this bundle and [nelmio/alice](https://github.com/nelmio/alice) is definitely a problem. This topic really interest me and I would happily help to develop and maintain this bundle. But some changes would be far from trivial and I'm by no means a senior developer, so it would still require the guidance of some people :)

That being said, while I was looking around thinking of how to redesign this bundle, I've came accross [KnpLabs/rad-fixtures-load][1], much more recent. There is a few things I'm not really happy with and that I would like to change, but it's definitely something worth to check over.

What do you think of it @hjr3? Would it be best to try to change this bundle to achieve our goals or would it be better to try to enhance [KnpLabs/rad-fixtures-load][1]?

cc @dunglas, @PedroTroller

[1]: https://github.com/KnpLabs/rad-fixtures-load
[2]: Alice/DataFixtureLoader.php

**Comment by hjr3** [comment]
If Knp is supporting that repo, then I think we should partner with them to improve that one.

**Comment by theofidry** [comment]
Well, we don't have much visibility about how the bundle will evolves and be managed for now but maybe @PedroTroller will enlighten us :)

Anyway I should still do a PR for this bundle to change a few things that make it easier to define custom faker data providers.

**Comment by PedroTroller** [comment]
Hi @hjr3.

I don't think that the idea of Alice is to provide a system to load a huge amont of data. I'm a supporter of really simple components for really simple tasks.

I think, if you have problems with data loading ascalability and resource dependencies, you don"t have to use Alice, it's not designed for this kind of problems. And so, you don't have to use the rad-fixtures-load.

**Comment by theofidry** [comment]
That being said we have some projects were it handles well a fair amount of data (over 100 fixtures files) for dev/inte/prod usage. For now it's doing well. Where I find it lacking is when it comes to custom data providers which we want to completely extract from the DataFixturesLoader to keep things maintainable and not too messy.

**Comment by theofidry** [comment]
@hjr3 there is a lot of changes with the version `~2.0` of `nelmio/alice`. I think an upgrade will really help it. I'll try to upgrade it on my fork and will do a PR for that :)

**Comment by theofidry** [comment]
@hjr3 could you take a look at [theofidry/AliceBundle](https://github.com/theofidry/AliceBundle)? There is still lots of things to do/check but that's the gist of it, the upgrade of [nelmio/alice](https://github.com/nelmio/alice) changes lots of things but it's a very great upgrade.
