### ISSUE TITLE
Exclude readOnly entities from purge / delete mode

### ISSUE THREAD

**Issue by Neirda24** [hautelook/AliceBundle#510]
Hi. I have several entities with a readOnly mode
```php
/**
 * @Entity(readOnly=true)
 * ...
 */
```
These are SQL views also ignored by doctrine to not mapped the schema diff 
```yaml
doctrine:
    dbal:
        default_connection: 'default'
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: '#^(?!view_).*#'
```
but when trying to insert the fixtures it fails with either :
``` bash
$ # with --purge-with-truncate
SQLSTATE[42809]: Wrong object type: 7 ERROR:  "view_something" is not a table
```

or

``` bash
$ # without --purge-with-truncate
SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  cannot delete from view "view_something"
  DETAIL:  Views containing GROUP BY are not automatically updatable.
  HINT:  To enable deleting from the view, provide an INSTEAD OF DELETE trigger or an unconditional ON DELETE DO INSTEAD rule.
```

any clues ?

Thanks in advance

**Comment by theofidry** [comment]
This probably needs to be fixed in https://github.com/theofidry/AliceDataFixtures. I was not aware there was read-only entities, we probably need to ignore them in the purgers

**Comment by Neirda24** [comment]
ok. should I open a new issue referencing this one then ?

**Comment by theofidry** [comment]
Please 👍

**Comment by Neirda24** [comment]
As stated in https://github.com/theofidry/AliceDataFixtures/issues/141 closing because it was a `schema_filter` error. Sorry for the noise.

**Comment by leandro980** [comment]
Hello, is there a way to avoid purging specific tables? Can it be performed using the `RefreshDatabaseTrait`?
