### ISSUE TITLE
Purger_factory has a dependency on a non-existent service doctrine.orm.entity_manager

### ISSUE THREAD

**Issue by HtunHtunHtet** [hautelook/AliceBundle#512]
I have a Symfony 3.4 application using mongo db and when I try to use faker, I am getting this error

I follow exactly as of documentation and registered as followed in my AppKernel

```
if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle();
            $bundles[] = new Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle();
            $bundles[] = new Hautelook\AliceBundle\HautelookAliceBundle();
        }
```
when i run bin/console, found the following error. 

>  The service "fidry_alice_data_fixtures.persistence.doctrine.purger.purger_factory" has a dependency on a non-existent service "doctrine.orm.entity_manager".

Did I miss out on anything ?

**Comment by theofidry** [comment]
Hi, unfortunately at the moment there is no MongoDB support. https://github.com/theofidry/AliceDataFixtures (the library used underneath) has one IIRC so it should not be too much work to add one to AliceBundle, however no one has come with a PR yet

**Comment by HtunHtunHtet** [comment]
Ok, Thank you @theofidry.
