### ISSUE TITLE
Support for doctrine/common 3.0

### ISSUE THREAD

**Issue by Nyholm** [hautelook/AliceBundle#513]
Im not sure how much/little work it is. :/

**Comment by theofidry** [comment]
That is a good question :) Although I suspect most of the work is going to be in https://github.com/theofidry/AliceDataFixtures

**Comment by theofidry** [comment]
Worth mentioning with https://github.com/theofidry/AliceDataFixtures/pull/113, it might be time to push for a new major release. WDYT @jdeniau do you think including this change (there is a risk we push to common ^3.0 min) is too much of a bump?

**Comment by jdeniau** [comment]
The changes in doctrine/common seems quite little according to the changelog.
I don't think there will be any conflict.

Both changes might be included in the same major releases.

**Comment by Nyholm** [comment]
We do need to allow doctrine/persistence: ^2.0 in this repo though.

**Comment by crbanman** [comment]
It would be great to see this implemented. A new project I'm working on is using doctrine/common:^3.0 and was disappointed when I found out alice-bundle isn't currently compatible.

**Comment by Nyholm** [comment]
WohoO!
