### ISSUE TITLE
Problem installation in symfony 4.4.13

### ISSUE THREAD

**Issue by piterssson** [hautelook/AliceBundle#514]
I'm trying install hautelook/alice-bundle and composer return:
![Zrzut ekranu z 2020-09-06 12-21-49](https://user-images.githubusercontent.com/16086241/92323773-bfcf6c00-f03b-11ea-8c75-95ae6337beaf.png)

**Comment by Shad-Z** [comment]
Same problem with symfony 5.1

**Comment by bernard-ng** [comment]
if you want to use version ^2.7 you should : 

 * Downgrade doctrine/persistence (2.0.0 => 1.3.8)
 * Downgrade doctrine/common (3.0.2 => 2.13.3)

**Comment by theofidry** [comment]
Indeed see #513; PRs are welcome
