### ISSUE TITLE
doctrine/persistence 2.0 compatibility

### ISSUE THREAD

**Issue by coldhu** [hautelook/AliceBundle#519]
Problem 1
    - Conclusion: don't install hautelook/alice-bundle 2.7.3
    - Conclusion: don't install hautelook/alice-bundle 2.7.2
    - Conclusion: don't install hautelook/alice-bundle v2.7.1
    - Conclusion: remove doctrine/persistence 2.0.0
    - Installation request for hautelook/alice-bundle ^2.7 -> satisfiable by hau                                                                                                                                                                                               telook/alice-bundle[2.7.2, 2.7.3, v2.7.0, v2.7.1].
    - Conclusion: don't install doctrine/persistence 2.0.0
    - hautelook/alice-bundle v2.7.0 requires doctrine/persistence ^1.3.4 -> sati                                                                                                                                                                                               sfiable by doctrine/persistence[1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8].
    - Can only install one of: doctrine/persistence[1.3.4, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.5, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.6, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.7, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.8, 2.0.0].
    - Installation request for doctrine/persistence (locked at 2.0.0) -> satisfi                                                                                                                                                                                               able by doctrine/persistence[2.0.0].

**Comment by gherkins** [comment]
same here on sf 4.4

```
composer require --dev hautelook/alice-bundle
Using version ^2.7 for hautelook/alice-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install hautelook/alice-bundle 2.7.3
    - Conclusion: don't install hautelook/alice-bundle 2.7.2
    - Conclusion: don't install hautelook/alice-bundle v2.7.1
    - Conclusion: remove doctrine/persistence 2.0.0
    - Installation request for hautelook/alice-bundle ^2.7 -> satisfiable by hautelook/alice-bundle[2.7.2, 2.7.3, v2.7.0, v2.7.1].
    - Conclusion: don't install doctrine/persistence 2.0.0
    - hautelook/alice-bundle v2.7.0 requires doctrine/persistence ^1.3.4 -> satisfiable by doctrine/persistence[1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8].
    - Can only install one of: doctrine/persistence[1.3.4, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.5, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.6, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.7, 2.0.0].
    - Can only install one of: doctrine/persistence[1.3.8, 2.0.0].
    - Installation request for doctrine/persistence (locked at 2.0.0) -> satisfiable by doctrine/persistence[2.0.0].

**Comment by theofidry** [comment]
See https://github.com/hautelook/AliceBundle/pull/518

You are free to provide help there if you want to speed things up

**Comment by bigfoot90** [comment]
I guess this can be closed now
