### ISSUE TITLE
Possibility to run commands after alice is done

### ISSUE THREAD

**Issue by leroy0211** [hautelook/AliceBundle#522]
Is there a possibility to run commands (query commands, symfony commands, shell commands, etc.) when alice is done loading fixtures into the database. 

My use-case is as follows: 

I have some fixtures for some entities, but that data needs to be compiled in some cache system (in our case, the same database). 
There is a service which "recalculates" the cached value, and that service should be called whenever alice is done. This way the faked data is stored in that compiled cache system instead of having to write fakes for that too.

**Comment by MSiteDev** [comment]
Maybe create a command that will run Alice first and then your command

**Comment by theofidry** [comment]
Indeed the AliceBundle command is merely a Symfony command. The only thing done in this bundle besides that is the finder logic to locate the fixtures which can easily be re-used so you should not have a problem to roll your own command if necessary which I think is more reliable than trying to allow to tweak the HautelookAliceBundle command to allow all sort of customization
