### ISSUE TITLE
Unable to generate fixtures when a datetime is used in a compound primary key

### ISSUE THREAD

**Issue by drupol** [hautelook/AliceBundle#527]
Hello,

I'm trying to generate fixtures for an entity (`TABLE_A`) with a composite primary key.

The primary key is composed of 2 fields:
* `apk1`, type `string`
* `apk2`, type `\DateTime`

I created a temporary project here: https://github.com/drupol/doctrine-date-as-id/

I've explained how to reproduce the issue on the [README](https://github.com/drupol/doctrine-date-as-id/), in only 4 steps.

Warning:

It works when removing `@ORM\Id`, but then, the IRI generated by API Platform is no more valid.

**Comment by theofidry** [comment]
Sorry for the late answer @drupol. I don't think there is any problem on Alice side: the objects are generated as expected (with our without the `@Orm\Id`) so it looks more to be a problem on Doctrine side which appears to expect stringeable only as identifiers at the moment (but I believe you already reported that issue)
