### ISSUE TITLE
RefreshDatabaseTrait per request, not per test

### ISSUE THREAD

**Issue by tylerwiegand** [hautelook/AliceBundle#528]
Refresh/Reload/RecreateDatabaseTraits all seem to work by refreshing between requests, not between tests.

Recreate steps:
1. Install Api Platform
2. Create an entity with @ApiResource (anything, doesnt matter)
3. Create a new test that posts to create a resource and that GET either the index or the individual resource in the same test
4. The resource will not be there. Remove the refresh/reload/recreate trait and it WILL be there.

This might be unique to an install with ApiPlatform, but it's definitely happening. I saw other issues related to the traits, but nothing about this specifically. Maybe something to do with then the kernel is booted and how requests work in ApiTestCase? Not sure. Hopefully someone else has the same issue and can chime in and we can narrow it down.

Related: https://github.com/api-platform/api-platform/issues/1640

**Comment by nathanjisaac** [comment]
@tylerwiegand I ran into this issue yesterday. The solution I found was to only run `self::createClient();` once. Then reference the client for every subsequent request.  

```php
<?php

namespace App\Tests\Functional;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;

class ExampleFunctionalTest extends ApiTestCase
{
    /** @test */
    public function example_test()
    {
        $client = self::createClient();
        
        $response = $client->request(
            'POST',
            '/articles',
            [
                'json' => [
                    'content' => 'some content',
                ],
            ]
        );
        $response = $client->request(
            'POST',
            '/articles',
            [
                'json' => [
                    'content' => 'some content',
                ],
            ]
        );
        
        $response = $client->request(
            'GET',
            '/articles'
        );
    }
}
```

**Comment by theofidry** [comment]
Worth mentioning that in API-Platform the kernel is re-booted between each client call which is a big problem in this scenario and IMO is something that should be fixed on API-Platform side

**Comment by theofidry** [comment]
I'll be closing this since it's an API-Platform issue
