### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by umpirsky** [hautelook/AliceBundle#53]
There is nelmio/alice 2.0.0 available. Bundle should support it.

**Comment by estahn** [comment]
+1

**Comment by umpirsky** [comment]
See https://github.com/hautelook/AliceBundle/pull/58.

**Comment by theofidry** [comment]
Done and the [v1.0.0 beta](https://github.com/hautelook/AliceBundle/releases/tag/v1.0.0-beta) has been released.
