### ISSUE TITLE
Incompatibility with postgresql ?

### ISSUE THREAD

**Issue by rsereir** [hautelook/AliceBundle#530]
When i trying to play fixtures on my local environement with postgresql, i have this error on my User fixtures:
```
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "User"                                               
  LINE 1: INSERT INTO User (id, firstname, lastname, email, roles, pas...                                               

```

it seems hautelook does not add double quote on User table

**Comment by theofidry** [comment]
Isn't it an issue with your Doctrine version/config? Hautelook/alice doesn't do anything custom at that level it uses whatever entity manager/connection you give it

**Comment by rsereir** [comment]
That's what I'm telling myself too.. But when i generate my entity migration i have this request:

```
        $this->addSql('CREATE TABLE "User"  ..... ');
```

Double quote are not added in the `INSERT INTO` request of hautelook. Have you got any solution to solve this issue ? I thought I would rename the table but it bothers me a bit

@theofidry  thanks for your answer

**Comment by SanderVerkuil** [comment]
As far as I know, the `User` keyword is a [reserved keyword](https://www.postgresql.org/docs/7.3/sql-keywords-appendix.html) in Postgres, therefore it is recommended to not name tables like `User`, but rather something like `Person`.

However, this can most likely be fixed though. I've noticed that the Migration generator handles reserved keywords better than the generic Doctrine ORM. A fix could be something along the lines of:

```php
<?php
namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`User`")
 */
class User implements UserInterface
{
  // Your user fields
}
```

I'm not entirely sure if this will work,

**Comment by theofidry** [comment]
AFAICT there is nothing really alice specific here, it boils down to your doctrine config. From what I can see in our apps we don't have anything else than adding the quotes to table as the previous comment suggest
