### ISSUE TITLE
Doctrine use case with OrderedFixtureInterface and DependentFixtureInterface

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#57]

**Comment by vpassapera** [comment]
Why not extend the Abstract Loader object in app land and add `implements OrderedFixturesInterface` and have your Fixtures extend that?

**Comment by theofidry** [comment]
I'll try that. But this issue is no for the current version but for the next one: theofidry/AliceBundle#13

**Comment by vpassapera** [comment]
I don't see why it wouln't (since `hautelook_alice.loader` is a service under the container scope), but that functionality has been effectively been rendered useless since you do the separation not at the FixtureLoader level, but at the yaml level.

**Comment by theofidry** [comment]
Yeah I don't really see the point of this feature, it was more to ensure the full compatibility with [doctrine/DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle). I'll try what you say and unless someone come with a solution, I think I'll just add a mention in the doc if it's not already done.
