### ISSUE TITLE
Loader PHP Files Ignored

### ISSUE THREAD

**Issue by kyaw-myo-thein** [hautelook/AliceBundle#68]
Trying v1.0.0-beta, I encounter this issue.

In v0.2, we have this class 
```class MySampleLoader class extends \Hautelook\AliceBundle\Alice\DataFixtureLoader```. 
In v1.0.0-beta, we adjusted that to extend new class 
```class MySampleLoader extends \Hautelook\AliceBundle\Alice\DataFixtureLoader```. 

However ```app/console hautelook_alice:fixtures:load``` command ignore to load MySampleLoader because it doesn't implement ```Doctrine\Common\DataFixtures\FixtureInterface```. Here is backtrace. 

```
vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php:82
vendor/hautelook/alice-bundle/Doctrine/Finder/Finder.php:39
vendor/hautelook/alice-bundle/Finder/Finder.php:82
vendor/hautelook/alice-bundle/Doctrine/Command/LoadDataFixturesCommand.php:137
```

To fix that, I tried the followings but no luck yet.

1# Implementing both `Doctrine\Common\DataFixtures\FixtureInterface` and `Nelmio\Alice\ProcessorInterface` clash with each other because they expect different parameters for load() function.
2# If we implement only ```Doctrine\Common\DataFixtures\FixtureInterface``` without implementing `Nelmio\Alice\ProcessorInterface`, then there is no benefit in using AliceBundle.

**Comment by theofidry** [comment]
Is there a way for you to show me your code?

Otherwise, your data loaders should now extend `Hautelook\AliceBundle\Doctrine\DataFixtures\ AbstractLoader`, which extends implements `Hautelook\AliceBundle\Doctrine\DataFixtures\LoaderInterface`, an interface extending `Doctrine\Common\DataFixtures\FixtureInterface`.

**Comment by theofidry** [comment]
Is your issue solved @kyaw-myo-thein?

**Comment by kyaw-myo-thein** [comment]
All good now. Thanks a lot @theofidry 

As you suggested, extending ```Hautelook\AliceBundle\Doctrine\DataFixtures\LoaderInterface``` is what I needed to do.

**Comment by theofidry** [comment]
Glad to hear it :)
