### ISSUE TITLE
[Documentation] Fixture file extension?

### ISSUE THREAD

**Issue by alexislefebvre** [hautelook/AliceBundle#77]
In [Basic usage](https://github.com/hautelook/AliceBundle/blob/master/README.md#basic-usage), the documentation says this:

>  Then create a fixture file in `AppBundle/DataFixtures/ORM`:

What is the suggested name for this file?

**Comment by theofidry** [comment]
I recommend the name of your entity, i.e. if your entity is `Dummy`, to call the file `dummy.yml`. Nothing is hard coded so you can pretty much put anything, if you prefer to put it to plurial `dummies.yml` or with the first character uppercase `Dummy.yml` nothing prevent you from doing so.

**Comment by alexislefebvre** [comment]
Ok, my question was more about the file extension. Even if the file looks like an YAML file, I think it's preferable to tell it explicitly. It's better now. Thanks!
