### ISSUE TITLE
Passing Options to Nelmio Alice

### ISSUE THREAD

**Issue by kyaw-myo-thein** [hautelook/AliceBundle#80]
Trying v1.0.0-beta, I wonder how I can pass options to ```nelmio/alice``` such as seed and persist_once although I don't need to use those options just yet. 

[hautelook/AliceBundle]
(
https://github.com/hautelook/AliceBundle/blob/v1.0.0-beta/Alice/DataFixtures/Loader.php#L70
)

**Comment by theofidry** [comment]
Those options are passed via the [Loader constructor](https://github.com/hautelook/AliceBundle/blob/v1.0.0-beta/Alice/DataFixtures/Loader.php#L43-L63).

You can find the loader declaration [here](https://github.com/hautelook/AliceBundle/blob/v1.0.0-beta/Resources/config/services.xml#L24-L30). As you can see, the `seed` and `locale` passed are the one specified in the configuration.

The `persist_once` value cannot be set as by default this would not persist properly relations. If someone need this, he will have to declare he's own loader.

**Comment by kyaw-myo-thein** [comment]
To change ```persist_once```, if I declare my own loader extending AbstractLoader and overwriting (Load method) [https://github.com/hautelook/AliceBundle/blob/v1.0.0-beta/Doctrine/DataFixtures/AbstractLoader.php#L34], Loader constructor is not accepting ```persist_once```, regardless set persist_once to false. I might be overlooking but that's how I understand.

If you could provide code e.g. to pass ```seed``` and ```persist_once```, that'd be greatly appreciated.

**Comment by theofidry** [comment]
Ok I'll add the `persist_once` as an option as other parameter.

Side note: the load method of Doctrine data loaders is never used, see #83.
