### ISSUE TITLE
Public method in the Loader - Not Used for Custom Faker Data Providers

### ISSUE THREAD

**Issue by kyaw-myo-thein** [hautelook/AliceBundle#81]
**In v0.2**, 
we could use public method in the loader as custom faker data providers as in [documentation](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#public-method-in-the-loader). As in e.g, we can use ```name: <groupName()>``` to generate specific group names.

**In v1.0.0-beta**, 
I realised that public methods are not recognised as data provider anymore. In my case, providers are useful only in the context of loader class, so I don't wish to [create separate faker class]( 
https://github.com/hautelook/AliceBundle/blob/master/Resources/doc/faker-providers.md)

**Comment by theofidry** [comment]
I could identify the bug and it's a rather nasty issue. So it will be solved shortly but have to wait a bit.

**Comment by theofidry** [comment]
@kyaw-myo-thein this issue should be solved now, I let you confirm it.

**Comment by kyaw-myo-thein** [comment]
I'll try to give feedback tomorrow (Sydney time).

I had a brief look today, checking out master branch. Switching to ```hautelook_alice:fixtures:load``` command throws unexpected error. I need to investigate further.

**Comment by kyaw-myo-thein** [comment]
It looks good now. Thank for fixing it @theofidry 

I'll close this issue.
